classes/sdimg.bbclass

We need it because we use mkfs.vfat.

Make sdimg depend on native dosfstools.

---

classes/sdimg.bbclass

We need it because we use mcopy.

Make sdimg depend on native mtools.

---

tests/acceptance/README.md
tests/acceptance/pytest.ini

pytest must be called with the '-s' argument or else it will not function correctly.
I've added a pytest.ini file that automatically adds the argument on execution.

Automatically add the '-s' command line argument to pytest

---

scripts/mender-qemu

It's quite annoying since it's common to press Ctrl-C inside the
emulator. The -nographic argument does some extra magic to avoid that.
Use "Ctrl-a x" instead to terminate emulator.

Make Ctrl-c not terminate emulator.

---

README.md

-nographic is default now, so no need to mention that. Instead,
mention how to terminate it.

Update README regarding emulator console access.

---

tests/acceptance/common.py

Systemd should have taken care of the mounting problem, and the mender
binary is always present in the image now.

Remove host preparation that is not needed anymore.

---

tests/acceptance/test_update.py

We don't update the bootcount anymore when Mender commits an update,
because it's not necessary (it's not used as long as
"upgrade_available" is 0), so don't check for that. But add some
additional checks right after we have updated, but before rebooting,
to make sure the expected environment is there.

Follow change in logic regarding bootcount when committing update.

---

recipes-bsp/u-boot/files/0001-beaglebone-mender-specific-configuration.patch

Instead reset and retry from the memory card. Otherwise we do not fall
back to the previous partition, which is both important for testing,
and it is what Mender is supposed to do.
This removes the safety net of falling back to the internal flash
altogether, but I think this is a separate concern that we can tackle
later, perhaps when we have a bit more clarity on what Mender should
do in such a situation.

MEN-307: BBB: Don't fall back on internal flash if boot fails.

---

classes/sdimg.bbclass

Since we prepend the path we need to do it one by one.

Prevent multiple ${IMAGE_BOOT_FILES} entries from breaking the build.

---

classes/sdimg.bbclass

This fixes an error of the type:
```
Couldn't get bitbake variable from .../poky/build/tmp/sysroots/vexpress-qemu/imgdata/core-image-full-cmdline.env.
File .../poky/build/tmp/sysroots/vexpress-qemu/imgdata/core-image-full-cmdline.env doesn't exist.
Traceback (most recent call last):
File ".../poky/scripts/wic", line 321, in <module>
sys.exit(main(sys.argv[1:]))
File ".../poky/scripts/wic", line 316, in main
return hlp.invoke_subcommand(args, parser, hlp.wic_help_usage, subcommands)
File ".../poky/scripts/lib/wic/help.py", line 95, in invoke_subcommand
subcommands.get(args[0], subcommand_error)[0](args[1:], usage)
File ".../poky/scripts/wic", line 222, in wic_create_subcommand
if not os.path.isdir(rootfs_dir):
File ".../poky/build/tmp/sysroots/x86_64-linux/usr/lib/python2.7/genericpath.py", …
```

Fix core-image-full-cmdline.env error when building fresh Mender image.

---

scripts/mender-qemu

Tiny patch series with fixes to `mender-qemu` scripts. These address 2 problems:
* workig under a OE inited shell
* runnig other images than just `core-image-full-cmdline`
@kacf @GregorioDiStefano

some fixes to mender-qemu wrapper

---

recipes-mender/mender/files/mender.conf
recipes-mender/mender/mender_0.1.bb

A short series of patches for mender recipe.
The first 3 patches introduce cleanups (removing unnecessary quotations, slashes etc.).
The 4th patch ships `mender-device-identity` in mender package.
The last patch introduces a fix to `mender.conf` so that the default config is at least a valid JSON.

cleanup  & device identity work

---

recipes-bsp/u-boot/files/0003-Add-kernel-panic-option-to-vexpress-boot-arguments.patch
recipes-bsp/u-boot/files/uEnv.txt
recipes-bsp/u-boot/u-boot-mender.inc

Having panic option set as a part of boot arguments we will be able
to restart boot process once booting kernel will hang.

Add panic option to bootloader boot arguments.

---

classes/sdimg.bbclass

```
commit 9571036460bd10e054b6b2c3a1ad92d26c6f37b4
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Thu May 26 10:28:48 2016
Add SDIMG_DATA_PART_SIZE_MB variable.
This requires changing how we construct the data partition, since the
--size parameter for the partition doesn't do what you'd expect:
Instead of using it as the size of the partition, it adds it to the
size of the partition. We are pretty used to constructing our own
file systems now, so do that instead.
Also change the names of temporary file system files to be more
consistent.
commit 4d4b7cbdab99e22d5d8b74d216a54e8de4f50fd8
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Thu May 26 09:56:02 2016
Rename SDIMG_PART1_SIZE_MB to SDIMG_BOOT_PART_SIZE_MB. …
```

Sdimg cleanup

---

recipes-mender/mender/mender_0.1.bb

Workaround go install inconsistency when installing host or cross
compiled binaries. Runnin go install, the built packages end up only in
${GOPATH}/bin or ${GOPATH}/bin/${GOOS}_${GOARCH}, the latter case being
true only for cross-compiled (from go's perspective) builds.
Guessing if we're go is cross-compiling is too much overhead, assume
that we're always cross-compiling. This works for the general case, but
will break if target is the same arch as host.

mender: workaround go install

---

classes/sdimg.bbclass
recipes-bsp/u-boot/u-boot-fw-utils_2015.10.bbappend
recipes-core/base-files/base-files/fstab
recipes-core/base-files/base-files_3.%.bbappend

As there is some limitation in older versions of u-boot that
environment utilities (fw_printenv and fe_setenv) can read environment
location consisting of 16 characters at most.
Changing partition name from /u-boot to /uboot will cause that
'/uboot/uboot.env' string will be 16 characters long.

Change the name of boot partition to /uboot.

---

recipes-mender/mender/mender_0.1.bb

Fix access to mender.conf & mender.service local files. The files are
fetched to ${WORKDIR} not ${S}.
Addresses the root cause of #60

mender: fix local file access

---

recipes-bsp/u-boot/files/generic-mender-boot-code.patch

Although not technically necessary, it's more consistent, and some
tests depend on it.

Reintroduce bootcount into U-Boot environment.

---

scripts/mender-qemu

The reasons why this happens sometimes is not clear, but with this
patch it should work either way.

Workaround the fact that the build sometimes ends up in tmp-glibc.

---

classes/mender-systemd.bbclass

It is actually enabled for vexpress-qemu by default, but because of
the way bitbake variables are resolved, it comes too late for the test
to pick it up, so skip the check in that case.

Fix incorrect error for systemd when compiling vexpress-qemu.

---

scripts/mender-qemu

It is unknown why there are sometimes two paths, but tmp/ appears to
be the one with qemu in it.

Reverse priority of tmp and tmp-glibc path in qemu launcher script.

---

Dockerfile
scripts/docker/entrypoint.sh
scripts/mender-qemu

This allows us to run the mender qemu environment inside of Docker.
As soon as I get a hold of the docker hub credentials, I will integrate this with the build machine, and push the latest container to docker hub.
I've added this since it would facilitate running the latest mender qemu image, and we will need this for integration testing. 
I also changed mender-qemu with some default parameters, and use qemu-system-arm from PATH.

Dockerize meta-mender Yocto image

---

recipes-devtools/go/go-cross_%.bbappend
recipes-devtools/go/go-native_%.bbappend

See 5b5171e81439269f6a1ad59f82d32d6b1a23335d in oe-meta-go.
The remaining part should also be fixed upstream soon, at which point
both of these files can be removed.

Remove Go workaround that has been fixed upstream.

---

Dockerfile

The current images are large ~700MB, this should reduce the size of
intermediate snapshots thus trimming the image to something like ~220MB.
@GregorioDiStefano can you try that in your environment?

Dockerfile: reduce docker image size

---

classes/mender-sdimg.bbclass

It has a special syntax using ';'. See the documentation for the
variable for more information.

MEN-529: Fix incorrect handling of IMAGE_BOOT_FILES.

---

recipes-mender/mender/mender_0.1.bb

Poky bitbake setup defaults to B=S what is inconvenient in case of
mender as we need to create a mock GOPATH structure for the sake of
build. Make sure to set B to something remotely reasonable.

mender: set build dir

---

tests/acceptance/conftest.py

We assume that the tests are always executed from the test directory
anyway.

Don't reference WORKSPACE which doesn't exist in local builds.

---

classes/mender-sdimg.bbclass

Use first ext2/3/4 filesystem found in IMAGE_FSTYPES instead.

MEN-546: Fix hardcoded filesystem type in sdimg creation.

---

recipes-mender/mender/files/mender.conf

@bboozzoo I see DeviceID is no longer referenced in the client, I think this was lingering artifact

Removing deprecated DeviceID key

---

recipes-bsp/u-boot/u-boot-fw-utils_%.bbappend
recipes-bsp/u-boot/u-boot-mender.inc

Fixes build with poky master, builds on top of #87. `fw_env.config` will be generated and shipped by `u-boot-fw-utils` only.

build with poky master

---

recipes-mender/mender/mender_0.1.bb

Right now MENER_CERT_LOCATION is empty, so the client will not try to use the trusted certificate when talking to the backend.

mender: provide sane default for MENDER_CERT_LOCATION

---

recipes-mender/mender/files/mender.service
recipes-mender/mender/mender_0.1.bb

Automatic setup of tenant token when starting mender client. The user
should override MENDER_TENANT_TOKEN and set it to value of the token
assigned by the system.

mender: tenant token handling

---

scripts/docker/entrypoint.sh

Since mender-qemu allows for passing parameters to the underlying qemu
process, enable passing command line parameters directly to entrypoint
wrapper.
So it's possible to run like this (to enable a snapshot of sd card image in qemu):
```
docker run mender-client -snapshot
```
@GregorioDiStefano @kacf @pasinskim

docker/entrypoint: allow for taking command line parameters

---

recipes-mender/mender/mender_0.1.bb

Currently we have 1 Jenkins job taking care of 2 different Yocto builds, and for performing testing.
1) We test without the mender service
2) We publish a standalone client
3) We integrate new qemu builds into the docker integration framework, where mender runs as a service
By disabling the mender service by running by default, 1&2 work out of the box, and 3) simply requires adidng the mender.service file to the right places.
Currently, with the mender service enabled, its more work.
@kacf

Don't make mender run as a service by default

---

scripts/mender-qemu

- Random mac address, so we get a random client ID, allowing us to deploy many QEMU clients in docker
- Lower memory from 1G => 512M

Random QEMU mac address, and lower memory allocation

---

recipes-bsp/u-boot/files/0001-Generic-boot-code-for-Mender.patch
recipes-bsp/u-boot/files/0002-Integration-of-Mender-boot-code-into-U-Boot.patch
recipes-bsp/u-boot/u-boot-mender-common.inc

The motivation behind this patch is to separate the pure Mender code,
which is a patch that will never conflict (it only contains new
files), from the integration of that code into U-Boot. Even though the
latter patch is minimal, it may conflict with some U-Boot versions,
since it has to touch some core areas.
If there ever is such a conflict during a user's integration, he may
have to produce his own patch to get around the problem, but that
means he would have to duplicate all the Mender code, which is
unnecessary and also means he won't receive updates to that code
unless he manually ports it.
With the two patches, the payload, which is the Mender code, is
separate, and thus will stay up to date even if the user has made his
own integration patch.
Signed-off-by: Kristian Amlie …

Split generic U-Boot patch into payload and integration pieces.

---

recipes-mender/mender/mender_0.1.bb

Disable inappropriate binary checks for Go binaries.

---

recipes-bsp/u-boot/files/0001-Generic-boot-code-for-Mender.patch

Since bootargs is only used implicitly by various boot commands, and
not explicitly like most "run" commands, it is not expanded when it is
used. This is a problem if for example ${mender_kernel_root} is
hardcoded directly in bootargs, without ever being explicitly set (and
thereby evaluated) by the script.
See also the U-Boot documentation: "Note: You cannot use this method
directly to define for example the "bootargs" environment variable, as
the implicit usage of this variable by the "bootm" command will not
trigger variable expansion - this happens only when using the "setenv"
command." (originally fetched from
http://www.denx.de/wiki/view/DULG/LinuxBootArgs)
We work around this by simply setting bootargs to itself, thereby
forcing reevaluation.
Signed-off-by: Kristian Amlie …

Fix U-Boot bootargs variable not being expanded properly.

---

recipes-mender/mender/mender_0.1.bb

It's not needed in PATH, and it's better to keep Mender's private
data/scripts isolated. This also brings it in line with the upcoming
inventory scripts.

Move identity script to /usr/share/mender/identity.

---

scripts/mender-qemu

This will make using `docker-compose scale` more useful.
Currently, after booting up qemu with the vexpress image, only 12mb of RAM is used.

make qemu vm only allocate 64mb of ram

---

recipes-mender/mender/mender_0.1.bb

Since commit a625568f4564dea0c4bcde009ef4157215e072cd, mender imports
its local modules (github.com/mendersoftware/mender/utils in this case).
For this to work, we need to recreate a complete GOPATH structure,
including github.com/mendersoftware/mender import path, for the build to
work.

mender: recreate full Go import path under GOPATH for build

---

classes/mender-artifactimg.bbclass
classes/mender-image.bbclass

Change artifact image generation to use `.mender` suffix instead of
`.artifactimg`. Leave the class name unchanged to avoid `mender` phrase
popping up too many times.
@kacf @pasinskim @GregorioDiStefano @eysteins

mender-image: drop .artifactimg suffix in favor of .mender

---

classes/mender-sdimg.bbclass

Do not use full path for the source file when symlinking sdimg, as none
of the other 'helper' symlinks do that.
Before:
```
lrwxrwxrwx 2 mborzecki mborzecki        59 10-05 10:52 core-image-minimal-vexpress-qemu.ext4 -> core-image-minimal-vexpress-qemu-20161005085209.rootfs.ext4
lrwxrwxrwx 2 mborzecki mborzecki        63 10-05 10:51 core-image-minimal-vexpress-qemu.manifest -> core-image-minimal-vexpress-qemu-20161005085138.rootfs.manifest
lrwxrwxrwx 2 mborzecki mborzecki        61 10-05 10:52 core-image-minimal-vexpress-qemu.mender -> core-image-minimal-vexpress-qemu-20161005085209.rootfs.mender
lrwxrwxrwx 1 mborzecki mborzecki        61 10-05 10:51 core-image-minimal-vexpress-qemu.qemuboot.conf -> core-image-minimal-vexpress-qemu-20161005085138.qemuboot.conf
lrwxrwxrwx 1 mborzecki …
```

mender-sdimg: do not use full path when symlinking sdimg

---

classes/mender-sdimg.bbclass

The issue is already fixed on master.
This is in relation to:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/meta-yocto-bsp/conf/machine/beaglebone.conf?id=3a73fe0efcb7aeefcca7011bba887caad03d4d03

Add missing kernel and device tree files for Beaglebone on krogoth.

---

tests/acceptance/common.py

Right now this is hardcoded, but more patches will follow to grab this
from bitbake itself.

Add bitbake_path fixture to get the bitbake PATH environment in a test.

---

tests/acceptance/.gitignore
tests/acceptance/common.py
tests/acceptance/test_sdimg.py
tests/acceptance/test_update.py

```
commit e00aa6fab6d93465b8eaf74aabeff912273e5ebc
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Wed Oct 19 12:59:34 2016
Add test for IMAGE_BOOTLOADER_FILE bitbake option.
At the time of writing, this test will in fact be skipped on all
platforms we currently test. But it's a nice test to keep around for
when a platform that uses IMAGE_BOOTLOADER_FILE comes around.
commit 741df67e274afc74dbd20a4ae1922cc00d7ae267
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Wed Oct 19 12:58:26 2016
Add autodetection of correct image to use for tests.
It simply uses the newest image of each type: ext4, sdimg and mender.
```

Test improvements

---

classes/mender-uboot.bbclass

DEPENDS and RDEPENDS need to match when building a custom
u-boot-fw-utils.

Fix (R)DEPENDS mismatch error when building custom u-boot-fw-utils.

---

classes/mender-sdimg.bbclass
tests/acceptance/common.py
tests/acceptance/test_sdimg.py

Passing count=1 to dd would write one additional sector after the
sparse sectors created by using seek. Avoid that by setting to zero.
Also add acceptance test for verifying that image size, partition
sizes and partition alignments are correct in the image.

Fix rootfs always overshooting the alignment by 1MiB.

---

classes/mender-artifactimg.bbclass
tests/acceptance/test_update.py

`-i` option was replaced with `-n`.

Add support for changed artifact command line interface.

---

classes/mender-image-buildinfo.bbclass
classes/mender-install.bbclass
classes/mender-uboot.bbclass
recipes-mender/mender-artifact/mender-artifact.bb
recipes-mender/mender/mender_0.1.bb

The series adds a recipe for mender-artifact package. The package delivers `${sysconfdir}/mender/artifact-info`. The file is populated in rootfs preprocessing.
In order to preserve backwards compatibility with, `${sysconfdir}/mender/build_mender` is a symlink to `artifact-info`.
Setting mender dependencies in `mender-uboot` is not a good idea and bitbake correctly raises a warning when parsing recipes. `RDEPENDS` of mender were moved to mender recipe. `u-boot` was dropped from `[R]DEPENDS`, as it should get built & installed as a result of machine setup. 
`DEPENDS_mender` was removed. AFAIK there's no build dependency on `u-boot` nor on `u-boot-fw-utils`.
@pasinskim @kacf

add recipe for mender-artifact

---

meta-mender-core/recipes-bsp/u-boot/patches/experimental/0001-Generic-bootlimit-patch-without-U-Boot-boot-counter-.patch
meta-mender-qemu/recipes-bsp/u-boot/patches/experimental/0002-Enable-custom-bootlimit-code-for-vexpress-qemu.patch

We implement our own replacement logic in the boot script. This is
only useful if porting Mender to an old U-Boot that doesn't have
bootlimit support.

MEN-562: Add experimental patches for using U-Boot without bootlimit support.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.bb

It's a fully generated package, with no source, so a license is kind
of pointless. Nevertheless, make the build system happy and provide
the Apache-2.0 license.

Fix license warning in mender-artifact.

---

meta-mender-core/classes/mender-sdimg.bbclass

If you tried to build sdimg once, and it failed somewhere in the late
stages, you could never build it again because the symlinks would
already exist. Fix by forcing creation even if they exist already.

Fix persistent symlink error if sdimg building has failed once.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.bb

It's already present in mender-artifactimg.bbclass, which assembles
the .mender file. However, if you only build the initial sdimg, the
check would be skipped, but it's equally important that it is in the
sdimg. So add the check to the mender-artifact.bb recipe, which should
cover both cases.

Add MENDER_ARTIFACT_NAME check to mender-artifact.bb recipe as well.

---

meta-mender-core/recipes-bsp/u-boot/patches/0001-Generic-boot-code-for-Mender.patch

Based on following user feedback:
Tested meta-mender on U-boot 2016.11 and get following:
| Error: You must add new CONFIG options using Kconfig
| The following new ad-hoc CONFIG options were detected:
| CONFIG_MENDER_H
|
| Please add these via Kconfig instead. Find a suitable Kconfig
| file and add a 'config' or 'menuconfig' option.
This is because of [PATCH 1/2] Generic boot code for Mender.
It is probably not the best naming convention to begin a header file
name with CONFIG_ since this is obviously now interpreted as
configuration option and hence the error.

Fix build for U-Boot 2016.11 and later.

---

meta-mender-core/classes/mender-sdimg.bbclass
meta-mender-raspberrypi/README.md
meta-mender-raspberrypi/conf/layer.conf
meta-mender-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi0/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi2/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi3/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bbappend
meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender.io-requirements.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-fw-utils_%.bbappend
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-raspberrypi.inc
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend

This pull request adds support to build mender for Raspberry Pi boards. I have only tested this on a Raspberry Pi 2.
This adds a dependency on (when building for a Raspberry Pi board):
```
URI: git://git.yoctoproject.org/meta-raspberrypi
branch: master
revision: HEAD
```
Following needs to be added to local.conf when building for Raspberry Pi`s:
```
MACHINE ?= "raspberrypi2"
KERNEL_IMAGETYPE = "uImage"
INHERIT += "mender-full"
DISTRO_FEATURES_append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""
IMAGE_FSTYPES = "ext4"
MENDER_ARTIFACT_NAME = "my-mender-image-1.0"
MENDER_PARTITION_ALIGNMENT_MB = "4"
MENDER_BOOT_PART_SIZE_MB = "40"
MACHINE_ESSENTIAL_EXTRA_RDEPENDS_append = " bcm2835-bootfiles" …
```

Add support for Raspberry Pi boards

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender.io-requirements.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-raspberrypi.inc

rpi-common.h has been renamed to rpi.h.
While at it changed mender.io occurrences to mender.

raspberrypi: u-boot: adjust mender patches for 2016.11

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch

Since https://github.com/mendersoftware/meta-
mender/commit/2a8ea346aa0d12da755d36f426164a0e54f757b3, it is expected
that the U-boot environment is on the MMC instead of a file on VFAT
partition.

raspberrypi: u-boot: move U-boot environment to MMC

---

meta-mender-beaglebone/recipes-bsp/u-boot/patches/0001-Disable-feature-which-breaks-internal-MMC-detection.patch
meta-mender-beaglebone/recipes-bsp/u-boot/u-boot_2016.11.bbappend

This problem was introduced in U-Boot in commit 80b24fcd3083515e6b961,
due to the addition of the CONFIG_DM_MMC option.

beaglebone: Disable feature which breaks internal MMC detection.

---

tests/acceptance/test_update.py

tests: Use BusyBox compatible variant of dd, which doesn't support "oflag"

---

meta-mender-core/classes/mender-sdimg.bbclass

`BitbakeVars._parse_line()` may incorrectly interpret lines containing
'<key>=<value>' pattern as those containing legitimate bitbake variables. When
<key> name concides with a known bitbake variable, one may observe unexpected
value returned by `get_bitbake_var(<key>)`.
In meta-mender case, IMAGE_CMD_sdimg defines ROOTFS_SIZE variable. OE-core commit
db08ffee0ad1451f3bf710f4d1b623938ba9aefb introduced a fallback mechanism for
setting partition size that uses ROOTFS_SIZE. Querying ROOTFS_SIZE while
meta-mender is included in layers leads to unexpected results.
@kacf @pasinskim

mender-sdimg: workaround get_bitbake_var() parsing issues

---

meta-mender-core/classes/mender-sdimg.bbclass

This is much more predictable than --size, and will produce an error
if the size can't be honored.

sdimg: Start using wic's --fixed-size option.

---

meta-mender-qemu/Dockerfile
meta-mender-qemu/scripts/docker/entrypoint.sh

This is primarily for development, where instead of creating a new
docker image every time you've built a new Yocto image, you grab them
from /mnt/build mount point instead. The image won't work unless you
specify either the arguments or the mount, but this was the case
before this patch as well.

Default to empty images in docker build.

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-install.bbclass
meta-mender-core/classes/mender-sdimg.bbclass
meta-mender-core/classes/mender-uboot.bbclass
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
tests/acceptance/test_mender-artifact.py

This is "payload" of the PR:
```
MEN-934: Always respect storage conf when determining rootfs size.
Previously it was only being respected when building the sdimg. We
want it to be respected also when building mender updates.
For this we auto-set the standard IMAGE_ROOTFS_SIZE Yocto variable,
however it's still possible to override it by the user.
```
The rest of the commits are simply enablers for this to work.

MEN-934: Always respect storage conf when determining rootfs size.

---

meta-mender-demo/recipes-core/netbase/netbase_%.bbappend

This will add an option so that the user can specify the Mender server
address during build time.
e.g. in local.conf:
MENDER_DEMO_SERVER_ADDRESS = "192.168.0.100"
This is usually a manual step that the user has to perform each time a
new image is built.

demo: netbase: add option to specify address of Mender server

---

meta-mender-core/classes/mender-install.bbclass
meta-mender-core/conf/layer.conf

```
commit a3d1d47aa73d0fd9fe31b5deca5b6d0e3ae8ede8
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Thu Jan 26 12:40:16 2017
MEN-927: Lock mender to Go version 1.7.
Not locking to the current 1.7.4, because the upstream Go layer does
not keep old patch versions around, and getting latest patch version
anyway seems like a good idea.
commit c9b4e966920246698e2da04b0f07a6df6c5d4470
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Thu Jan 26 12:27:53 2017
Add layer dependency to go layer.
```

MEN-927: Lock mender to Go version 1.7.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.bb

We also need to transfer the .git directory to the build folder
because the Makefile needs it to figure out the version.
Fixes MEN-897.

m-artifact: Support automatic version by using Makefile.

---

meta-mender-qemu/recipes-bsp/u-boot/patches/0001-Enable-U-Boot-on-QEMU-to-use-Mender-boot-code.patch
meta-mender-qemu/scripts/mender-qemu

The memory apparently starts counting from 0x60000000. By having our
kernel and dtb files load to an address closer to that address, we can
reduce the memory needed to boot. The problem with the previous
address was that it was pointing outside of the address space if the
available memory was reduced.
Consequently, reduce the QEMU memory to 64MiB.

qemu: Rearrange memory layout to allow lower memory footprint.

---

meta-mender-core/recipes-mender/mender/mender_0.1.bb

Remove INHIBIT_PACKAGE_STRIP, since upstream patch was merged.

---

meta-mender-core/classes/mender-sdimg.bbclass
meta-mender-demo/conf/layer.conf

Generally it's all that's needed, and this will reduce testing times
considerably because there will be much less writing.
At the time of writing, the rootfs fills about 94MiB, so if you double
that for the dual rootfs and add 100MiB+ for the other partitions,
400MiB seems like a sane default.

Reduce demo sdimg size to 400MiB.

---

meta-mender-core/classes/mender-sdimg.bbclass

Use kilobytes directly, since it is the unit of
MENDER_CALC_ROOTFS_SIZE.

Clean up rootfs size usage in mender-sdimg.bbclass.

---

meta-mender-core/classes/mender-install.bbclass
tests/acceptance/test_build.py

For example core-image-minimal will add space to this unconditionally
if systemd is enabled.

Include .._EXTRA_SPACE in image size calculations.

---

meta-mender-core/classes/mender-install.bbclass
meta-mender-core/conf/layer.conf
tests/acceptance/common.py

Also remove dependence on specific version, we now follow the latest
one in Yocto instead.

Remove go layer depends, since Yocto ships with Go support now.

---

meta-mender-core/classes/mender-artifactimg.bbclass

Also remove IMAGE_ROOTFS_EXTRA_SPACE reference, since we handle that
automatically now, and instead suggest changing
MENDER_STORAGE_TOTAL_SIZE_MB.

Turn too-big-update warning into error.

---

meta-mender-qemu/Dockerfile

This shaves off ~200MB from the image size:
```
sh-4.3$ docker images |grep mender- 
mender-alpine-bash       latest              44aec2f4dab6        3 minutes ago       438.7 MB
mender-ubuntu-arm-bash   latest              1a0ae211dbc9        6 minutes ago       656.2 MB
```
@kacf @GregorioDiStefano

meta-mender-qemu: use alpine:3.4 as base for dockerized client VM

---

tests/acceptance/test_mender-artifact.py
tests/acceptance/test_update.py

This is important so that version 1 can not be used as a backdoor
circumventing the signature verification.

Add tests for unsigned image of version 1.

---

meta-mender-demo/recipes-core/volatile-binds/volatile-binds.bbappend

It was caused by commit fcd48092d7bca, and this just partially
restores the old behavior.

Work around DNS not working in upstream poky pyro and master.

---

tests/acceptance/common.py

Fixes a test breakage on Beaglebone, where this variable is only
defined in the environment.

tests: Make sure we look in the environment for MACHINE variable.

---

meta-mender-core/classes/mender-sdimg.bbclass

Changelog: Fix MENDER_DATA_PART_DIR sometimes copying some files
multiple times.
Based on a patch by David Silver <dsilver@upthere.com>

use rsync to copy data dir contents

---

meta-mender-qemu/Dockerfile
meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
meta-mender-qemu/scripts/mender-qemu

* SERVER_URL environment variable can be passed in while launching
* tenant.conf and server.crt can be passed in by mounting a volume
containing those files on /mnt/config.
More info in the Dockerfile for QEMU.
MEN-1207

QEMU: Add ability to configure certain client values before launching

---

meta-mender-core/classes/mender-sdimg.bbclass

Changelog: Fix a bug which caused sdimg generation to bypass the
sstate mechanism. This could lead to broken builds in some corner
cases, and it also means that sdimg images would never be cleaned up.

Fix sdimg being generated outside of sstate mechanism.

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-state-scripts.bbclass
meta-mender-demo/recipes-mender/example-state-scripts/example-state-scripts_1.0.bb
meta-mender-demo/recipes-mender/example-state-scripts/files/LICENSE
meta-mender-demo/recipes-mender/example-state-scripts/files/example-script
tests/acceptance/test_build.py

The new mender-state-scripts class can be used in a recipe to turn
that recipe into a state script recipe. Any script or binary that the
recipe provides using the class will become part of the Mender update
as a state script.
There are several ways to include them:
* Put the script/binary in ${MENDER_STATE_SCRIPTS_DIR} during the
do_compile stage.
* Put an archive in SRC_URI that extracts to
${PN}-${PV}/mender-state-scripts, where ${PN}-${PV} are the recipe
name and version.
* Set the variable MENDER_STATE_SCRIPTS manually to a directory that
contains the scripts.
Note that the three methods should not be mixed.

MEN-1014: Add mender-state-scripts class and example.

---

meta-mender-core/recipes-bsp/u-boot/patches/0001-Generic-boot-code-for-Mender.patch
meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender.inc
meta-mender-qemu/Dockerfile
meta-mender-qemu/classes/vexpress-nor_image.bbclass
meta-mender-qemu/conf/machine/include/vexpress.inc
meta-mender-qemu/conf/machine/vexpress-qemu-flash.conf
meta-mender-qemu/conf/machine/vexpress-qemu.conf
meta-mender-qemu/recipes-bsp/u-boot/files/vexpress-qemu-flash/fw_env.config.default
meta-mender-qemu/recipes-bsp/u-boot/patches/0001-vexpress_ca9x4-enable-booting-from-ubifs.patch
meta-mender-qemu/recipes-bsp/u-boot/patches/0005-vexpress_ca9x4-Mender-with-UBIFS-integration.patch
meta-mender-qemu/recipes-bsp/u-boot/u-boot-fw-utils_%.bbappend
meta-mender-qemu/recipes-bsp/u-boot/u-boot-vexpress-qemu.inc
meta-mender-qemu/recipes-kernel/linux/linux-yocto_%.bbappend
meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
meta-mender-qemu/scripts/mender-qemu

This PR adds support for raw flash to qemu. You need to use qemu master (or 2.9) to be able to use generated image.
Short summary:
There's a separate machine config `vexpress-qemu-flash`, as its setup is significantly different. The machine config already defines some MENDER variables (see vexpress-qemu-flash.conf) as we know the size of the storage upfront.
There's a number of u-boot patches that are queued up right here for now: https://github.com/bboozzoo/u-boot/commits/bboozzoo/vexpress-a9-ubi-mender (they will be added once I verify that things are working). The 
`vexpress_ca9x4: enable booting from ubifs` does some significant changes to uboot config and flash layout, these are:
* enable UBI, UBIFS, MTD on CFI, MTD concatenation (so our sepate 64MB banks (`nor0`, `nor1`) will appear …

qemu raw flash

---

meta-mender-qemu/scripts/docker/entrypoint.sh

@GregorioDiStefano @kacf 
Need to build and push this image as all integration tests will currently be failing without this fix.

meta-mender-qemu/entrypont: fix running with reconfigured images

---

meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi0/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi2/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi3/boot.cmd
meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

Currently we completly ignore what boot firmware feels that we
should use as bootargs and we define our own. By doing so we
lose some functionality. This patch attempts to improve this.
The bootargs looks like this now:
8250.nr_uarts=0 bcm2708_fb.fbwidth=1184 bcm2708_fb.fbheight=624 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000 dwc_otg.lpm_enable=0 console=ttyS0,115200 rootfstype=ext4
rootwait root=/dev/mmcblk0p3
Signed-off-by: Mirza Krak <mirza.krak@endian.se>

raspberrypi: use bootargs passed on by boot firmware

---

meta-mender-core/classes/mender-install.bbclass

Changelog: Change MENDER_DEVICE_TYPES_COMPATIBLE to follow value of
MENDER_DEVICE_TYPE by default. This triggers the correct behavior when
MENDER_DEVICE_TYPE has been redefined.

Change compatible device types to follow device type of build.

---

meta-mender-qemu/recipes-connectivity/openssh/openssh_%.bbappend
meta-mender-qemu/scripts/mender-qemu
tests/acceptance/common.py

```
commit e6952b8ae150052b1d4ae960de2f2999c55b565d
Author: Maciej Borzecki <maciej.borzecki@rndity.com>
Date:   Thu Jun 29 08:17:52 2017 +0200
tests: support QEMU_DRIVE, refactor qemu handling
Add support for setting up QEMU_DRIVE. Use a temporary file to store the image.
Cleanning this up required refactoring to the actual handling of qemu
startup/teardown.
Also fixes a problem when the tests went on a rampage and killed all instances
of qemu-system-arm.
Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>
commit 207a7b506a71401b9e4a2d635cf50b0242770302
Author: Maciej Borzecki <maciej.borzecki@rndity.com>
Date:   Thu Jun 29 08:04:37 2017 +0200
meta-mender-qemu/mender-qemu: exec qemu
This should allow a reasonable cleanup when killing the helper script. Also,
qemu …
```

integration fixes

---

meta-mender-core/classes/mender-install.bbclass
meta-mender-qemu/Dockerfile
meta-mender-qemu/conf/machine/vexpress-qemu-flash.conf
meta-mender-qemu/recipes-core/systemd/files/01-logs-to-console.conf
meta-mender-qemu/recipes-core/systemd/systemd_%.bbappend
meta-mender-qemu/scripts/mender-qemu
tests/acceptance/common.py
tests/acceptance/conftest.py
tests/acceptance/requirements.txt
tests/acceptance/test_build.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_rootfs.py
tests/acceptance/test_sdimg.py
tests/acceptance/test_ubimg.py
tests/acceptance/test_update.py

Currently contains also what's already up for review in #323 will rebase when that one is merged.
Work in progress, I'm testing with both `vexpress-qemu` and `vexpress-qemu-flash`. You will need a modification to mednersoftware/mender-qa scripts in order to build for `vexpress-qemu-flash` as the tests don't set `MACHINE` on their own.
Most of `test_build` tests are skipped, because they rely heavily on ext* images. All of mender-artifact tests are all usable. `test_rootfs` contains a separate tests for `ubimg` and `sdimg`. All of `test_sdimg` are skipped for non-sdimg images. `test_update` was not updated yet.

qemu raw flash acceptance tests

---

meta-mender-core/recipes-mender/mender/mender.inc
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
tests/acceptance/test_build.py

Also adds a simple test for testing the tenant-token new variable.

MEN-1071: Adds a tenant-token variable for use with custom tokens.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/mender_git.bb

It should behave like this:
* If PREFERRED_VERSION is unset or a bare version tag, set version to
"master-git<SHA>" to prevent the recipe from being selected.
* If PREFERRED_VERSION has a tag with "-build" in it, set version to
that version, in order to be able to use the Git recipe for building
temporary tags without needing to create a recipe for each one.
* If PREFFERED_VERSION contains "-git", set the version to that
string, minus any "%" suffix and plus <SHA>. This will build a
binary with a temporary version string.

Rewrite git recipes to be smarter when selecting versions.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/mender_git.bb

It should behave like this:
* If PREFERRED_VERSION is unset or a bare version tag, set version to
"master-git<SHA>" to prevent the recipe from being selected.
* If PREFERRED_VERSION has a tag with "-build" in it, set version to
that version, in order to be able to use the Git recipe for building
temporary tags without needing to create a recipe for each one.
* If PREFFERED_VERSION contains "-git", set the version to that
string, minus any "%" suffix and plus <SHA>. This will build a
binary with a temporary version string.
(cherry picked from commit 2d7ffec95a59a3168345fb5305632afe620c4e9d)

[pyro] Rewrite git recipes to be smarter when selecting versions.

---

tests/acceptance/common.py
tests/acceptance/conftest.py
tests/acceptance/test_build.py
tests/acceptance/test_commits.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_rootfs.py
tests/acceptance/test_sdimg.py
tests/acceptance/test_ubimg.py
tests/acceptance/test_update.py

This is in order to support multiple versions of Mender with the
acceptance tests, since they live in a repository which is versioned
after poky, not Mender.

tests: Add mandatory minimum Mender version mark to all tests.

---

meta-mender-raspberrypi/README.md
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi0/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi2/boot.cmd
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/raspberrypi3/boot.cmd

On the Raspberry Pi platform, the DTB is generate by the start.elf firmware
and we should defer to that rather than loading the "standard" DTB file.
This is fixed in the meta-raspberrypi layer here:
https://www.mail-archive.com/yocto@yoctoproject.org/msg32465.html
Additional links with details:
https://www.raspberrypi.org/forums//viewtopic.php?f=107&t=134018
http://dius.com.au/2015/08/19/raspberry-pi-uboot/

rpi: Fix DTB handling for Mender-based Raspberry Pi boards.

---

meta-mender-core/classes/mender-sdimg.bbclass

Since we are using rawcopy/fsimage in the wks entry for the data
partition, wic makes no attempt to set it, so we need to set it when
creating the filesystem.

Make sure filesystem label is set for data partition. 

---

meta-mender-raspberrypi/README.md

Changes done in 264cf2ee4c12e072a1343e0102dfc70a35ee93c5 make this line obsolete.

raspberrypi: remove legacy documentation from README

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-setup-ubi.inc
meta-mender-core/classes/mender-setup-uboot.inc
meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-qemu/conf/machine/vexpress-qemu.conf

This is the first step in booting via UEFI. This just creates an image
using the GPT partition table format, which UEFI requires. There are
some shortcomings in this implementation, which will be resolved in
upcoming tasks:
* The boot partition source in the wks file should be changed to
'bootimg-efi'. However, this can't be done until we have a valid
bootloader available like grub. Hence the EFI partition is not valid
at the moment.
* Right now you have to set IMAGE_BOOT_FILES to a dummy file in order
for wic not to complain. This will also go away once we get a real
EFI bootloader in place.
We also tweak some variable assignments after it was revealed that
removing mender-uboot from DISTRO_FEATURES caused some problems.
Signed-off-by: Kristian Amlie …

MEN-1431: Make UEFI image generator: uefiimg.

---

meta-mender-core/classes/mender-setup-install.inc

This partially reverts variable assignment depending on distro
features.
What we want is for the assignment to happen if, and only if:
* mender-install feature is enabled
* there is no previous assignment
However it seems impossible to do this correctly, because:
* If we use an override, then even a weak default assignment overrides
any other hard assignment.
* If we use inline Python to detect the distro feature, then the code
executes at the end instead of where it occurs, which means our
assignment is overridden by earlier defaults.
* It is not possible in the Python code to tell whether the currently
set value is a default or not.
* Using a Python function in the assignment itself, we can execute at
the right moment, but we get an infinite recursion if we try to
access the already set …

Fix custom set IMAGE_ROOTFS_SIZE not being respected.

---

tests/acceptance/test_commits.py

By putting the error in the pytest.fail() call, it shows up in the
test result itself, instead of just buried in a log.

Improve failure message when changelog or signoff is missing. 

---

meta-mender-core/recipes-mender/mender/mender.inc

It's not required by the client if the server certificate is properly
signed.

Support building without a server.crt client certificate.

---

meta-mender-demo/recipes-core/systemd/systemd_%.bbappend

systemd: Set default epoch to 0 to avoid fsck at first boot.

---

meta-mender-core/recipes-core/systemd/systemd_%.bbappend
meta-mender-demo/recipes-core/systemd/systemd_%.bbappend

systemd: Move epoch settings back into meta-mender-core.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/mender_git.bb
tests/acceptance/common.py
tests/acceptance/test_build.py

```
commit e2e69ebaf8c7dd5ebeae24a913c0faa1d25d180a
Date:   Thu Oct 12 13:55:01 2017
Fix parse error in MENDER_CERT_LOCATION when PREFERRED_VERSION is unset.
Also add a long desired test, which tests all common combinations of
PREFERRED_VERSIONs. This tests that we can build all tagged versions
of Mender, something that isn't normally checked in Jenkins, because
it builds using PREFERRED_VERSION and a SHA. It also checks that
different types of PREFERRED_VERSION, including with and without
"pn-", and including being missing altogether, builds successfully.
commit 92aa055d76bca814c7d8ff7e799eea1924576b24 …
```

Fix parse error in MENDER_CERT_LOCATION when PREFERRED_VERSION is unset.

---

meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in

Commit e9bb7f0c6d3f77312970034ca0a63b3df0e3ba8e in meta-raspberrypi changed
the processing of this file so we need to adjust.

rpi-u-boot-scr: Switch to boot.cmd.in style recipe.

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch

mender_boot_part_name was never updated once it had been written from
the default environment.
Which led to that we never updated the Linux kernel and dtb on
a NAND/UBI setup, becuase we would always load the Linux kernel from
ROOTFS_A regardless of current active part.
While at it also removed the "persistant" storage of mender_boot_part_name
and the reason for this is that the persistant value would not match the
actual value used to boot the device since we alter it in "mender_setup"
which does not re-save the environment.
Reported-by: Dan Walkes <danwalkes@trellis-logic.com>
Signed-off-by: Mirza Krak <mirza.krak@endian.se>

u-boot: update mender_boot_part_name when mender_boot_part changes

---

meta-mender-qemu/recipes-bsp/u-boot/patches/0001-vexpress_ca9x4-enable-booting-from-ubifs.patch

They are enabled implicitly by enabling PARTITIONS.

Remove vexpress Kconfig options that aren't really options.

---

tests/acceptance/test_update.py

This originally came out of the discussion at:
https://github.com/mendersoftware/meta-mender/pull/403#issuecomment-339889998

tests: Make sure kernel is loaded from correct partition. 

---

meta-mender-core/classes/mender-part-images.bbclass

For some reason if we let rsync set the owner and group information
first, it becomes impossible to set them to something else later on.
The exact cause is unknown, but it may be that rsync uses fchown(),
while we use chown(), and that this triggers the bug. In any case,
avoiding setting the owner and group with rsync seems to fix the
problem.

Work around bug in libpseudo regarding file owners on data partition.

---

tests/meta-mender-raspberrypi3-ci/conf/layer.conf
tests/meta-mender-raspberrypi3-ci/recipes-bsp/rpi-u-boot-scr/files/boot-for-flashing.cmd
tests/meta-mender-raspberrypi3-ci/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bbappend
tests/meta-mender-raspberrypi3-ci/recipes-mender/mender-qa/files/rpi/activate-test-image

Previously we were booting the Mender kernel, even when we were
heading for the Raspbian OS to do a Mender sdimg flash. With this
commit we create a separate boot.scr file that can be used to boot the
kernel directly from Raspbian, avoiding any problems that might occur
because some Mender test has corrupted the Mender kernel.

Improve resiliency of RPi3 image flashing by booting Raspbian kernel.

---

meta-mender-raspberrypi/conf/layer.conf

Currently meta-raspberrypi has BBFILE_PRIORITY set to 9, which means that our layer will be processed before the layer we append. 
This is not intended and we should have higher priority as there might be changes in meta-raspberrypi that need to be applied before we can apply ours. 

meta-mender-raspberrypi: increase layer priority to 10

---

tests/acceptance/test_update.py

After 6a420b51ef80ef, the update became much bigger, so the flipped
byte will always be outside the range of the content string we test
for, since it is in the middle of the file. So we no longer need to
update the content, and in fact doing so would print the entire thing
in the log.

tests: Prevent printing of entire 8MB update.

---

meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc

Raspberry Pi kernel recipes use the KERNEL_DEVICETREE
variable to specify the dtbo overlays to build, not just
the board dtbs.
Ignore these dtbo overlays when assigning MENDER_DTB_NAME.
The existing behavior of choosing the last dtb in the list
if more then one is found is maintained.
Not sure this is a particularly good idea. It might be better
to abort if multiple dtbs are found since using the wrong
dtb for uboot will probably not work.
Signed-off-by: Scott Ellis <scott@jumpnowtek.com>
Modified-by: Kristian Amlie <kristian.amlie@northern.tech>
* Add quotes around variable assignment
* Switch to sed extended regexes and '\s+'
* Remove now unneeded "grep -o"
* Remove redundant 'sed' expressions
* Add changelog

meta-mender-core: Allow dtbos in KERNEL_DEVICETREE

---

tests/acceptance/common.py
tests/acceptance/conftest.py
tests/acceptance/fixtures.py

If common.py is repeatedly imported from several tests, this causes
pytest to create a separate session fixture each time it is imported,
even though there should be only one. This reduces performance
significantly because for instance the test build directory needs to
be reinitialized several times. It can also be dangerous because it is
not expected that session fixtures should have more than one instance.
Fix it by moving the fixtures into their own file and importing it
only from conftest.py. The remaining functions are left in common.py,
since many of them need to be imported to be used as function calls
from the various tests.

tests: Move fixtures into own file to avoid multiple session fixtures. 

---

meta-mender-core/recipes-mender/mender-wait-for-timesync/mender-wait-for-timesync_1.0.bb

mender: Allow empty in mender-wait-for-timesync.

---

meta-mender-qemu/scripts/mender-qemu

qemu does not have enough memory to allocate for upgrade process.
Logs when trying to upgrade qemu image rootfs:
root@vexpress-qemu:~# mender --rootfs https://d1b0l86ne08fsf.cloudfront.net/1.3.0/vexpress-qemu/vexpress_release_2_1.3.0.mender
--- snip ---
ERRO[0158] Could not execute fw_setenv:  fork/exec /sbin/fw_setenv: cannot allocate memory  module=bootenv
ERRO[0158] Enabling updated partition failed: fork/exec /sbin/fw_setenv: cannot allocate memory  module=rootfs
ERRO[0158] fork/exec /sbin/fw_setenv: cannot allocate memory  module=main
--- snip ---
Signed-off-by: Chang Rebecca Swee Fun <rebecca.swee.fun.chang@intel.com>

mender-qemu: increase qemu memory size to 256MiB.

---

meta-mender-core/recipes-mender/mender/files/mender.service

It was originally meant to hold the tenant token, but we have moved
away from that and it is now in the config file.

Drop creation of `authtentoken` file, which is unneeded now. 

---

meta-mender-core/classes/mender-part-images.bbclass

The image_types.bbclass defines a set of conversion types that can be
applied to images (gz, xz, bz2 and more).
With the current state it is not possible to apply an conversion type
on the sdimg using:
IMAGE_FSTYPES += "sdimg.gz"
Because the conversion types assume that that the image is named in the
following format:
${IMAGE_NAME}${IMAGE_NAME_SUFFIX}.${type}
IMAGE_NAME_SUFFIX defaults to ".rootfs" which breaks things for us. By
setting IMAGE_NAME_SUFFIX to an empty string the expected image name
format is correct and the sdimg type can support all the conversiontypes
that are present in image_types.bbclass.
Above is really helpfull to compress the "sdimg" file as it mostly consist
of zero's and by compressing it is much easier to handle, transfer between
devices or between servers.
Note …

fix support of CONVERSIONTYPES for sdimg

---

meta-mender-qemu/conf/machine/vexpress-qemu-flash.conf
meta-mender-raspberrypi/README.md
tests/build-conf/beaglebone-yocto/local.conf
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf

Since we now explicitly use ARTIFACTIMG_FSTYPE instead of scanning
IMAGE_FSTYPES (and have sensible defaults) it should no longer be
necessary to explicitly set these.

mender: Cleanup IMAGE_FSTYPES.

---

meta-mender-qemu/scripts/docker/entrypoint.sh

Changelog: Fix occasional inode corruption issue when re-launching a
previously launched and saved QEMU image.
(cherry picked from commit 131708bb84e20dfe891a1a7fcd367bcd6888631f)

QEMU: Limit client setup steps to run on first boot only.

---

meta-mender-core/classes/mender-setup-image.inc

If the IMAGE_FSTYPES contains redundancies recipes will be run several times.

Fix build error if `IMAGE_FSTYPES` contains the same entry more than once

---

meta-mender-qemu/recipes-kernel/linux/linux-yocto/reduce-memory-to-256m.patch
meta-mender-qemu/recipes-kernel/linux/linux-yocto_%.bbappend

Our emulator script uses 256M, so the device tree file should mirror
that.
Changelog: Fix Linux kernel hanging when loaded via U-Boot/UEFI/GRUB
on vexpress-qemu*.

MEN-1657: Fix incorrect memory size in vexpress-qemu devicetree file.

---

meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Some platforms use "_append" to set the UBOOT_MACHINE resulting
in a leading space in the variable value.  We need to strip this
out so that it is passed in properly as a command line parameter
to uboot_auto_configure.sh.
(cherry picked from commit b8aa8dcf58c1d1a1ab255b00b44cff1959b35009)

meta-mender-core: Clean spaces out of UBOOT_MACHINE.

---

meta-mender-raspberrypi-demo/classes/rpi-demo-wifi.bbclass

There is no package called  'linux-firmware-raspbian-bcm43430' 
Reference: https://groups.google.com/a/lists.mender.io/forum/#!topic/mender/L7LSR3_719I

Fix ERROR: Nothing RPROVIDES 'linux-firmware-raspbian-bcm43430'

---

meta-mender-demo/recipes-core/images/core-image-full-cmdline.bbappend

It is not supported to handle multiple directories and
appending could hint that it would.
[MEN-1980] - MENDER_DATA_PART_DIR does not work as expected
(cherry picked from commit 2c8c11a07453d6c4b954a15d46c1084285c4418e)

meta-mender-demo: remove append from MENDER_DATA_PART_DIR

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch
tests/acceptance/test_update.py

The way it works is that we store the 'mender_check_saveenv_canary=1'
variable in the default U-Boot environment. We do not store the
corresponding 'mender_saveenv_canary=1' value in the default
environment, but instead we write this during the boot process. When
the Mender client finds the former variable, it will look for the
second value as well, and produce an error if it is not present. If
this happens it is an indication that the U-Boot boot loader and the
user space tools do not agree on the location of the environment. It
will also catch cases where mender_setup is not run.

Add canary value to U-Boot env to catch bootloader/user-space mismatch.

---

meta-mender-core/recipes-bsp/grub/files/06_bootargs_grub.cfg
meta-mender-core/recipes-bsp/grub/files/90_mender_boot_grub.cfg
meta-mender-core/recipes-bsp/grub/grub-mender-grubenv_1.0.bb

This allows it to be overridden or modified by adding a script snippet
which sets the variable.
Also log kernel messages to both screen and serial port by default,
and have systemd log to serial port (last "console" argument,
apparently it cannot log to both).

GRUB: Pass kernel arguments from bootargs variable instead of hardcoded.

---

meta-mender-core/classes/mender-helpers.bbclass
meta-mender-core/classes/mender-setup.bbclass
meta-mender-qemu/conf/layer.conf

It appears that `/dev/hda` is rather uncommon, and quite specific to
QEMU since its IDE driver (which corresponds to `/dev/hda`) is
obsolete in modern hardware, and hence should only be used for
testing.
This is building on #576, only the top commit is new.

Change default storage on x86 to memory card (mmcblk0).

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-setup.bbclass
meta-mender-qemu/conf/layer.conf
tests/acceptance/test_update.py

Changelog: Switch image names from containing `MACHINE` to containing
`MENDER_DEVICE_TYPE`. So for example, if you have a build for the
raspberrypi3 machine type, with device type of "prod_rpi3", the image
will now be called `core-image-minimal-prod_rpi3.sdimg` instead of
`core-image-minimal-raspberrypi3.sdimg`.
The main reason for doing this change is that MACHINE is not enough to
separate images from each other when multiple boot loader
configurations are involved. For example vexpress-qemu can be booted
both with U-Boot and with GRUB, and these images are not compatible
with each other. To make sure that images have distinct names, this
change is necessary.

Switch image names from containing MACHINE to containing DEVICE_TYPE.

---

meta-mender-core/recipes-bsp/grub/grub-mender-grubenv_1.0.bb

MEN-2048: Fix `MENDER_GRUB_STORAGE_DEVICE` variable not being respected.

---

meta-mender-core/classes/mender-setup.bbclass

This avoids unnecessary rebuilds when adding or removing the meta-mender-core
layer.

mender: Add MENDER_MACHINE to BB_HASHBASE_WHITELIST.

---

meta-mender-core/classes/mender-setup-image.inc

It is incorrect to use both types of append syntax and also to add
spaces between functions and semi-colons, this is confusing and causes
unexpected behaviour.
First, the += adds the string defined to the
ROOTFS_POSTPROCESS_COMMAND_append variable, with an extra space at the
start. Then, the _append syntax adds this new string to the
ROOTFS_POSTPROCESS_COMMAND variable, after all previous += operations.
It is only necessary to add one space at the beginning of an _append
operation, or no spaces for a += operation.
Also, by adding a space between `mender_update_fstab_file` and `;` (for
example) we make it impossible to remove `mender_update_fstab_file ;`
from the ROOTFS_POSTPROCESS_COMMAND list. The following describes each
_remove syntax and its associated error:
* …

mender-setup-image.inc: Fix recipe append syntax

---

meta-mender-core/classes/mender-setup-image.inc
meta-mender-core/classes/mender-setup-ubi.inc
meta-mender-toradex-nxp/recipes-bsp/u-boot/patches/0005-fw_env_main.c-Fix-incorrect-size-for-malloc-ed-strin.patch
meta-mender-toradex-nxp/recipes-bsp/u-boot/patches/u-boot_v2016.11-backport-of-34255b92e6e68941ab1134299faa86acc5a1abc8.patch
meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex_2016.11.bbappend
tests/acceptance/test_build.py

I think this should be the last fixes. After this, I only have device specific settings left in my `local.conf`:
* `MENDER_MTDIDS = "nand0=gpmi-nand"`
* `MENDER_MTDPARTS = "gpmi-nand:512k(mx7-bcb),1536k(u-boot1)ro,1536k(u-boot2)ro,512k(u-boot-env),-(ubi)"`
* `MENDER_STORAGE_PEB_SIZE = "131072"`
* `MENDER_STORAGE_TOTAL_SIZE_MB = "512"`
I am not sure how strongly these are tied to the `colibri-imx7` machine type, especially the last one. We could potentially put these also into the `machine.conf`, but is it appropriate, or should the user set them?
No other changes are required to build for `colibri-imx7`.
See individual commits for details.

More fixes after colibri imx7 testing

---

meta-mender-core/classes/mender-setup-grub.inc

FIX: Renamed boot.efi to bootia32.efi in mender-setup-grub.inc

---

.gitmodules
tests/acceptance/conftest.py

This is attempting to deal with the fact that image tests now live in
a separate repository. The existing method where we copy over the
tests from that repository is very fragile, and doesn't allow
specifying alternate branches, which will be important as newer
versions of mender-image-tests drift out of sync with older branches
of meta-mender. We will then need to branch mender-image-tests and
switch the submodule over to that.
One slight complication with our use of this submodule is that we want
to track branches, not explicit commits. We solve this by having an
automatic pull before testing starts, which can be disabled if you're
debugging something locally, or in the Jenkins case where we will
check out the exact commit that was specified in the build.
The "repo" tool was considered …

tests: Add mender-image-tests as a submodule.

---

meta-mender-core/classes/mender-artifactimg.bbclass

Replace IMAGE_NAME with IMAGE_LINK_NAME because otherwise
in certain cases IMAGE_NAME might point to non-existent file
and as an end result do_image_mender fails.
Reported-by: Stoyan Bogdanov <stoyan.bogdanov@konsulko.com>
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

mender-artifactimg.bbclass: Ensure image exists

---

meta-mender-qemu/scripts/mender-qemu

(cherry picked from commit 8bb9c4bb1ddde7e2b00216b490854ade23393a42)

[rocko] QEMU: Always try to run with KVM enabled, only fall back to emulation.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.3.0.bb
meta-mender-core/recipes-mender/mender/mender_1.5.1.bb
meta-mender-core/recipes-mender/mender/mender_1.6.0.bb
tests/acceptance/fixtures.py

This is necessary for pyro and earlier.

mender: Adapt LIC_FILES_CHKSUM definitions to older golang support.

---

tests/build-conf/raspberrypi3/bblayers.conf

Changelog: Fix missing wpa_supplicant in Raspberry Pi demo images.

Add raspberrypi-demo layer to build.

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch

Even though there does not seem to be any problems applying the
current patch it does produce a warning:
WARNING: u-boot-1_2018.01-r0 do_patch:
Some of the context lines in patches were ignored. This can lead to
incorrectly applied patches.
The context lines in the patches can be updated with devtool:
devtool modify <recipe>
devtool finish --force-patch-refresh <recipe> <layer_path>
Then the updated patches and the source tree (in devtool's workspace)
should be reviewed to make sure the patches apply in the correct place
and don't introduce duplicate lines (which can, and does happen
when some of the context is ignored). Further information:
http://lists.openembedded.org/pipermail/openembedded-core/2018-March/148675.html
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10450
Details: …

rpi: update U-boot patch to get rid of warning

---

meta-mender-core/recipes-bsp/grub/files/cfg
meta-mender-core/recipes-bsp/grub/grub-efi_%.bbappend

When GRUB is launched it tries to search configuration files in directory ((hd0,gpt1)/EFI/BOOT)/EFI/BOOT/grub.cfg . This directory does not exist. Search command was was setup  redundantly by yocto grub layer. Searching cfg file is not needed, because prefix path already points to the path where the proper grub.cfg exists. Replacing improper yocto cfg file by the correct one causes that there is no strange error message during booting.
Signed-off-by: Dominik Adamski <adamski.dominik@gmail.com>

Remove error message during GRUB booting.

---

meta-mender-core/classes/mender-setup-image.inc

In thud the entire boot directory is excluded because the variable does not end in a /.
This causes mounts to fail.
Signed-off-by: Michael Davis <michael.davis@essvote.com>

Fix boot directory being excluded from thud images

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/recipes-devtools/e2fsprogs/e2fsprogs_1.44.%.bbappend
meta-mender-core/recipes-devtools/e2fsprogs/patches/0001-Do-not-use-metadata_csum-feature-on-ext4-by-default.patch

```
commit c45085187ec79dc2a2dcbb2a2566fe509f0194f0
Date:   Fri Nov 30 10:20:18 2018
Fix images not being modifiable by mender-artifact in thud and later.
The problem is that the "metadata_csum" feature is very recent, and in
fact even the version shipped in poky (1.44.3) doesn't support it
(both fsck.ext4 and tune2fs refuse to handle it). Why they turned it
on in the first place is a mystery to me. In any case it should be
safe to turn off for our images, so that debugfs (and hence
mender-artifact) is able to handle the image.
If anyone requires this feature, it can be flipped on again on the
built image by a recent version of e2fsprogs/tune2fs.
commit …
```

Several fixes for thud and later

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_1.1.0.bb
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_1.2.0.bb

grub-mender-grubenv_1.1.0.bb got the changes for partuuid instead of 1.2.0.bb.
Signed-off-by: Michael Davis <michael.davis@essvote.com>

Fix grub-mender-grubenv partuuid recipes

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.3.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.4.0.bb
meta-mender-core/recipes-mender/mender/mender_1.6.1.bb
meta-mender-core/recipes-mender/mender/mender_1.7.0.bb

Changelog: Add mender 1.6.1 and 1.7.0 recipes.
Changelog: Add mender-artifact 2.3.1 and 2.4.0 recipes.
(cherry picked from commit 95ef48ee322a0db9187ea4d6c25f3c85d5e4db16)

[sumo] Add Mender 1.7.0 release recipes.

---

meta-mender-core/classes/mender-part-images.bbclass

Turns out that argparse works a bit strangely, and wants all arguments
after one flag, instead of one argument per flag. For example:
--exclude-path data/ boot/efi/
instead of:
--exclude-path data/ --exclude-path boot/efi/

MEN-2290: Fix data directory not being empty on rootfs.

---

tests/acceptance/fixtures.py

This is needed for selectively executing tests in mender-image-tests.
(cherry picked from commit b4e69d2273d10a24f13955c924c1ecd7421fbd1c)

tests: Add min_yocto_version fixture for use in external tests.

---

meta-mender-core/classes/mender-helpers.bbclass

Add NVMe devices to the list of valid devices for GRUB.
Signed-off-by: Stoyan Bogdanov <stoyan.bogdanov@konsulko.com>
@trini

mender-helpers.bbclass: Add NVMe support

---

meta-mender-core/recipes-bsp/grub/files/06_bootargs_grub.cfg

Description of 'rootwait' in kernel docs,
"Wait (indefinitely) for root device to show up.
Useful for devices that are detected asynchronously
(e.g. USB and MMC devices)."
The large majority of devices that we integrate use eMMC for storage
medium, and it is quite common to use a USB "live disk" for provisioning.
Without the 'rootwait' argument, mount of rootfs failes occasionally,
it is simple a race condition at boot and you are only lucky if it works
without it.

add 'rootwait' to bootargs

---

meta-mender-core/classes/mender-setup-grub.inc

Add grub-efi-bootaa64.efi to _MENDER_EFI_BOOT_FILES making sure it actually
gets installed to boot partition.
Signed-off-by: Moritz Fischer <moritz@ettus.com>

mender-setup-grub: Add grub-efi-bootaa64.efi to _MENDER_EFI_BOOT_FILES

---

meta-mender-core/recipes-bsp/grub/grub-mender.inc

Mender generates a grub.cfg that utilizes `[` which is an alias for `test` and
we should probably make sure that it is builtin when grub-mender.inc is used.
This has probably gone unnoticed because the upstream recipe includes this by
default. 
I experienced problems when working with a downstream grub-efi recipe,
which did not include the `test` module in GRUB_BUILDIN. 

grub: ensure "test" module is builtin

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.0.0b1.bb

There is one lite quirk here that I have not handled.
The run-time dependency "liblzma" is not available as a native package, not sure how to handle this.

mender-artifact (3.0.0b1): add missing build dep on "xz"

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-helpers.bbclass

Change the detection of mender-artifact file flag from version based
to checking the help screen, which is easier.

Fix error message `Incorrect Usage: flag provided but not defined: -f`

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Also remove some old ones that whose support was dropped long ago.

Fix license checksum for mender-artifact 3.0.x specifically.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.0.0b1.bb
meta-mender-core/recipes-mender/mender/mender_2.0.0b1.bb

They should use 2.0.x and 3.0.x respectively
Changelog: Fix mender 2.0.x and mender-artifact 3.0.x recipes to use the
correct branches when fetching the source.

Update mender and mender-artifact recipes after branch renames

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.0.0b1.bb

Changelog: Add missing build dependency on "xz" in Mender Artifact recipe for 3.0.0b1 version
This dependency should be added to resolve the below error:
| # github.com/mendersoftware/mender-artifact/vendor/github.com/mendersoftware/go-liblzma
| ../../../../../../../build/src/github.com/mendersoftware/mender-artifact/vendor/github.com/mendersoftware/go-liblzma/reader.go:9:18: fatal error: lzma.h: No such file or directory
| compilation terminated.
Signed-off-by: Ajith P Venugopal <ajithpv@outlook.com>

mender-artifact(3.0.0b1):Add "xz" build dependency

---

meta-mender-core/classes/mender-part-images.bbclass

In thud and newer, when processing the exclude_path logic, if the directory
to be excluded does not exist, then wic will error out.  Only list the
entries if they exist.

mender: Do not exclude missing directories.

---

tests/acceptance/files/Makefile.test_uboot_automation
tests/acceptance/test_uboot_automation.py

```
commit 47d604773c1867ed8f144976597909602de33650
Date:   Thu May 2 13:58:07 2019
test_uboot_compile: Make sure all cores are used.
Right now we may limit by memory since each build directory is very
memory consuming (RAM drive). But that may leave cores unused, so make
sure the sub-make invocations try to use those cores.
commit 6b97f98ded0f3e59b691d6f700aeb6fdb63f0142
Date:   Thu May 2 13:56:38 2019
test_uboot_compile: Make sure the Makefile is counted in time calc.
Otherwise the test might not run even if the file has changed. …
```

test_uboot_compile: Make sure all cores are used.

---

meta-mender-core/classes/mender-setup-image.inc
meta-mender-core/recipes-mender/mender/mender_git.inc
meta-mender-core/recipes-mender/mender/mender_git1.x.bb

This is required in order build 1.x recipes using the git recipe,
since it uses the old makefile style and many other conditionals as
well, such as module inclusion.

Break mender_git recipe into pre- and post-2.0 recipes.

---

meta-mender-core/recipes-bsp/u-boot/u-boot-mender.inc

Fix/workaround for a build problem. The problem can be reproduced by inserting a long sleep at the start of meta-mender-core/recipes-bsp/u-boot/u-boot-mender.inc do_deploy_append_mender-uboot().

Fix build failing in do_image_ubimg task

---

meta-mender-demo/recipes-core/packagegroups/packagegroup-core-boot.bbappend

x86-64 seems to have a problem because Yocto does not include a
`/lib64` folder by default, and this is where most externally built
binaries are built to load the dynamic linker from. Include the LSB
package to make the image LSB compliant and include the `/lib64`
symlink to `/lib`.
Changelog: Demo images now include Yocto LSB package.

MEN-2421: Make sure that external Busybox runs on Yocto demo images.

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/files/06_mender_debug_pause_grub.cfg
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc

This got lost when grub-mender-grubenv was converted to its own
repository, so let's restore it.
Reported-by: Drew Moseley <drew.moseley@northern.tech>

grub-mender-grubenv: Fix broken 'debug-pause' `PACKAGECONFIG`.

---

meta-mender-core/classes/mender-bootimg.bbclass
meta-mender-core/classes/mender-helpers.bbclass
meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-setup.bbclass
tests/acceptance/test_bootimg.py

This contains the contents of /boot for systems that need it separate.

mender: Add support for a bootimg FSTYPE.

---

meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
meta-mender-qemu/scripts/mender-qemu

We can only connect using the Docker IP, so make sure this IP is
reported to the backend. This can then be used to construct a link to
this address.

MEN-2574: QEMU: Add inventory script for Docker IP and open port 80.

---

meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
meta-mender-qemu/scripts/mender-qemu

We can only connect using the Docker IP, so make sure this IP is
reported to the backend. This can then be used to construct a link to
this address.
(cherry picked from commit fa8198779126f30b200dabd17e195360ea6d6e09)

[thud]: MEN-2574: QEMU: Add inventory script for Docker IP and open port 80.

---

tests/acceptance/test_update.py

Based on a patch by Ole Petter <ole.orhagen@northern.tech>

TestFix: Mender-client now returns errcode 2, and ErrorNothingToCommit.

---

tests/acceptance/test_update.py

Based on a patch by Ole Petter <ole.orhagen@northern.tech>
(cherry picked from commit c2c21117451e949b52a498b99e242284106bc50c)

[thud] TestFix: Mender-client now returns errcode 2, and ErrorNothingToCommit.

---

meta-mender-core/classes/mender-helpers.bbclass

This new define is to allow builds when no dtb is produced or the dtb is included inside another file, fit image for example.
Links with pull request #757 that modifies the rocko branch.

Add MENDER_DTB_NAME_FORCE to master branch

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-ubimg.bbclass
meta-mender-qemu/classes/vexpress-nor_image.bbclass
tests/acceptance/fixtures.py
tests/acceptance/test_ubimg.py

We also switch the data partition to use the same mechanism, mostly as
a free testing mechanism for our dataimg image type.
A test is added for ubimg and the corresponding part image test is in
the mender-image-tests repository.
MEN-2597

Ensure that artifact and partition images' checksums are equal.

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/recipes-core/initrdscripts/files/init-install-efi-mender.sh
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend

The current HDDIMG (and ISO for that matter) support in Yocto sets up multiple
bootloader options. One is standard live boot but the other is an install mechanism
so you can install your build onto a target without removable media. This patch
provides a version of this scripting that works with Mender. Basically, the SDIMG
UEFIIMG or MTDIMG file are copied into the HDDIMG and the initrd runs a script
which uses 'dd' to write the image.
This has been tested on an X86 platform with an internal MSATA drive and an external
USB drive.

mender: Setup Live installer.

---

meta-mender-core/classes/mender-full.bbclass
meta-mender-raspberrypi/conf/layer.conf

* `rpi` is not a valid machine name, and there are anyway too many
machine names in that layer to specify all of them. Instead set
unconditionally for the meta-mender-raspberrypi layer.
* We need weak assignment in the meta-mender-core layer, since the
`mender-full.bbclass` is evaluated after the `layer.conf` file, even
if the former layer is listed first.

rpi: Fix several assignment bugs regarding `MENDER_BOOTLOADER_DEFAULT`.

---

meta-mender-qemu/docker/vexpress-qemu/Dockerfile
meta-mender-qemu/scripts/mender-qemu

```
commit 41091d8dfde32a0bfad205d9d7f769a610c46123 (HEAD -> fix-vexpress-qemu-not-starting, lluiscampos/fix-vexpress-qemu-not-starting)
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Tue Jul 30 12:42:39 2019 +0200
Switch to upstream qemu for ARM architecture
Building it from source does not work for Alpine Linux 3.7. The
resulting Docker image is unable to start-up qemu, as many shared
libraries ar not found.
It is unknown if the reset race bug is fixed upstream for this Linux
version.
commit 93e733b67a312f1e05d7266891c70ec72efa926a
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Tue Jul 30 12:40:54 2019 +0200
Exit with failure when qemu-system-xxx cannot start
This was the case when building it …
```

Fix vexpress qemu not starting

---

meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch
meta-mender-core/recipes-mender/mender/files/mender-set-systemd-machine-id.sh
meta-mender-core/recipes-mender/mender/files/mender-systemd-machine-id.service
meta-mender-core/recipes-mender/mender/mender.inc

This patchset  passes the machine-id on the kernel command line to systemd. This ensures that it is the same regardless of which partition is /. It also works properly for read-only root.
I have only lightly tested this on Master but I have a version in Thud that has been tested more thoroughly.

Allow the machine-id to persist

---

meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb

Add PACKAGE_ARCH to force package to be machine-dependent
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

u-boot-fw-utils: set PACKAGE_ARCH as MACHINE_ARCH

---

meta-mender-core/classes/mender-part-images.bbclass
tests/acceptance/test_build.py

```
commit b66beb2945ebb4ceb1465914c53118a48921a6b2
Date:   Fri Sep 6 07:36:14 2019
Fix incorrect partition types after we started using `rawcopy`.
This was introduced in 30a27a9f5e9ba8edb1e879380a64fc8cc994af43. When
we switched away from the `rootfs` source, we lost the identity of the
filesystem, and all partitions became the generic "Microsoft basic
data" type. We fix GPT by using `--part-type` argument, but the MBR
code in wic doesn't support using it, so we need to fix those entries
manually with fdisk.
commit 4eb39076050b08c3a9ce5a335914fb1bd1f45459
Date:   Fri Sep 6 08:38:31 2019
Fix incorrect boot …
```

Several partition type fixes

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_0.1.1.bb

Following modification in deploy naming for the module and therefore
keeping consistency with Yocto name convention.

Rename ARM mender-binary-delta subfolders to 'arm' and 'aarch64'

---

meta-mender-core/recipes-mender/mender-migrate-configuration/mender-migrate-configuration.bb
meta-mender-core/recipes-mender/mender/mender.inc

In the one hand, fix the recipe itself by moving the cp statement to
do_compile as required by mender-state-scripts class.
In the other hand, this recipe will only work if split-mender-config is
disabled in the same build. Add a hard check for this making it depend
on mender and document the improve the usage doc in the changelog entry.
Cancel-changelog: 5acbed2
Changelog: Splits the mender.conf configuration file into a transient
configuration /etc/mender/mender.conf and a persistent congiguration in
/data/mender/mender.conf. This split is enabled by default, and it can
be opt-out by adding `PACKAGECONFIG_remove = "split-mender-config"` to
local.conf.
Changelog: Add a new recipe mender-migrate-configuration to ease the
migration of devices with single mender.conf to the new setup of …

Fix and strict check for mender-migrate-configuration MEN-2757

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-rpi-Drop-reading-of-fdt_addr-from-environment.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-raspberrypi.inc

Current U-Boot logic will use the value in the 'fdt_addr' variable if present in
U-boot enviroment to load DTB. This has shown to be problematic as the address of
where the boot firmware places the DTB can change depending on what is
set in config.txt and cmdline.txt.
For this reason always use the value that is passed on by the boot firmware.
This is what the error looks like:
U-Boot 2019.01 (Sep 26 2019 - 11:56:02 +0000)
DRAM:  948 MiB
RPI 3 Model B+ (0xa020d3)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from MMC... OK
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   No ethernet found.
starting USB...
USB0:   scanning bus 0 for devices... 4 USB Device(s) found
scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
switch …

raspberrypi: add patch to always use 'fdt_addr' passed on by firmware

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-2019.01/0001-configs-rpi4-mender-integration.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot_2019.01.bbappend

meta-raspberrypi carries U-Boot patches to support RPi4, and these
patches are only applied when building 'raspberrypi4' machine. For this
reason we can not have one integration patch for both RPi3 and RPi4 as it
will not apply when building for a RPi3 target.
We have to split out the RPi4 support in a individual patch that is only
applied when buildingfor RPi4.
This will sync-up in future releases once RPi4 support is part of U-Boot
upstream code.

raspberrypi: split RPi3 and RPi4 integration

---

meta-mender-core/classes/mender-setup.bbclass

Fix related to #822. Please include in the `warrior` branch.

mender-setup: do not add systemd options to fstab without mender-systemd

---

meta-mender-core/recipes-mender/mender/mender_git.inc

It is not really required so let's try to keep this function clean.

Remove explicit tag 2.1.1 from licenses checksum in mender git recipe

---

meta-mender-core/classes/mender-setup.bbclass

mender-setup: do not add systemd options to fstab without mender-systemd
Signed-off-by: Benjamin Byholm <benjamin.byholm@walkbase.com>
(cherry picked from commit e55302d3a4951e51c27b619afef3819aec141b80)

Warrior update

---

tests/acceptance/test_build.py

The current mender-version guard had a version of 2.0.0, which is too low, since
the changes in mender-artifact which holds the depends and provides
functionality is only available in master at the moment of this writing. Hence
set the tag to 2.2.0, which for now only includes the master branch.
Without this fix, cherry-picks to older branches will fail the acceptance tests,
if they employ older versions of mender-artifact.

Update min_mender_version sentinel to 2.2.0 for artifact deps tests

---

meta-mender-core/classes/mender-setup.bbclass

The index is "3" when no bootpart is present, because we will get rid of
the "extended" partition if we remove boot part.
Changelog: Fix boot when MENDER_DATA_PART_DEFAULT = "0"

fix MENDER_DATA_PART default value when creating image without bootpart

---

tests/acceptance/requirements_py3.txt

Add pytest-html plugin to pip3 requirements
So that the CI can generate and collect HTML reports. This dependency
was overlooked during PR #849

Add pytest-html plugin to pip3 requirements

---

meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc

When u-boot is built with KERNEL_IMAGETYPE="fitImage", the wrong boot command
(MENDER_BOOT_KERNEL_TYPE) was chosen in do_provide_mender_defines because
the selection defaults to "bootz". The correct command is "bootm" because a
fitImage is an extended uImage format. For details about this format, see:
https://github.com/u-boot/u-boot/blob/master/doc/uImage.FIT/howto.txt
Signed-off-by: Joerg Hofrichter <joerg.hofrichter@ni.com>

u-boot-mender: set correct boot command for fitImage

---

meta-mender-core/recipes-mender/mender/mender.inc

Add textrel to the 'INSANE_SKIP_${PN}' to avoid below Yocto QA warning:
> WARNING: mender-2.0.0-r0 do_package_qa: QA Issue: ELF binary ‘<build_dir>/tmp/work/aarch64-poky-linux/mender/2.0.0-r0/packages-split/mender/usr/bin/mender’ has relocations in .text [textrel]
Signed-off-by: Ajith P V <ajithpv@outlook.com>

Add textrel skip to Sumo

---

tests/acceptance/requirements_py3.txt
tests/acceptance/test_update.py

We are getting connection refused error some times in the client
acceptance tests. It does not seem possible to reproduce locally.
With this checks we can see if the problem is in the server side or
maybe in the QEMU networking (forwarding 10.0.2.2 to the host).

Use Python3 when starting the HTTP server and add connection checks

---

.gitlab-ci.yml
pyproject.toml

This adds a .gitlab-ci.yml file which includes the
'.gitlab-ci-check-python3-format.yml' file, which ensures that the python code
in the acceptance directory is formatted correctly.

Enable CI verification of Python formatting for acceptance tests

---

tests/acceptance/requirements_py3.txt
tests/acceptance/test_build.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_uboot_automation.py
tests/acceptance/test_update.py

```
commit d0087be0812aa5817b67ffec0eeb2a02fafebd0b
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Jan 20 14:12:00 2020 +0100
Set pytest version to 5.3.2 and fix the rest of the dependencies
The acceptance tests started failing on 18/01/2020 just after upstream
release of latest pytest 5.3.3.
The actual issue requires further investigation, but for now let's block
the versions used for testing: setting pytest to 5.3.2 and the rest to
the latest release.
commit a4f49639d2e3c7575025645b26bc5aaccd8cf101
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Jan 20 14:10:46 2020 +0100
Get the rid of all warnings related to scape chars in regex
```

Set pytest version and fix warnings

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc

Make sure the target directory exists when debug-log is enabled.
(cherry picked from commit a523cacf729a0dc6158709b15db06fc32b5643ca)

cherry-pick: grub-mender-grubenv: Fix broken debug-log PACKAGECONFIG.

---

meta-mender-core/classes/mender-full.bbclass

`mender-growfs-data` and `MENDER_EXTRA_PARTS` are mutually exclusive,
so set the default of `mender-growfs-data` to off if
`MENDER_EXTRA_PARTS` is being used.

Fix failure in boot log when `MENDER_EXTRA_PARTS` is used.

---

meta-mender-core/classes/mender-helpers.bbclass

Signed-off-by: Matthew Beckler <matthew@packetpower.com>
Hello, this is my first contribution to Mender. I ran into [MEN-2494](https://tracker.mender.io/browse/MEN-2494) and thought it might be a good first PR. Hope I followed the guidelines correctly.
Here's how the new warning appears when building for beaglebone:
`WARNING: u-boot-1_2019.01-r0 do_provide_mender_defines: Found more than one dtb specified in KERNEL_DEVICETREE (am335x-bone.dtb am335x-boneblack.dtb am335x-bonegreen.dtb). Only one should be specified. Choosing the last one: am335x-bonegreen.dtb. Set KERNEL_DEVICETREE to the desired dtb file to silence this warning.`

Improve warning when multiple DTB files are in KERNEL_DEVICETREE

---

meta-mender-core/recipes-mender/mender/mender.inc
meta-mender-demo/recipes-mender/mender/mender_%.bbappend
tests/meta-mender-ci/recipes-testing/read-only-rootfs/mender_%.bbappend

This fixes an issue with `mender setup`.
MEN-3048

In demo mode, put demo certificate in same directory as Debian package.

---

meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi-mender.inc

meta-mender removes `root=/dev/mmcblk0p2`, and then appends `root=\${mender_kernel_root}` (notice no trailing whitespace) to CMDLINE. However, when pitft feature is enabled, meta-raspberrypi additionally adds `fbcon=map:10 fbcon=font:VGA8x8` to cmdline.txt (refer [here](https://github.com/agherzan/meta-raspberrypi/blob/251a351fc328d30abcbdb054b9e6b3eb301feebb/recipes-kernel/linux/linux-raspberrypi.inc#L139))
This screws up CMDLINE (no space in-between `root` and `fbcon` arguments) when meta-mender is used with meta-raspberrypi with pitft enabled. The problem can be fixed in either `meta-raspberrypi` or `meta-mender`. So let me know your opinion :+1:

rpi: fix rootfs cmdline trailing space

---

meta-mender-core/classes/mender-part-images.bbclass

This will help when not using `mender-grub`, and instead using
Barebox, for example.

Improve dependency logic to not require U-Boot unconditionally on ARM.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.3.0.bb
meta-mender-core/recipes-mender/mender/mender_2.1.3.bb
meta-mender-core/recipes-mender/mender/mender_2.2.0.bb

- Add mender 2.2.0 recipe and remove beta
- Add mender-artifact 3.3.0 recipe and remove beta
- Add mender 2.1.3 recipe

Add recipes for Mender 2.3.0 and 2.2.2 releases

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.bb

The new "mender-client.service" will not exist for those versions.

Revert to "mender.service" when building Git versions < 2.2.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.0.1.bb

From the Yocto Manual changes to zeus:
``` The file-rdeps runtime dependency check no longer expands RDEPENDS
recursively as there is no mechanism to ensure they can be fully computed, and
thus races sometimes result in errors either showing up or not. Thus, you might
now see errors for missing runtime dependencies that were previously satisfied
recursively. Here is an example: package A contains a shell script starting with
B, which does depend on bash. You need to add the missing dependency or
dependencies to resolve the warning.
```
Which is what did bite us this time, as the `xz` dependency did resolve it
recursively previously.

MEN-3263: Explicitly add liblzma to RDEPENDS

---

tests/acceptance/test_update.py

Commit cd5c489 made this test strictly not compatible with older mender
releases (where the logger still used stdout).
Furthermore, the commit introduced an error in the second assert, as the
"ret_code=0" will not be seen in stderr in any case.
See #942

Amend test_too_big_image_update to accept both stdout/stderr

---

meta-mender-raspberrypi/classes/rpi-update-firmware.bbclass
meta-mender-raspberrypi/recipes-mender/update-firmware-state-script/files/ArtifactInstall_Leave_50.in
meta-mender-raspberrypi/recipes-mender/update-firmware-state-script/update-firmware-state-script.bb

Raspberry Pi boards have a set of boot firmware files that are
located on the vfat boot part, and these files are normally not updated
when you perform an update of the root filesystem.
Occasionally there will be changes to the Raspberry Pi software stack
that requires that these files are update. Typically there is something
in the Linux kernel that requires something that is in the boot
firmware. This means that to update the Linux kernel you must also
update the boot firmware files.
Above is really sub-optimal design of the Raspberry Pi boards but a
limitation that we must live with.
Note that the DTB files are also part of "boot firmware" and included in
the state script update.
The provided state-script can be enabled by adding the following to e.g
local.conf:
INHERIT += …

raspberrypi: add state script to update boot firmware

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_git.bb
meta-mender-core/recipes-mender/mender-client-migrate-configuration/mender-client-migrate-configuration.bb

Changelog: grubenv: Handle debug command prompt when running as EFI
app.

Update to new grub-mender-grubenv SHA.

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Checksum update for mender-artifact dependency in mender.

MEN-3345: Merge Artifact depends i4

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

It seems that the following command fails:
/usr/sbin/parted -s /dev/mmcblk0 resizepart 4 100%
if GPT PMBR is not present, e.g
GPT PMBR size mismatch (8388607 != 125045423) will be corrected by write.
The backup GPT table is not on the end of the device. This problem will be corrected by write.
Disk /dev/sda: 59.6 GiB, 64023257088 bytes, 125045424 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 4024D69C-D9FD-4BBD-9625-4B10975CD498
Device       Start     End Sectors  Size Type
/dev/sda1    16384   49151   32768   16M EFI System
/dev/sda2    49152 4079615 4030464  1.9G Linux filesystem
/dev/sda3  4079616 8110079 4030464  1.9G Linux filesystem
/dev/sda4 …

MEN-3366: write GPT partition table before resize of data part

---

meta-mender-raspberrypi/recipes-mender/update-firmware-state-script/files/ArtifactInstall_Leave_50.in

The ArtifactInstall_Leave_50 state script fails on busybox systems because umount does not understand the long `--lazy` flag :
> stderr collected while running script /var/lib/mender/scripts/ArtifactInstall_Leave_50 [umount: unrecognized option '--lazy'\nBusyBox v1.27.2 (2018-12-03 18:22:35 UTC) multi-call binary.\n\nUsage: umount [OPTIONS] FILESYSTEM|DIRECTORY\n]" module=executor
The short `-l` flag is useable with both util-linux and busybox versions of umount.

raspberrypi: busybox compatibility for boot firmware state script

---

tests/acceptance/fixtures.py

Otherwise all remote reports get copied to the same local file
named "coverage", overriding it every time.

[tests] Create coverage dir before calling scp

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

This is needed to go along with PR:
https://github.com/mendersoftware/mender-artifact/pull/268
Which adds multiple new entries to the LIC_FILES_CHKSUM.sha256 file as a result
of upgrading dependencies, and moving to go modules.

chore(checksum): Update the Mender Artifact master checksum

---

meta-mender-core/classes/grub-mender-grubenv.bbclass
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_git.bb
meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled_2.04.bb

The URLs include the revision SHA of grub-mender-grubenv as well as
the version of GRUB, which means we can get a stable checksum instead
of a constantly changing one.
Also standardize on some things that are shared between the
grub-efi-mender-precompiled and grub-mender-grubenv recipes, such as
URIs, revisions and the GRUB module list. We also check that the GRUB
module list defined in Yocto is the same as the one used to compile
the binaries.

MEN-3477: Start downloading grub-efi from grub-mender-grubenv URLs.

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc

The only way to use GRUB 2.04 on ARM is via UEFI, and the
kernel_devicetree information is not used when loading via UEFI,
instead it is queried directly from the UEFI provider.

grub-mender-grubenv: Remove kernel_devicetree.

---

tests/acceptance/fixtures.py
tests/acceptance/test_snapshot.py

We do this by running both with and without terminal.

MEN-3580: Catch SIGCHLD errors in mender-artifact snapshot test.

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

This actually adds an unnecessary dependency when using Git SHAs for
older versions of Mender, but this should be harmless, and it won't
affect production recipes.

Add OpenSSL as dependency for Git versions of the Mender client.

---

tests/acceptance/fixtures.py

It the target did not generate coverage reports, skip creating locally a
"coverage" dir so that the CI does not expect files there.

[acceptance tests] Do not create empty "coverage" dir

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.0.1.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.0b1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.0b1.bb
meta-mender-core/recipes-mender/mender/mender_2.3.0b1.bb
meta-mender-core/recipes-mender/mender/mender_git.inc

This contains some notable differences from #998, namely that all the references to "mender-client" have been reverted to "mender", since this is the name which is used on warrior.

Warrior updates for 2.4.0b1 Mender Product release

---

meta-mender-core/classes/mender-setup-image.inc
tests/acceptance/fixtures.py
tests/acceptance/test_os_integration.py
tests/build-conf/beagleboneblack/local.conf

```
commit 1c2c2d165383e76a6335baa41144bc4479fe8e6a
Date:   Wed Jun 24 15:30:58 2020
MEN-3676: Add acceptance test for syslog functionality.
commit 8c46643d0f7c7b1be2aa53aac505ecf133bdccfd
Date:   Wed Jun 24 15:29:23 2020
Fix a few missing renames from "mender" to "mender-client".
```

MEN-3676: Add acceptance test for syslog functionality.

---

meta-mender-core/recipes-devtools/mtools/mtools/clang_UNUSED.patch
meta-mender-core/recipes-devtools/mtools/mtools/disable-hardcoded-configs.patch
meta-mender-core/recipes-devtools/mtools/mtools/mtools-makeinfo.patch
meta-mender-core/recipes-devtools/mtools/mtools/no-x11.gplv3.patch
meta-mender-core/recipes-devtools/mtools/mtools_4.0.23.bb

With mtools 4.0.19 in Yocto Warrior, 'mcopy' causes corruption in the boot partition when copying the EFI directory.
Fix this by importing mtools 4.0.23 from the Yocto Zeus branch.
Observed error:
```
fsck.fat 4.1 (2017-01-24)
/EFI/BOOT/.
Bad short file name (.).
Auto-renaming it.
Renamed to FSCK0000.000
/EFI/BOOT/..
Bad short file name (..).
Auto-renaming it.
Renamed to FSCK0000.001
/EFI/BOOT/FSCK0000.000
File size is 0 bytes, cluster chain length is > 0 bytes.
Truncating file to 0 bytes.
/EFI/BOOT/FSCK0000.001
File size is 0 bytes, cluster chain length is > 0 bytes.
Truncating file to 0 bytes.
/EFI/BOOT/mender_grubenv1
Has a large number of bad entries. (2/5)
Not dropping it in auto-mode.
/EFI/BOOT/mender_grubenv1/.
Bad short file name (.).
Auto-renaming it.
Renamed to FSCK0000.000 …
```

[Warrior] Fix EFI boot partition corruption with mtools 4.0.19

---

meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_patch.sh
tests/acceptance/files/Makefile.test_uboot_automation
tests/acceptance/test_uboot_automation.py

```
commit 1e7f2153ca32c10eb0ae7baa30d29e0d98c7d614
Date:   Wed Jun 24 17:52:55 2020
test_uboot_compile: Update test conditions after fixes in this area.
commit 0467a6f855d1013281885b3ef61061c3ff7b7d6b
Date:   Wed Jun 24 17:47:21 2020
uboot_auto_configure: Handle unwanted config options better.
Actively disable CONFIG options we want to get rid of instead of just
removing them from the defconfig file. This helps in the case where we
try to remove an option, but it's immediately brought back because the
default is to be on.
Changelog: U-Boot auto-configuration: Better algorithm for removing
options from …
```

U-Boot compile test fixes

---

meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc

The uboot_auto_configure.sh script uses the cross compiler to build
cmd/version.o from the U-Boot sources so it can generate a list of files to
patch. However, this will fail if the target board (and therefore the target
toolchain) uses floating point flags (e.g. armv5tehf-vfp) since U-Boot is not
meant to be built with floating-point.
The Yocto recipes invoke the cross toolchain when building U-Boot in a way
so that any floating-point build flags are not passed to the build. Tweak
the way the cross toolchain is invoked by following the way Yocto invokes
it.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>

uboot_auto_configure: build U-Boot the same way Yocto does

---

meta-mender-demo/recipes-extended/images/mender-image-full-cmdline-rofs.bb

On zeus we need the 64bit fix. This fix is already applied in the
meta-mender-commercial layer, but this layer is not used for this
particular test image.

MEN-3781: Make sure that our Docker rofs image is zeus compatible.

---

meta-mender-demo/recipes-extended/images/mender-image-full-cmdline-rofs.bb

On zeus we need the 64bit fix. This fix is already applied in the
meta-mender-commercial layer, but this layer is not used for this
particular test image.
(cherry picked from commit e4d8ddb58be1291165b3a798b0d576ee4cbb1f2f)

zeus: MEN-3781: Make sure that our Docker rofs image is zeus compatible.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.3.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.2.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.0.bb

Changelog: Add mender-2.2.1 and mender-artifact-3.3.1 recipes.
Changelog: Add mender-2.3.0 and mender-artifact-3.4.0 recipes.
Changelog: Add mender-binary-delta-1.1.0 release.

Add recipes for 2.3.1 and 2.4.0 release.

---

meta-mender-core/recipes-bsp/u-boot/libubootenv_%.bbappend
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-helpers.inc
meta-mender-core/recipes-bsp/u-boot/u-boot-mender.inc

Changelog: Fix incorrect BOOTENV_SIZE value being used in libubootenv
recipe. The symptom of this was a non-working set of `fw_printenv` and
`fw_setenv` tools:
```
root@raspberrypi4:~# fw_printenv
Cannot read environment, using default
Cannot read default environment from file
```
This was accidentally broken in commit f61fa534d43dcd, where the
task was originally handled by the u-boot-fw-utils recipe files.

MEN-3834: Fix incorrect BOOTENV_SIZE value being used in libubootenv.

---

meta-mender-core/recipes-core/systemd/systemd_%.bbappend

On dunfell it is apparently not enough anymore to just specify
`set-time-epoch` to force systemd to use 1st Jan 1970 as epoch. It is
apparently possible to to use any epoch you like, and the default is
the build time, so we need to specifically set it to zero. See the
comment above the change for context on why the epoch is needed in the
first place.
Changelog: Fix fsck running on every boot in dunfell.
Thank you!

Fix broken `set-time-epoch` feature in dunfell.

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-resize-data-part.sh.in

This change is needed for warrior MBR systems using BusyBox's fdisk.
Signed-off-by: oriday <Ossian.Riday@gmail.com>
Thank you!

[MEN-3761]MBR systems don't have a backup header, so always return true

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-systemd-machine-id.service
meta-mender-core/recipes-mender/mender-client/mender-client.inc

Please note that I'm submitting this PR to dunfell because that's where I've tested this, but the same change appears to be applicable to master as well. 
---
Fix for the the following:
```
ERROR: mender-client-2.3.0-r0 do_package: QA Issue: mender-client: Files/directories were installed but not shipped in any package:
/lib/systemd/system/mender-client-systemd-machine-id.service
```
This service is installed with a name based on the MENDER_CLIENT
variable, but this variable was not used in FILES. Previously, the
file names matched, but it now needs to be updated as the value of
MENDER_CLIENT has been changed.

mender-client: fix install of systemd-machine-id.service

---

meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend

Fixes a rebuild problem that arises when having built with 'MENDER_STORAGE_DEVICE' set to one value, then changing it and rebuilding.
In that case, the 'devnode' variable inside 'init-install-efi-mender.sh' is NOT updated, producing invalid images.
The root cause was that bitbake does not re-fetch the 'init-install-efi-mender.sh' file.
Sed is then executed on the file where 'MENDER_STORAGE_DEVICE' has already been replaced from a previous sed execution.
Fixed by using an intermediate file instead.
If you reach this problem, fixing it requires cleaning: 'bitbake initramfs-module-install-efi -c clean'

 initramfs-module-install-efi: Ensure variable changes are reflected on rebuild

---

meta-mender-qemu/recipes-connectivity/openssl/openssl_%.bbappend

_Note_: goes with [mender/pull/581](https://github.com/mendersoftware/mender/pull/581)
ChangeLog:none

MEN-3730 OpenSSL: set SECLEVEL=2 in /etc/ssl/openssl.cnf

---

meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend

Fixes a rebuild problem that arises when having built with 'MENDER_STORAGE_DEVICE' set to one value, then changing it and rebuilding.
In that case, the 'devnode' variable inside 'init-install-efi-mender.sh' is NOT updated, producing invalid images.
The root cause was that bitbake does not re-fetch the 'init-install-efi-mender.sh' file.
Sed is then executed on the file where 'MENDER_STORAGE_DEVICE' has already been replaced from a previous sed execution.
Fixed by using an intermediate file instead.
If you reach this problem, fixing it requires cleaning: 'bitbake initramfs-module-install-efi -c clean'
Signed-off-by: Kasper Føns <kf@chora.dk>
(cherry picked from commit ca9fca8b7cfb1ae0b4644ae7c68d9cd244e0dde5)
🚨 Please review the [guidelines for …

[dunfell] initramfs-module-install-efi: Ensure variable changes are reflected on rebuild

---

meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend

Fixes a rebuild problem that arises when having built with 'MENDER_STORAGE_DEVICE' set to one value, then changing it and rebuilding.
In that case, the 'devnode' variable inside 'init-install-efi-mender.sh' is NOT updated, producing invalid images.
The root cause was that bitbake does not re-fetch the 'init-install-efi-mender.sh' file.
Sed is then executed on the file where 'MENDER_STORAGE_DEVICE' has already been replaced from a previous sed execution.
Fixed by using an intermediate file instead.
If you reach this problem, fixing it requires cleaning: 'bitbake initramfs-module-install-efi -c clean'
Signed-off-by: Kasper Føns <kf@chora.dk>
(cherry picked from commit ca9fca8b7cfb1ae0b4644ae7c68d9cd244e0dde5)
🚨 Please review the [guidelines for …

[warrior] initramfs-module-install-efi: Ensure variable changes are reflected on rebuild

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Update of the LIC_FILES_CHKSUM.sha256 check sum
for https://github.com/mendersoftware/mender/pull/587
ChangeLog:none

update mender-client LIC md5 for mender/pull/587

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-demo/recipes-mender/mender-client/mender-client_%.bbappend

The default is changed in order to have a better chance to fix
problems on devices, when the rootfs-image setup us not working, for
example by using the script module.
Changelog: Install standard Mender Update Modules by default. These
are:
* deb
* directory
* docker
* rpm
* script
* single-file
To disable the automatic installation of these Update Modules, add
`PACKAGECONFIG_remove = "modules"` to your `mender_%.bbappend` file,
or set `PACKAGECONFIG` explicitly.

Install standard Mender Update Modules by default.

---

meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

This is needed on zeus and older, which do not use libubootenv.

MEN-3851: Warn when detecting U-Boot version without script '=' support. 

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch

The u-boot integration link has been broken since Mender 1.7.

Update docs.mender.io links from u-boot patches

---

meta-mender-commercial/conf/layer.conf
meta-mender-demo/recipes-extended/images/mender-image-full-cmdline-rofs.bb

There is evidence from users of mender-convert that having the
`has_journal` feature turned on in the filesystem features causes fsck
to break the checksum of the filesystem, even when it doesn't make any
changes. Currently the Yocto-produced image does not run fsck, so it
is not a problem there, but it could be if someone uses an initrd for
example (this is where fsck is run in the mender-convert case). So
this fix is simply about being proactive and disabling it now, before
it becomes a problem.
Changelog: Disable filesystem journal on read-only-rootfs, which
sometimes causes unstable rootfs checksum together with fsck.

MEN-3912: Disable filesystem journal on read-only-rootfs.

---

meta-mender-core/recipes-bsp/u-boot/files/add_kconfig_option_with_depends.py

Changelog: Fixed key extraction by skipping new lines in defconfig.
The `add_kconfig_option_with_depends.py` file throws `Not sure how to
handle Kconfig option that doesn't start with 'CONFIG_'` when the
provided defconfig file contains blank lines. It has been fixed by
checking for empty lines before processing for keys.
Signed-off-by: Daniel Selvan D <danilselvan@gmail.com>
Modified-by: Kristian Amlie <kristian.amlie@northern.tech>
* Adjusted commit message and squashed.

uboot_auto_config: Fixed key extraction by skipping new lines in defconfig

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.3.1.bb
meta-mender-core/recipes-mender/mender/mender_2.2.1.bb
tests/acceptance/test_update.py

Changelog: Add mender 2.2.1 recipe
Changelog: Add mender-artifact 3.3.1 recipe
Changelog: Remove mender 2.2.0b1 recipe
Changelog: Remove mender-artifact 3.3.0b1 recipe
Same as #1081 and #1078.

Add recipes for Mender 2.3.1 components to thud

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.inc
meta-mender-core/recipes-mender/mender-client/mender-client.inc
tests/meta-mender-ci/recipes-testing/mender-coverage-client/gobinarycoverage.bb

The ptest part of go class was separated to go-ptest class some time
before zeus. See poky commit 70a862a.
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=70a862a367beea2c92ec0fb1bcaba41b942c78ac
By the looks of it, since then we have not been running unit tests on
our mender-client and mender-artifact recipes builds.

Inherit go-ptest in Mender golang recipes

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

It will go into the feature branch together with https://github.com/mendersoftware/mender/pull/625
This is provisional, we will have a better approach (and a proper Changelog tag) with [MEN-4014](https://tracker.mender.io/browse/MEN-4014)

MEN-4032: Add glib-2.0 dependency for mender-client

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc

```
commit f08e4c8819da6446fc3ec90802f9b57b61bed251
Date:   Mon Oct 12 13:02:01 2020
mender-binary-delta: Fix broken do_version_check.
For unknown reasons, the "noexec" flag is not actually possible to
turn off, not even with "0" nor "". The only way to disable it is to
remove it, which kind of defeats the purpose of having it. Luckily
it's easy to work around, so just do the variable check in code
instead.
The reason this has passed in our CI is that it is not covered by the
sstate cache, so if it had a hit then this problem would not reveal
itself.
commit 14113b2f3d8a4a2688ea9879f565caca2dade015
Date: …
```

mender-binary-delta: do_version_check() fixes

---

meta-mender-commercial/conf/layer.conf
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc
meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh
meta-mender-core/recipes-kernel/linux/boot-partition-devicetree.bb
meta-mender-demo/recipes-extended/images/mender-image-full-cmdline-rofs.bb
tests/acceptance/test_build.py

Bringing all relevant changes from [dunfell-v2020.10](https://docs.mender.io/development/release-information/release-notes-changelog#meta-mender-dunfell-v2020-10) into `zeus`, notably skipping the "Yocto check layer" changes (#1097 and #1037).

Zeus update v2020.10.2

---

meta-mender-commercial/conf/layer.conf
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc
meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh
meta-mender-demo/recipes-extended/images/mender-image-full-cmdline-rofs.bb

Bringing all relevant changes from [dunfell-v2020.10](https://docs.mender.io/development/release-information/release-notes-changelog#meta-mender-dunfell-v2020-10) into `warrior`, notably skipping the "Yocto check layer" changes (#1097 and #1037).
Added commits 401c6d8b4562af7ae79fd53d0ad778b0b797d895 and e4d8ddb58be1291165b3a798b0d576ee4cbb1f2f, which were missed in previous updates for unknown reason.
See also #1120.

Warrior update v2020.10.2

---

.gitmodules
tests/acceptance/conftest.py

From now on, the integration pipeline will not be cloning separately
mender-image-tests and then hacking meta-mender to use such clone, but
just use whatever is submodule'd here.
This commit updates the submodule to latest, removes the --no-pull
functionality, and removes the ignore of the submodule to make
developers aware.
See related PR https://github.com/mendersoftware/mender-qa/pull/432

[tests/acceptance] Remove --no-pull and update image-tests

---

.github/dependabot.yml

Trigger submodule update from zeus on, including future yocto branches.
Note that warrior is out as it uses Python 2 and, as per today, can not
be further updated.

[dependabot] Extend submodule update to maintained branches

---

meta-mender-core/recipes-mender/mender-client/mender-client_2.4.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

For 2.4.0 recipe, 2.4.x builds, and master builds.

mender-client: Update LICENSE to include OpenSSL

---

.github/dependabot.yml

By explicitly marking the first entry with target_branch master, so that
dependabot does not detect the rest as duplicates of this one.

[dependabot] Fix parse error in dependabot file

---

tests/acceptance/common.py

* [tests/acceptance] common.py: Remove scp compression
We run tests only on virtual devices, so the compression overhead does
not pay off compared to the transmission time.
* [tests/acceptance] common.py: Remove try/catch in put_no_sftp
It added no value to the function. Also now both put/get functions are
aligned.

[tests/acceptance] common.py: minor improvements

---

meta-mender-core/classes/mender-maybe-setup.bbclass

Instead of being appended to OVERRIDES, mender specific overrides
should be appended to DISTROOVERRIDES. This ensures mender overrides
not break the order in OVERRIDES, for instance, the 'forcevariable'
override should always be the last in OVERRIDES.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
Thank you!

mender-maybe-setup.bbclass: move mender overrides to DISTROOVERRIDES

---

tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/fixtures.py
tests/acceptance/pytest.ini
tests/acceptance/test_bootimg.py
tests/acceptance/test_build.py
tests/acceptance/test_dataimg.py
tests/acceptance/test_inventory.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_os_integration.py
tests/acceptance/test_snapshot.py
tests/acceptance/test_ubimg.py
tests/acceptance/test_uboot_automation.py

There is enough confusion with discerning Mender releases from Mender client
release versions already.
Let us try and keep them at a minimum by explicilty noting that we are referring
to the client release.

rename: min_mender_version -> min_mender_client_version

---

meta-mender-core/recipes-mender/mender-shell/mender-shell.bb

Changelog: Add a recipe for building 'mender-shell', remote shell support.

MEN-4083: Add a build recipe for mender-shell

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
tests/acceptance/test_build.py

```
commit 27b4ae73fddf7ae89f543756d09136a30a0368ba
Date:   Thu Nov 5 11:06:20 2020
Update mender-image-tests in order to test DBus files.
commit dee4d841beeeb6815f4cb3dfe4c9e1b53c3e25c8
Date:   Thu Nov 5 11:05:42 2020
Update mender-client checksum after adding godbus test dependency.
commit 3b94af210b622d0cd771f57c334758c0dc62f9ff
Date:   Thu Nov 5 08:14:25 2020
MEN-4030: Test that busconfig files are gone when dbus is off.
Signed-off-by: Kristian Amlie …
```

MEN-4030: Add DBus busconfig file

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bb
tests/acceptance/test_build.py

This adds a feature: 'mender-inventory-geo-script' which installs the
inventory-geo script as an inventory script when the Mender-client is installed.
By default, this is a sub-feature of the following features to go along with the
current setup which installs the script by default:
* mender-full
* mender-full-ubi
* mender-full-bios

Add a feature for the inventory-geo-script in the Mender-client

---

tests/acceptance/test_snapshot.py

The fix for the sudo bug is on the released Mender-Artifact 3.4.x branch, but is
not yet released, meaning that it is not in the 3.4.0 tag in Mender-Artifact:
https://github.com/mendersoftware/mender-artifact/commits/3.4.0
Therefore, this will only be in master and be released with Mender release 2.6.0

test: bump min mender version

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-shell/mender-shell.bb

This doesn't actually cover all license we use, so it should not be
used for production recipes, but should be acceptable for the Git
recipes.

Switch to a more relaxed license checksum checker for the Git recipe.

---

tests/acceptance/test_build.py

By appending a comma, the parentheses turn into a tuple, which always
evaluates to true, regardless of its content. This fixes warnings of
the type:
```
PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
```

Fix always-true condition in test.

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

Where install-inventory targets were not yet split.

mender-client: fix build for 2.4.x and earlier

---

tests/acceptance/test_dbus.py
tests/meta-mender-ci/conf/layer.conf

Install a non-root user in meta-mender-ci and use it in the new test to
verify that AccessDenied is returned when accessing Mender D-Bus API.

MEN-4033: Acceptance test test_dbus_non_root_access

---

meta-mender-core/recipes-mender/mender-shell/mender-shell.bb

Namely:
* inherit go instead of go-mod
* inherit pkgconfig instead of manually specifying dependency
* fix do_compile function
* reorder declarations
* use term "add-on" in description

mender-shell: align recipe with other Mender go recipes

---

meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc

Add another kernel module to QEMU, needed by TestFaultTolerance.

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-shell/mender-shell.bb

Changelog: mender-shell: generate and install mender-shell.conf with
required fields. `ServerURL` can be configured setting yocto variable
`MENDER_SERVER_URL`, same as used by mender-client recipe. If a
`mender-shell.conf` file is found in the `SRC_URI`, the contents will be
merged.
Note: includes test from https://github.com/mendersoftware/mender-image-tests/pull/33
In addition:
* mender-client: fix QA Issue: invalid PACKAGECONFIG: inventory-network-scripts

MEN-4242: mender-shell: generate and install mender-shell.conf

---

meta-mender-core/recipes-mender/mender-shell/mender-shell.bb
meta-mender-demo/recipes-mender/mender-shell/mender-shell.bbappend

Changelog: mender-shell: Add `User` to generated mender-shell.conf. The
value of it is configured using `MENDER_SHELL_USER` variable, which
defaults to `nobody` for meta-mender-core and `root` for
meta-mender-demo.
This PR contains https://github.com/mendersoftware/mender-image-tests/pull/34

mender-shell: Add User filed to mender-shell.conf

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/recipes-mender/mender-shell/mender-shell.bb
meta-mender-demo/conf/layer.conf
meta-mender-demo/recipes-mender/mender-shell/mender-shell.bbappend

As the title says:
* Bring mender-shell related commits (skipped from #1172 due to #1213).
* Revert rootfs label change (see #1219).
* And update tests (from #1232).
This should be all to finally tag/release `zeus`.

[zeus] mender-shell + revert rootfs labels + tests updates

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

By conditionally expecting or not an install-dbus target in the
Makefile.

mender-client.inc: support git build for 2.4.x and earlier

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
tests/acceptance/test_build.py

Amend of #1236:
```
Fix shell script parse error when no dbus in PACKAGECONFIG
Error introduced at 4f8b02a, and it only shows when building with
preferred version master (grep succeed) and removing dbus from
PACKAGECONFIG.
```
And  and revert of #1237:
```
Revert "[tests/acceptance] test_build_nodbus: set min mender 2.5.0"
This reverts commit 76a2d441692d741701b7cd4ac60ae2d7db0a4c71.
This commit was not needed in the first place, the error that motivated
it was miss-understood. See previous commit fixing the shell syntax.
```

Amend shell syntax conditional dbus + revert skip test

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-qemu/docker/qemux86-64/Dockerfile
tests/acceptance/requirements_py3.txt
tests/meta-mender-ci/conf/distro/poky-mender-ci.conf

#1240, #1241, #1242, #1244 and:
* [tests/acceptance] Remove pytest-xdist from requirements
(makes #1243 N.A.)
* [mender-client.inc] Remove nonexisting file from FILES
* [meta-mender-ci] Remove override of PACKAGE_CLASSES

Dependabot updates + Misc clean-ups

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-client/mender-client_2.2.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bb
tests/acceptance/test_build.py
tests/meta-mender-ci/recipes-mender/mender-client/mender-client_%.bbappend

In addition, I ported the minumum commits to fix mender-client build in `dunfell`.
Changelog: mender-client: The self-signed Mender server certificate, if
present, is copied to ca-certificates in addition to
`MENDER_CERT_LOCATION` to be trusted by other services running in the
device.

MEN-4273 (dunfell): Copy self-signed certificate to ca-certificates

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

And clean-up unnecessary md5 field in mender_license function.

[mender-artifact] Update LICENSE checksum on git recipe

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

And clean-up unnecessary md5 field in mender_license function.
(cherry picked from commit f98adbbcd9c27b728740c60714e699b6eee44a63)

dunfell: [mender-artifact] Update LICENSE checksum on git recipe

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.0.bb

It depends on mender-artifact 3.5, which has not been released yet.

Temporarily down-prioritize mender-binary-delta 1.2.0 in version sel.

---

meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-demo/recipes-mender/mender-connect/mender-connect_%.bbappend

Set it to /bin/bash in the meta-mender-demo layer

Add the MENDER_CONNECT_SHELL to meta-mender-core, defaults to /bin/sh

---

meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-demo/recipes-mender/mender-connect/mender-connect_%.bbappend

Bring #1271 to `dunfell` to build the release candidate there.

[dunfell] Add the MENDER_CONNECT_SHELL to meta-mender-core, defaults to /bin/sh

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-demo/conf/layer.conf
meta-mender-demo/recipes-core/packagegroups/packagegroup-core-boot.bbappend

Also make sure the demo layer only installs it if we are building a
recent enough client. `layer.conf` seems to have some restrictions on
inline Python, so move it to a recipe as a dependency instead.

Make mender-connect dependent on mender-client.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.5.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.5.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect.inc
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb

* Add recipe mender-connect 1.0.0
Moving most of the logic of the old git recipe into an inc file, and
reworking the new git recipe as for other mender recipes.
* Add mender-client and mender-artifact new recipes
Changelog: Add recipe mender-client 2.5.0
Changelog: Add recipe mender-artifact 3.5.0
* Revert "Temporarily down-prioritize mender-binary-delta 1.2.0 in version sel."
This reverts commit 446dcc1ba224edf6e9dbc2fcf58ed1c0b5953a80.

dunfell: Mender 2.6.0 release

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.2.bb

Changelog: Add mender-artifact 3.4.1 recipe.
Changelog: Add mender-client 2.3.2 and 2.4.2 recipes.
Forward ported from dunfell, with additional tweaks to fit master:
* DISTRO_FEATURES -> MENDER_FEATURES

Add recipes for Mender 2.4.2 and 2.5.1.

---

meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install.inc
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install_%.bbappend

Fix Mender installation from a USB stick (hddimg) on machines with
BIOS by using the same installation script as for EFI.
Changelog: Fix Mender installation from a USB stick for BIOS
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Thank you!

initramfs-module-install_%.bbappend: Fix Mender

---

meta-mender-core/recipes-mender/mender-connect/mender-connect.inc

mender-connect: Correct ShellCommand key in config file

---

meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb

The mender_configure_autorev_if_git_version logic is only applicable
once we have other recipes to chose from. As it stands (only git recipe)
we should always build latest.

mender-configure git: Use always AUTOREV

---

tests/acceptance/requirements_py3.txt

And set it to the previous to last version, not introducing Rust
dependency. We'll update it in a different PR.

[requirements_py3.txt] Add cryptography

---

meta-mender-core/recipes-mender/mender-connect/mender-connect.inc

This parameter is not required, as the ServerURL is retrieved from the
mender client via D-Bus API.

mender-connect.conf: Remove unnecessary field ServerURL

---

meta-mender-core/recipes-mender/mender-configure/mender-configure.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-demo/recipes-core/packagegroups/packagegroup-core-boot.bbappend
meta-mender-demo/recipes-mender/mender-configure/mender-configure_%.bbappend

Changelog: Add mender-configure-scripts package, which provides
timezone configuration out of the box.
Changelog: Add mender-configure-demo package, which provides led
manipulation on Raspberry Pi devices, for demo purposes.
Changelog: If the `mender-systemd` class is set (the default),
mender-configure now provides a service file for systemd which will
automatically apply the stored configuration on startup.

m-configure: Adapt to new configuration scripts and systemd integration.

---

meta-mender-core/classes/mender-helpers.bbclass

All devices end in digits, and always have non-digit preceding those
digits, so use that to match instead of individual names.

Make device matching independent of device prefix.

---

meta-mender-core/recipes-devtools/dosfstools/dosfstools_4.2.bb

This is due to an error in older versions, which can leave the Vfat boot
partitions bricked.
See https://tracker.mender.io/browse/MEN-4497 for more information.

MEN-4497: Include a recipe for building dosfstools 4.2

---

meta-mender-core/classes/mender-setup-grub.inc

Use stronger `EFI_PROVIDER` assignment if related classes are set.
Since a default has already been set in some layers, and `?=`
assignments work in a first-one-counts fashion, our values do not
propogate if we use `?=`.
The original motivation and discussion for this fix is here:
https://hub.mender.io/t/simple-configuration-dunfell/2991/28

Fix `EFI_PROVIDER` being set incorrectly when using certain layers.

---

tests/acceptance/commercial/test_delta_update_module.py

To version 2.5.0: latest mender-binary-delta 1.2.0 requires
mender-artifact 3.5.0, which corresponds to mender 2.5.0.
(cherry picked from commit d2edbd4be2e0e7a8a5dcee0c5c4f074695540333)

[test_delta_update_module::perform_update] Set min_mender_version

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc

grub-efi has cleanconfigs added as such:
addtask cleanconfigs after do_sign do_chownboot before deploy do_package
but chownboot was being ordered *after* deploy. cleanconfigs deleting grub.cfg after deploy was causing psuedo to freakout and abort.
cleanconfigs should be sandwiched inbetween do_sign and do_deploy.
grub-mender-grubenv now explicitly adds do_chownboot before do_deploy
Signed-off-by: corey cothrum <contact@coreycothrum.com>
Thank you!

fix grub chownboot task ordering

---

meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb

This reverts commit 346f222c25f3e8f696d3f4187eb63be8c32725e6.

Revert "mender-configure git: Use always AUTOREV"

---

tests/acceptance/test_build.py

Instead of 2.6.0. It seems like it was a confusion wrt Mender (product)
and mender (client) version.
Amends commit 62efe5017e2d3cdf9d29f2f68779b9f6df4daf59.

[test_build] Mark min version 2.5.0 for test_certificate_split

---

tests/acceptance/requirements_deb.txt

This reverts commit fcabd7d771abf72621a4ce9e55cd54246ce3736f.

Revert "MEN-4106: add rpm to the deb requirements to run acceptance tests"

---

.gitlab-ci.yml
LICENSE
LIC_FILES_CHKSUM.sha256
meta-mender-qemu/scripts/docker/ext4_manipulator.py
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/conftest.py
tests/acceptance/test_build.py
tests/acceptance/test_dbus.py
tests/acceptance/test_ubimg.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py

Fix copyright statements and add CI license checks
To bring the repo to Mender standards.
Namely:
* Include GitLab template to check license in CI
* Move COPYING to LICENSE and update year
* Add license checksums file
* Add Copyright and License in some missing files
* Update Copyright year in some test files

Fix copyright statements and add CI license checks

---

tests/meta-mender-ci/recipes-testing/mender-mock-server/mender-mock-server_1.0.bb

After commit 457f0d2, which updated the copyright year.

Update license checksum for mender-mock-server

---

.gitlab-ci.yml

This I came across while working on the QA-315 task and the initial motivation to also use the `generate_client_publish_job` script. While that was scrapped to not stretch the task scope even further, I thought it would be worthwhile to include these smaller changes.
working triggering pipeline: https://gitlab.com/Northern.tech/Mender/meta-mender/-/pipelines/315052607
triggered pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/315058043

slight mender-qa trigger optimization

---

.gitlab-ci.yml
LICENSE
LIC_FILES_CHKSUM.sha256
meta-mender-core/recipes-mender/mender-configure/mender-configure.inc
meta-mender-demo/conf/layer.conf
meta-mender-qemu/scripts/docker/ext4_manipulator.py
meta-mender-qemu/scripts/docker/setup-mender-configuration.py
tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/conftest.py
tests/acceptance/mock_server.py
tests/acceptance/requirements_py3.txt
tests/acceptance/test_build.py
tests/acceptance/test_dbus.py
tests/acceptance/test_ubimg.py
tests/acceptance/test_update_control.py
tests/meta-mender-ci/conf/layer.conf
tests/meta-mender-ci/recipes-testing/logger-update-module/logger-update-module.bb
tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/mender-mock-server_1.0.bb

`mender-mock-server.py` has to be substantially extended for the calls
to work correctly. We have to consume the body of requests for
subsequent calls to work, and we need to be able to handle chunked
bodies. We also make it possible to schedule a deployment with it.
In addition we add a logger-update-module which we can use to track
exactly which states the Update Module is going through.

MEN-4550: Add acceptance test for DBus Update Control endpoint.

---

tests/acceptance/mock_server.py
tests/acceptance/test_update_control.py

Implementation at https://github.com/mendersoftware/mender/pull/790
Already approved at https://github.com/mendersoftware/meta-mender/pull/1385

MEN-4562: Extend test_update_control to verify deployment maps clean-up

---

meta-mender-commercial/recipes-extended/images/mender-monitor-image-full-cmdline.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor.inc
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb

* MEN-4712: meta-mender-commercial: Add monitor-client git recipe
* MEN-4712: Add new image monitor-image-full-cmdline for internal testing
`Changelog: Title` in both

MEN-4712: monitor-client yocto integration (internal flow)

---

tests/acceptance/mock_server.py

This will make the tests take longer, but will result in fewer spurious errors.

Bump the timeout for the acceptance mock-server

---

tests/acceptance/test_dbus.py
tests/acceptance/test_update_control.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py

* test_update_control.py: Clean up Mender state between test cases
Using the helper from mender-images, inspired by the same clean-up done
for test_dbus.py
Update also the git submodule at the same time
* mender-mock-server.py: Support for multiple chunks chunked transfer
Print the mock server logs on test failures too.
Used Mozilla dev docs for reference. See:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#chun
ked_encoding

Robustness improvements for test_update_control.py

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor.inc

MEN-4737 Monitoring wrapper alignment
Goes with https://github.com/mendersoftware/monitor-client/pull/17
* include service file
* add a correct link to the mender-monitord
ChangeLog:title

MEN-4737 Monitoring wrapper alignment

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.5.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.5.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.6.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.2.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.1.1.bb

Changelog: Add mender-artifact-3.5.2 recipe.
Changelog: Add mender-client-2.5.2 recipe.
Changelog: Add mender-client-2.6.1 recipe.
Changelog: Add mender-connect-1.0.2 recipe.
Changelog: Add mender-connect-1.1.1 recipe.

Add recipes for Mender 2.6.2 and 2.7.1.

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-qemu/recipes-mender/mender-client/mender-client_git.bbappend
tests/acceptance/test_build.py

MEN-4811: Conditionally install D-Bus interface files
The interface files, shipped in mender-client-dev package, shall be
present only when PACKAGECONFIG contains "dbus".
Fixed also how the test was getting `deploy_dir_rpm`. If obtained from
bitbake variables, the dir will point to the base build dir (and not the
prepared one for this test!).
Changelog: Fix: mender-client-dev package contains D-Bus interface files
only when "dbus" is enabled in PACKAGECONFIG.
In addition:
* meta-mender-qemu: Remove mender-client_git.bbappend
* Testing https://github.com/mendersoftware/mender-image-tests/pull/55 (technically unrelated, though)

MEN-4811: Conditionally install D-Bus interface files

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor.inc
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb
tests/acceptance/commercial/test_monitor_addon.py

* Add version check in mender-monitor.inc
* Add logic to accept build tags in mender-monitor_git.bb
* Unify `S` in git and inc recipe: both will use the tarball
* Add test test_monitor_addon.py to check contents

MEN-4807: mender-monitor integration (external flow)

---

meta-mender-core/classes/grub-mender-grubenv.bbclass
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_git.bb
meta-mender-core/recipes-mender/mender-client/files/mender-client-set-systemd-machine-id.sh
tests/acceptance/commercial/test_delta_update_module.py

Changelog: grub-mender-grubenv: User space tools, "fw_printenv" and
"fw_setenv" have been renamed to "grub-mender-grubenv-print" and
"grub-mender-grubenv-set", respectively. This has been done in order
to avoid conflict with U-Boot's user space tools, which have the same
names.

Upgrade to grub-mender-grubenv tools with new names.

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb

This will force yocto to rebuild from source every time that the
filename of the tarball changes.
Now the PV for the git recipe will be master-git${SRCREV}
This change aligns this recipe with other Mender components that are
build from source, though in this case SRCREV is extracted from the
filename and not from an actual Git repository.

mender-monitor_git: define unique PV based on SRCREV

---

tests/meta-mender-ci/recipes-mender/mender-monitor/mender-monitor_%.bbappend

Aligning it with the other Mender components, see commit f3b44b9.

meta-mender-ci: Support MENDER_CI_LOGLEVEL for mender-monitor

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb

Which it is when not specifically set up to build the component.

monitor: Fix parse error when SRC_URI is empty.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.3.0.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_1.0.0.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.6.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.1.0.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_1.0.2.bb

Porting #1476 to master.
Port to master: remove DEFAULT_PREFERENCE = "-1" for mender-client
recipe.

master: Release Mender 3.1.0

---

meta-mender-core/recipes-bsp/grub/mender-grub-efi-impl.inc

meta-secure-core defines `password.inc` which triggers an error if I want to use secure boot:
```
meta-secure-core defines password.inc which triggers an error:
Path ./package/boot/efi/EFI/BOOT/password.inc.p7b is owned by uid 1000,
gid 1000, which doesn't match any user/group on target. This may be due
to host contamination.
```
Removing `password.inc` file fixes this.
Please, review. Thanks.

Fix FTBFS due to host contamination with secure boot enabled [master]

---

meta-mender-core/recipes-bsp/grub/mender-grub-efi-impl.inc

meta-secure-core defines password.inc which triggers an error:
Path ./package/boot/efi/EFI/BOOT/password.inc.p7b is owned by uid 1000,
gid 1000, which doesn't match any user/group on target. This may be due
to host contamination.
Changelog: Fix FTBFS due to host contamination with secure boot enabled
Signed-off-by: Peter Hatina <peter@hatina.eu>
(cherry picked from commit 490aa4120961316d201b2878fac1f8ac07dcbf85)

Fix FTBFS due to host contamination with secure boot enabled

---

meta-mender-core/classes/mender-part-images.bbclass

Original code by: Ehson Hussain <ehsonhussain@gmail.com>

Avoid populating rootfs partition B to save space when compressing.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.inc

Changelog: Fix installation when cross-compiling mender-artifact
Signed-off-by: Clément Péron <peron.clem@gmail.com>

mender-artifact: fix installation when cross-compiling

---

tests/acceptance/test_dbus.py

In the context of MEN-5216, the D-Bus APIs shall return http://localhost
URL and not the Mender backend one.

MEN-5216: test_dbus.py: Extend tests to verify local proxy URL

---

meta-mender-core/classes/mender-image-systemd-boot.bbclass
meta-mender-core/classes/mender-maybe-setup.bbclass
meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-setup-grub.inc
meta-mender-core/classes/mender-setup-image.inc
meta-mender-core/classes/mender-setup-systemd-boot.inc
meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-bsp/systemd-mender-config/files/ab_setup.py
meta-mender-core/recipes-bsp/systemd-mender-config/systemd-mender-config.bb
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install.inc
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install_%.bbappend
meta-mender-core/recipes-core/meta/wic-tools.bbappend
meta-mender-core/recipes-core/systemd/files/systemd-boot-slotconfig.patch
meta-mender-core/recipes-core/systemd/systemd-boot_%.bbappend

This PR replaces #1474, which contained our first draft based on `zeus`. We have rebased to `master` and verified that everything continues to work. In addition to almost all of the changes requested in the original PR, I tossed in a couple of `repo` manifests for cloning the repositories for testing purposes. Let me know what further issues need to be addressed.
The biggest outstanding issue is the question of `meta-intel` integration. Right now, I believe that dependency has been isolated to `mender-image-systemd-boot.bbclass`, and that could be replaced with a new implementation. Ideally, these (and other) implementations could co-exist behind an abstraction, at which point I feel compelled to ask whether this branch provides sufficient proof-of-concept to allow it to be merged as-is. …

add systemd-boot support

---

meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb

Through adding the RDEPENDS (>= 3.2) for the mender-client in mender-connect,
older release branches cannot build using the git-recipe.
This fix is simply adding a function for selecting the minimal required version
for release branches in git recipes through returning:
2.5 when version <= 1.2.x
3.2 otherwise

fix: Mender-connect RDEPENDS set dynamically for release branches

---

tests/acceptance/mocks/mock_dbus_server.py
tests/acceptance/mocks/mock_websocket_server.py
tests/acceptance/test_dbus.py
tests/acceptance/test_mender-connect.py
tests/acceptance/test_update_control.py
tests/build-conf/beagleboneblack/bblayers.conf
tests/build-conf/qemux86-64-bios-grub-gpt/bblayers.conf
tests/build-conf/qemux86-64-bios-grub/bblayers.conf
tests/build-conf/qemux86-64-uefi-grub/bblayers.conf
tests/build-conf/raspberrypi3/bblayers.conf
tests/build-conf/raspberrypi4/bblayers.conf
tests/build-conf/vexpress-qemu-flash/bblayers.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/bblayers.conf
tests/build-conf/vexpress-qemu/bblayers.conf
tests/meta-mender-ci/conf/layer.conf
tests/meta-mender-ci/recipes-devtools/python/python3-websockets_%.bbappend

So that we can verify re-connection cases.
Two simple mocks have been developed:
* mock_dbus_server.py to mock D-Bus API and have a way from the test to
set the parameters and/or trigger the signal
* mock_websocket_server.py just accepts any websocket connection
meta-mender-ci has been updated to install the dependencies and increase
the image size.

MEN-5290: Acceptance tests for mender-connect

---

meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb

Through adding the RDEPENDS (>= 3.2) for the mender-client in mender-connect,
older release branches cannot build using the git-recipe.
This fix is simply adding a function for selecting the minimal required version
for release branches in git recipes through returning:
2.5 when version <= 1.2.x
3.2 otherwise
(cherry picked from commit fcced37a590714286e2e97d93e92793963a1f8ba)
Thank you!

[Cherry dunfell] rdepends release branch fix

---

tests/acceptance/mock_server.py
tests/acceptance/test_update_control.py

The client now uses the shortest interval among
`UpdatePollIntervalSeconds` and
`UpdateControlMapExpirationTimeSeconds` when deciding how long to wait
before re-querying the server for an Update Control Map. So we can no
longer use a quick update check time together with a slow Update
Control Map time. Instead, use the same time for both, and use the
`check-update` flag to force a quick update check at the points where
we deploy.

tests: Adapt to new polling policy for Update Control Maps in the client.

---

meta-mender-core/classes/mender-part-images.bbclass

Changelog: Fix error message `ERROR: It's not possible to create empty
squashfs partition 'None'` when using "squashfs" filesystem type.

MEN-5285: Avoid empty partitions for squashfs. Doesn't support them.

---

tests/acceptance/mock_server.py
tests/acceptance/test_update_control.py

The client now uses the shortest interval among
`UpdatePollIntervalSeconds` and
`UpdateControlMapExpirationTimeSeconds` when deciding how long to wait
before re-querying the server for an Update Control Map. So we can no
longer use a quick update check time together with a slow Update
Control Map time. Instead, use the same time for both, and use the
`check-update` flag to force a quick update check at the points where
we deploy.
(cherry picked from commit dccf39a1085111a7599f9941ffa34c9d663bf244)

[dunfell] tests: Adapt to new polling policy for Update Control Maps in the client.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb

When using `PREFERRED_VERSION_mender-client` instead of
`PREFERRED_VERSION_pn-mender-client`, the recipe doesn't correctly
pick up the branch name, causing checksum verification to fail. The
former is what is documented in the Yocto manual, so let's make sure
we support that.

Fix incorrect checksum detection on version branches.

---

meta-mender-core/classes/mender-helpers.bbclass

I get pseudo/abort inode mismatch errors on `LockDown.efi` when doing
back-to-back builds. The first build works fine. Building again (without cleaning and without changes)
fails.
I'm using the latest versions of dunfell.
`pseudo.log`:
```
path mismatch [2 links]: ino 1313785
db '/production-image/1.0-r0/rootfs/boot/efi/EFI/BOOT/LockDown.efi'
req '/production-image/1.0-r0/bootfs.image_uefiimg/EFI/BOOT/LockDown.efi'. 
```
Adding `PSEUDO_DSIABLE=1` to the rm/cleanup in
mender_merge_bootfs_and_image_boot_files resolves this issue, but I'm not 100% sure if this is the real fix
or just patching the symptoms.
I've looked [meta-efi-secure-boot](https://github.com/jiazhang0/meta-secure-core/tree/master/meta-efi-secure-boot/recipes-bsp/efitools) and don't see anything wrong/weird with …

prevent pseudo inode mismatch w/ efi-secure-boot

---

meta-mender-demo/mender-commercial/mender-monitor/mender-monitor_%.bbappend

The examples only exist from mender-monitor 1.1.x onwards, so we need
some special handling for older versions in the bbappend.

meta-mender-demo: mender-monitor bbappend conditional to the version

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_1.0.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.3.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.2.1.bb

Cherry-pick the relevant recipes from bugfix releases Mender 3.1.1, Mender 3.0.2 and Mender 2.6.4

master: bugfix releases Mender 3.1.1, Mender 3.0.2 and Mender 2.6.4

---

meta-mender-commercial/classes/mender-closed-source-utils.bbclass
meta-mender-commercial/recipes-extended/images/mender-gateway-image-full-cmdline.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway.inc
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_git.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb
tests/acceptance/commercial/test_mender_gateway.py
tests/meta-mender-ci/conf/layer.conf

Adds a closed source Yocto recipe for mender-gateway. Only the git
recipe is included in this commit. The recipe takes a tarball containing
the pre-compiled binaries and support files and just installs them on
the target.
A piece of code from mender-monitor has been refactored into a common
class for reuse in all closed source recipes that define SRCREV from the
tarball filename.
Acceptance test added accordingly.
Changelog: Add recipe for mender-gateway_git
Changelog: Add testing image mender-gateway-image-full-cmdline

MEN-5300: add a recipe for mender-gateway

---

meta-mender-qemu/docker/qemux86-64/Dockerfile
meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py

Modified setup-mender-configuration.py to support injecting the conf
file for mender-gateway and opened the 8080 port on QEMU for the gateway
to serve.

mender-qemu support for mender-gateway requirements

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway.inc

Two fixes:
* The source file was incorrect (use S instead of WORKDIR)
* The string "mender-gateway <PV>" is not present on the go binary, look
look for only the version instead.

mender-gateway: Fix do_version_check

---

meta-mender-core/recipes-core/lsb-ld/lsb-ld.bb

Fix do_install for x86-64 to avoid issues with ./lib64/*.a and
missing arent directory structure during do_package on multilib
systems.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Thank you!

lsb-ld: Avoid lib64/*.a issues on multilib systems

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/conf/layer.conf
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-helpers.inc
meta-mender-qemu/conf/layer.conf
meta-mender-raspberrypi-demo/conf/layer.conf
meta-mender-raspberrypi/conf/layer.conf
meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi-rt_%.bbappend

These fixes bring the layer into parseable state on the honister release, however in a slightly degraded state. Especially the `mender-client_git` recipe is being masked out until the syntax in the involved.
Thank you!

fixes for honister

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway.inc
meta-mender-demo/conf/layer.conf
meta-mender-demo/mender-commercial/images/mender-gateway-image-full-cmdline.bbappend
meta-mender-demo/mender-commercial/mender-gateway/mender-gateway_%.bbappend
meta-mender-qemu/scripts/docker/entrypoint.sh

Main commit:
MEN-5475: meta-mender-demo: Add demo functionality for mender-gateway
Requires the user to extend SRC_URI of mender-gateway with the location
of the examples tarball:
```
SRC_URI_pn-mender-gateway_append = " file:///<download-path>/mender-gateway-examples-1.0.0.tar"
```
Download the tarball from https://docs.mender.io/downloads

MEN-5475: meta-mender-demo: Add demo functionality for mender-gateway

---

meta-mender-core/classes/mender-setup.bbclass

Used script 'scripts/contrib/convert-variable-renames.py' from
openembedded-core meta layer to convert new override syntax.
Refer bitbake, commit efaafc9ec2e8c0475e3fb27e877a1c0a5532a0e5.
Signed-off-by: Preeti Sachan <preeti.sachan@intel.com>

Rename bb variable

---

meta-mender-core/recipes-core/systemd/systemd-boot_%.bbappend
meta-mender-core/recipes-devtools/e2fsprogs/patches/0001-Do-not-use-metadata_csum-feature-on-ext4-by-default.patch
meta-mender-qemu/conf/layer.conf
meta-mender-raspberrypi-demo/conf/layer.conf
meta-mender-raspberrypi/conf/layer.conf

Hi,
just a quick patch refresh for e2fsprog and mark the layer compatible with hardknott

Refresh e2fsprog patch and mark layer compatible with hardknott

---

meta-mender-core/classes/mender-dataimg.bbclass

Add a new feature to support F2FS (Flash-Friendly File System) for
the data partition with variable MENDER_DATA_PART_FSTYPE_TO_GEN.
Changelog: Support F2FS for the data partition
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Add a new feature to support F2FS (Flash-Friendly File System) for the data partition using variable `MENDER_DATA_PART_FSTYPE_TO_GEN`. The workflow is the same as for the already supported `btrfs`, `ext4`, etc.

dataimg: Add F2FS support

---

meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled_2.04.bb

This reflects the licence identifier change in upstream
commit b0130fcf91daee0d905af755302fabe608da141c
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
Thank you!

grub-efi-precompiled: fix license identifier

---

meta-mender-qemu/docker/build-docker
meta-mender-qemu/docker/qemux86-64/Dockerfile
meta-mender-qemu/scripts/docker/extract_fs

Those go together:
* https://github.com/mendersoftware/mender-qa/pull/580
build and prepare so called clean images and pass them to build-docker
to embed in the images we later /extract_fs in integration tests
* https://github.com/mendersoftware/meta-mender/pull/1663
support for a new flag that allows to specify an extra image
to embed in the container
* https://github.com/mendersoftware/integration/pull/1983
use the clean images in the tests and test for artifact_info
in a explicit manner
ChangeLog: none

QA-387 Embed a clean image

---

.github/PULL_REQUEST_TEMPLATE.md

QA-365: Add the conventional commit spec to the PR template

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
tests/acceptance/test_build.py
tests/meta-mender-ci/recipes-testing/mender-coverage-client/mender-client_%.bbappend

```
commit f6c1a8cf55c34898909ff7a6ed577f0dc50920f0
Date:   Mon May 23 21:00:30 2022
test: nodbus: Clean the mender-client between builds.
We need it because tag changes ("nodbus") are not picked up without
cleaning first.
commit 8b4eb998b9552203792de3ba9b66c027df64a64e
Date:   Mon May 23 16:46:35 2022
fix: Force building in separate build directory, even with `externalsrc`.
The problem with building in `${S}` is that files remain there after
a build, due to bad interoperability between the `externalsrc` and
`go` classes, the `clean` target does not clean this up. Therefore,
force the creation of a separate build directory …
```

Fixes for Pseudo abort issue

---

meta-mender-qemu/docker/qemux86-64/Dockerfile

- since the python version installed was unversioned until now, the default target would be the latest stable
- to both prevent unintended versioning issues & speed up the build, the base image is switched to python
- also removed another image layer by avoiding the apk cache
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

chore: moved qemu docker image to python base image.

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-resize-data-part.sh.in
meta-mender-core/recipes-mender/mender-client/mender-client.inc

This PR is split into two parts:
* **Simplify mender-client-resize-data-part by figuring out the storage device from `MENDER_DATA_PART`**
This way, we don't need to populate the script with a valid value for `MENDER_STORAGE_DEVICE` anymore. That variable doesn't exist in a "partuuid" setup and is already auto-derived in a similar way in a "partlabel" setup.
* **Make mender-client-resize-data-part compatible with "partuuid" setups**
This commit derives the expected value for `MENDER_DATA_PART` from the PARTUUID in "partuuid" setups, in a similar way as it's already done for "partlabel" setups.
I have backported this fix to dunfell (which only supports "partuuid" but not "partlabel") in https://github.com/enlyze/meta-mender/tree/dunfell-mender-client-resize-data-partuuid and successfully …

Simplify mender-client-resize-data-part and make it compatible with "partuuid" setups

---

tests/acceptance/test_dbus.py

see: https://github.com/mendersoftware/mender/pull/1001
Ticket: None

test: Client now returns loopback IP address, instead of localhost.

---

.gitmodules
tests/acceptance/test_dbus.py
tests/build-conf/beagleboneblack/local.conf
tests/build-conf/qemux86-64-bios-grub-gpt/local.conf
tests/build-conf/qemux86-64-bios-grub/local.conf
tests/build-conf/qemux86-64-uefi-grub/local.conf
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/local.conf
tests/build-conf/vexpress-qemu/local.conf
tests/meta-mender-ci/conf/layer.conf

Just cherry-picks, but I did fork the mender-image-tests repository, see https://github.com/mendersoftware/mender-image-tests/pull/68.

Dunfell: Changes to support interoperability with kirkstone.

---

tests/acceptance/requirements_deb.txt

Remove unnecessary python2-dev package: there's no python 2 in ubuntu:18:04
```
oot@a2f304a7fa54:/# ls /usr/bin/python*
python3            python3-config     python3.6          python3.6-config   python3.6m         python3.6m-config  python3m           python3m-config 
```
Docker image cannot be built because of `E: Unable to locate package python2-dev` error message.
Failing job: https://gitlab.com/Northern.tech/Mender/mender-test-containers/-/jobs/2564428900#L926
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

chore: remove unnecessary python2-dev package

---

tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf

fix: adjust package rename of bootfiles to upstream in testing
Changelog:  None
Ticket: MEN5689
This adjusts the test scripts to the already existing adjustment of the payload scripts to upstream.

MEN5689: fix bootfiles rename to match upstream

---

meta-mender-core/recipes-mender/mender-client/files/0001-fix-Upgrade-openssl-dependency-to-fix-cast-error-in-.patch
meta-mender-core/recipes-mender/mender-client/mender-client_3.3.0.bb

Carry the OpenSSL-binding selection patch in the layer until 3.3.1 is released which will include it.

MEN-5700: patch mender client 3.3.0 for kirkstone

---

meta-mender-commercial/conf/layer.conf
meta-mender-core/conf/layer.conf
meta-mender-demo/conf/layer.conf
meta-mender-qemu/conf/layer.conf
meta-mender-raspberrypi-demo/conf/layer.conf
meta-mender-raspberrypi/conf/layer.conf

This restricts to the usage of the layer to the
kirkstone release only, in order to facilitate
the LTS scheme.
Ticket: MEN-5681
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>

feat: set LAYERCOMPAT to kirkstone only

---

tests/acceptance/test_uboot_automation.py

Fix spurious errors when reading binary data from the file:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1435: invalid start byte
Ticket: None

test: improve test_uboot_automation.py

---

tests/acceptance/test_uboot_automation.py

This only affects the error path, which fails due to the content being
bytes. Switch to latin_1 coding instead, which accepts the entire
0-255 range of byte characters.

test: Use latin_1 coding so we can keep using str when printing logs.

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-resize-data-part.sh.in

Modifying the partition table in any way may trigger udev at some point.
We don't want to continue right while udev is recreating /dev/disk symlinks.
Instead, we want this to happen deterministically now and be done when the script is done.
Ticket: MEN-5717
Signed-off-by: Colin Finck <c.finck@enlyze.com>

fix: Race condition in mender-client-resize-data-part (master)

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-resize-data-part.sh.in

Modifying the partition table in any way may trigger udev at some point.
We don't want to continue right while udev is recreating /dev/disk symlinks.
Instead, we want this to happen deterministically now and be done when the script is done.
Ticket: MEN-5717
Signed-off-by: Colin Finck <c.finck@enlyze.com>
(cherry picked from commit 6939aaae4f423c5b2aac58c88816972953847822)

fix: Race condition in mender-client-resize-data-part (dunfell)

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc

Ticket: MEN-4980
Changelog: The `mender-binary-delta` recipe now takes a tarball as
input instead of a folder containing unpacked files. Remove the line
starting with `FILESEXTRAPATHS`, and instead insert this line:
```
SRC_URI:pn-mender-binary-delta = "file://${HOME}/mender-binary-delta-1.4.0.tar.xz"
```
where the path points to the downloaded tarball.
BREAKING CHANGE

feat:mender-binary-delta now takes tarball as input instead of folder.

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc

If a variable in do_configure task changed do_configure task is triggered
again but not do_compile.This patch clean the build folder and triggered
do_compile task again to get a fresh grub.cfg file with the fresh generated
data from do_configure task.
Signed-off-by: Sebastian Suesens <sebastian.suesens@baslerweb.com>
```
```
Thank you!

grub-mender-grubenv.inc: clean build folder in do_configure task

---

tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf

Gets the rid of:
```
WARNING: IMAGE_FSTYPES:remove += is not a recommended operator combination, please replace it.
```

chore: Correct syntax on build-conf files

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-data-dir.service

This adds a `Before` dependency on the mender-client service file in the service
which creates the `/data/mender` directory.
Just to insure proper ordering of events.
Changelog: Add a systemd After dependency on the `mender-client-data-dir`
service file.

fix: have the data dir created before the client runs

---

meta-mender-commercial/conf/layer.conf

This is to avoid altering the build just by adding the layer.
Ticket: None

fix: Make `read-only-rootfs` tweaks dependent on `mender-image` feature flag.

---

meta-mender-raspberrypi/recipes-mender/update-firmware-state-script/files/ArtifactInstall_Leave_50.in

Changelog: meta-mender-raspberrypi: update-firmware-state-script: Make
copies of firmware binaries safer. On VFAT file-systems `mv` is not
atomic, but still using it narrows the time window in which the files
could be corrupted.

perf(update-firmware-state-script) Improve robustness

---

meta-mender-raspberrypi/recipes-bsp/bootfiles/rpi-cmdline-mender.inc
meta-mender-raspberrypi/recipes-bsp/bootfiles/rpi-cmdline.bbappend
meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi-mender.inc
meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

fix: cmdline.txt generation in meta-mender-raspberrypi
The generation of cmdline.txt has been moved upstream to a new recipe,
so our bbappend was not being applied.
See:
https://github.com/agherzan/meta-raspberrypi/commit/8827040d9c218f68ae3ee6a5814929888ed61581
Ticket: MEN-5834
fix(rpi-cmdline-mender.inc): Fix cmdline.txt after generation
Due to an implementation detail, we cannot use the standard syntax for
appending, see inline comment.
Ticket: MEN-5834

MEN-5834: fix: cmdline.txt generation in meta-mender-raspberrypi

---

meta-mender-core/classes/mender-setup-image.inc

This commit is inspired the commit below from poky: https://git.yoctoproject.org/poky/commit/?id=f85a4a1462bc2105f7c62f2b09c1d092c7677ada
Although the code is different, it is applying the exact same type of fix, and therefore I'm also reusing (most of) their commit message below:
---
To exclude content from the rootfs, the prefunc makes a copy (using hardlinks if possible) of the rootfs directory and associated pseudo db, then removes files & directories as needed. However if these files and directories are removed using the python functions os.remove and shutil.rmtree, the copied pseudo db will not be updated correctly. For files copied from the original rootfs, if hardlinks were used successfully when copying the rootfs this should mean that the relevant inodes can't be reused and so …

fix: Update pseudo db when excluding content from rootfs

---

tests/build-conf/beagleboneblack/local.conf
tests/build-conf/qemux86-64-bios-grub-gpt/local.conf
tests/build-conf/qemux86-64-bios-grub/local.conf
tests/build-conf/qemux86-64-uefi-grub/local.conf
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/local.conf
tests/build-conf/vexpress-qemu/local.conf

At the time of writing, this appears to affect dunfell only, not kirkstone, although the reason for this is unclear.
Ticket: MEN-5857

chore: Work around bug in interaction between pseudo and pycache.

---

tests/meta-mender-ci/recipes-core/systemd-conf/files/journald.conf
tests/meta-mender-ci/recipes-core/systemd-conf/systemd-conf_%.bbappend

After a bit of digging, I discovered that when KVM is once again re-enabled in our acceptance test jobs, the client would run out of memory, as a result of the 'systemd-run' job filling up the `/run`, and hence the running memory of the QEMU instance.
The fix is to create a stricter journald config for our CI-layer.
The settings are pretty strict, but I don't necessarily see a big problem here.
With these settings a vacuum of the log is triggered at tighter intervals, so less logs are kept. But still plenty of MiB's available for log storage.
Ticket: QA-414

test(update_control): fix the issue with /run logs filling up mem

---

meta-mender-core/classes/grub-mender-grubenv.bbclass
meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled_2.04.bb

Ticket: ME-6
Changelog: Upgrade grub-mender-grubenv to include the XFS module in the default installation.

fix: bump the grub-mender-grubenv version

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.8.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.3.1.bb
tests/acceptance/test_build.py
tests/build-conf/beagleboneblack/local.conf
tests/build-conf/qemux86-64-bios-grub-gpt/local.conf
tests/build-conf/qemux86-64-bios-grub/local.conf
tests/build-conf/qemux86-64-uefi-grub/local.conf
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/local.conf
tests/build-conf/vexpress-qemu/local.conf

I wanted only to submit this dummy but annoying fix:
chore: Update commented out build conf settings with new separator
And ended up finding this one:
test: Update test_preferred_versions to new separator syntax
By the looks of it, EXTERNALSRC_ and PREFERRED_VERSION_ did not trigger
warnings or errors and this mistake went unnoticed. The test "passes"
because it just builds always the latest available recipe.

test: Update test_preferred_versions to new separator syntax

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-bootstrap-artifact.bbclass
tests/acceptance/test_build.py

And extend existing test to verify the new functionality.
Changelog: Mender Artifacts include now information about the installed Update Modules in the image. Specifically, the Artifacts `provide` two pair of keys for each module:
`rootfs-image.update-module.<UPDATE_MODULE>.version` and `rootfs-image.update-module.<UPDATE_MODULE>.mender_update_module`. This also applies to the bootstrap Artifact which gets installed on first boot.

MEN-5845: feat: Add information about supported update modules in mender Artifacts

---

tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/test_build.py

* chore(test_delta_update_module.py): Migrate from deprecated distutils
Clears `DeprecationWarning`. See:
https://peps.python.org/pep-0632/#migration-advice
* chore(test_build.py): Fix syntax with a literal
Clears `SyntaxWarning`: "is not" with a literal.

chore: Fix warnings

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb

@kacf related to https://github.com/mendersoftware/meta-mender/commit/b31ab892d6ccdbec7b880c73f0e2d795e9866e34
Switch to 'd.getVar()' style, since this now fails on kirkstone and later.
We can get it directly inside the function
Signed-off-by: Clément Péron <peron.clem@gmail.com>

properly get the SRCPV inside the function

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

This naming has changed upstream so make sure we use the right files.
Ticket: None
Signed-off-by: Drew Moseley <drew@moseleynet.net>
(cherry picked from commit e90da1144ff72a2f9bf176ed82b1bb991b2ddcad)

fix: udev: Rename blacklist to ignorelist.

---

tests/acceptance/test_mender-connect.py

This fixes the mender-connect spurious failure tests.
The issue turned out to be that the time is passed in between the host and the QEMU instance, and is being used as a single source of truth.
This created a window of opportunity in which the test would get the system time on the host, then pass it into the QEMU instance to use as a timestamp in `since=<time>` when filtering the logs with `journald`.
Hence, mender-connect would actually behave, but log the correct output in the window of time which arose in between the host time, and QEMU's time, and it was simple filtered out.
The fix is dead simple: Use the QEMU instance time as the single source of truth
Ticket: QA-483

test(test-connect): Fix the mender-connect spurious failure tests

---

meta-mender-core/recipes-mender/mender-client/mender-client_3.3.1.bb

Ticket: MEN-6122
Changelog: Fix the regression in which Dunfell started providing the 3.3.x
client as the default. This was an unintentional change, and this
re-downprioritizes it, so that the `2.x` client is once again the default.

fix: Do not provide the mender-client 3.3.1 as the branch default

---

meta-mender-core/classes/grub-mender-grubenv.bbclass
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_git.bb

Changelog: grub-mender-grubenv: Add lock file to prevent data races when accessing boot environment concurrently.
Ticket: None

fix: Update to grub-mender-grubenv with lock fix.

---

LICENSE
LIC_FILES_CHKSUM.sha256
meta-mender-commercial/recipes-extended/images/mender-image-full-cmdline-rofs-commercial.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_git.bb
meta-mender-core/classes/grub-mender-grubenv.bbclass
meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-bootstrap-artifact.bbclass
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_git.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-qemu/scripts/mender-qemu
tests/acceptance/.gitignore
tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/mock_server.py
tests/acceptance/requirements_py3.txt
tests/acceptance/test_build.py
tests/acceptance/test_dbus.py
tests/acceptance/test_inventory.py
tests/acceptance/test_mender-connect.py
tests/acceptance/test_snapshot.py
tests/acceptance/test_uboot_automation.py
tests/acceptance/test_update_control.py

This is based on #1803.
This cherry-picks the commits needed to introduce parallel acceptance testing on kirkstone, but I also cherry-picked some surrounding commits that seemed sensible to include.

Kirkstone parallel testing

---

tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/commercial/test_mender_gateway.py
tests/acceptance/commercial/test_monitor_addon.py
tests/acceptance/test_bootstrap_artifact.py
tests/acceptance/test_build.py
tests/acceptance/test_dbus.py
tests/acceptance/test_inventory.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_mender-connect.py
tests/acceptance/test_snapshot.py
tests/acceptance/test_update_control.py

Update image-tests submodule to bring the split functionality.
Mark all tests accordingly. Along the way, minor tests doc improvements
have been made.

QA-487: test: Split out cross-platform tests

---

meta-mender-core/recipes-bsp/grub/mender-grub-efi-impl.inc

We have a device that uses both "meta-mender" and "meta-efi-secure-boot". We have been having problems with [pseudo aborting](https://wiki.yoctoproject.org/wiki/Pseudo_Abort) during the "do_package" task of the "grub-efi" recipe. The pseudo log file contains entries similar to the following:
```
path mismatch [2 links]: ino 156950073 db '/build/justin.verble/pc/tmp/work/corei7-64-poky-linux/grub-efi/2.04-r0/image/boot/efi/EFI/BOOT/grub.cfg' req '/build/justin.verble/pc/tmp/work/corei7-64-poky-linux/grub-efi/2.04-r0/packages-split/grub-efi-dbg/usr'.
```
Resource files are installed by the appended "grub-efi" recipe in "meta-efi-secure-boot". This happens during the "do_install" task which uses pseudo by default. The appended "grub-efi" recipe in "meta-mender" removes these files without …

fix: Remove grub.efi resource files using pseudo.

---

tests/acceptance/test_build.py

Depending on the `mender-client` version, this artifact might not be found in the build.

test: Conditionally verify the bootstrap Artifact

---

meta-mender-core/recipes-kernel/linux/boot-partition-devicetree.bb

GPL-2.0 is no longer a valid license, avoid a warning by using GPL-2.0-only (which is the same as the kernel itself).
Changelog: boot-partition-devicetree use proper SPDX License GPL-2.0-only

fix: boot-partition-devicetree QA license warning

---

meta-mender-demo/mender-commercial/mender-gateway/mender-gateway_%.bbappend

If you have meta-mender-demo enabled for other reasons than the gateway, the build will fail if you didn't get the examples tar. This makes it a warning not a hard build fail.
Ticket: None
Signed-off-by: Alan <alan.martinovic@northern.tech>
(cherry picked from commit e6c0f10394f89840555c479711e779e9cb3429af)

feat: Make the build succeed if gateway examples aren't present

---

meta-mender-core/classes/mender-part-images.bbclass

Tested with kirkstone release.
When building a gptimg I was seeing an error related to the partition type.
The context command is:
`ERROR: _exec_cmd: export PATH=....:$PATH;export BLK_DEFAULT_SECTOR_SIZE=512; sfdisk --part-type ......-20230409232256-gptimg/tmp.wic.ecrqtv27/mender-gptimg-202304092323-mmcblk0.direct 1 8300 returned '1' instead of 0
| output: sfdisk: ....-20230409232256-gptimg/tmp.wic.ecrqtv27/mender-gptimg-202304092323-mmcblk0.direct: partition 1: failed to set partition type`
I couldn't find any changes or reasoning for sfdisk why the shorthand format isn't supported, assuming it worked when this line was last touched.  I was able to resolve the error by replacing the shorthand 8300 with the full UUID or by removing this if/else block entirely.

Replace GPT partition type 8300 with the full UUID value

---

meta-mender-core/classes/mender-part-images.bbclass

Encountered an error with sfdisk where partition type 8300 created a "failed to set partition type" error.
Changelog: Replace gpt partition type 8300 with full UUID
Ticket: None
Signed-off-by: Chad Rockey <chadrockey@gmail.com>
(cherry picked from commit 161ce89264b46bd3422320d57e4a89f0a2e90a9e)

fix: Replace gpt partition type 8300 with full UUID

---

meta-mender-core/recipes-core/meta/wic-tools.bbappend

This avoids building grub-related packages when using u-boot, just like what was done for systemd-boot.  In some cases, these dependencies actually interfere with the expected use of u-boot, and this fixes those issues.
Ticket: None
Signed-off-by: Zachary T Welch <zach@aquabyte.ai>
(cherry picked from commit f958be043d148c6fba0f7467fc02a634478a50c0)

fix: wic-tools does not need grub when using uboot

---

meta-mender-core/recipes-mender/mender-configure/mender-configure.inc

Originally from Mender Hub:
https://hub.mender.io/t/mender-configure-files-installed-but-not-shipped/3289
Ticket: None

fix: mender-configure: Don't break if libdir is set to `lib64`.

---

meta-mender-qemu/scripts/docker/extract_fs

So that the script does not need to be run on a privileged container nor uses loopback devices from the host machine.

QA-512: chore: Alternative `extract_fs` script logic with no loopback dev

---

meta-mender-core/recipes-update-modules/mender-app-update-module/mender-app-update-module_git.bb
tests/acceptance/test_app_update_module.py

The app-updates Update Module provides an API for orchestrated application level updates, and currently two user implementation for docker-compose and k8s.
The recipe installs the Update Module and dependencies for deploying such docker-compose and k8s artifacts. The implementation is in shell script and therefore architecture agnostic.
Ticket: MEN-6084

feat: add recipe for the Application Update Module

---

meta-mender-core/classes/mender-bootimg.bbclass
meta-mender-core/classes/mender-dataimg.bbclass

coreutils 9.0 introduces a new behavior in the "install" tool. When used to install a sparse file, it now looks for holes and may insert new holes. Using "mv" instead of install ensures that images do not lose significant information.
This fix is beneficial to the use of bmaptool to write images to a device, especially if the image contains a FAT filesystem.
```
```
Please describe your …

fix: mv image files instead of install, to avoid corrupting the image.

---

meta-mender-demo/recipes-connectivity/qemu-connectivity-helper/files/qemu-connectivity-helper.service
meta-mender-demo/recipes-mender/mender-reboot-detector/files/mender-reboot-detector.service

Adds the new client service names to `Before` list for `mender-reboot-detector` and `qemu-connectivity-helper`.

chore: Update test systemd services with the new client names

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc

(cherry picked from commit 1b7ec65c64024a423868f98aa3814543225c9b1a)

chore(client): Remove/adapt last remaining `RDEPENDS:${PN}` references.

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
meta-mender-core/recipes-mender/mender-client/mender-client-go.inc

It should be `interfaces` according to:
* https://dbus.freedesktop.org/doc/dbus-api-design.html

fix: Amend D-Bus interface files path for the C++ client

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

It should be `interfaces` according to:
* https://dbus.freedesktop.org/doc/dbus-api-design.html
Changelog: Fix the install path for the D-Bus interface files shipped in `mender-client-dev` package. It was `$(datadir)/dbus-1/interface` but it should be `interfaces` instead.

fix: Amend D-Bus interface files path

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-core/recipes-mender/mender-flash/mender-flash_git.bb
meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot_git.bb

Following up from the copyright year update in the license files
See:
* https://github.com/mendersoftware/mender-artifact/pull/576
* https://github.com/mendersoftware/mender-configure-module/pull/105
* https://github.com/mendersoftware/mender-connect/pull/126
* https://github.com/mendersoftware/mender-flash/pull/10
* https://github.com/mendersoftware/mender-snapshot/pull/18

chore: Update licenses checksums for git recipes

---

meta-mender-core/recipes-mender/mender-client/mender_git.bb

This is to account for the 2024 license year update.

chore(license): Update the mender license checksum

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-client/mender_git.bb

The licenses of the C++ client was wrong, and the checksum for the Golang client when building with Git was also wrong. Fix both, and consolidate licenses in one file.
Ticket: None

fix(mender): Fix incorrect licenses and license checksums.

---

meta-mender-core/recipes-mender/mender-configure/mender-configure.inc

The mender-configure installation process now supports the prefix and systemd_unitdire directories being passed in. This is required for the ongoign usrmerge effort.
Ticket: None
```
```
Thank you!

fix: pass prefix and systemd_unitdir to mender-configure installation

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
meta-mender-core/recipes-mender/mender-client/mender-client-go.inc

No changelog, since we never tagged the broken version.
Ticket: None

fix: Fix naming mismatch for mender-grow-data.service.

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

For some reason `gitsm` has a different checkout location than `git`. It's probably related to how it interacts with the go class, but we don't need `gitsm` for the Golang client anyway, so just switch back to `git`.
Ticket: None

fix: Fix broken Git builds for mender-client < 4.0.

---

meta-mender-core/classes/mender-setup-image.inc

The IMAGE_FSTYPE "mender.bmap" is added by default if the MENDER_FEATURES flag "mender-image" is set, but is has no valid use case. Hence, it can be removed.
Ticket: None
```
```
Thank you!

fix: remove "mender.bmap" IMAGE_FSTYPE

---

meta-mender-core/classes/mender-maybe-setup.bbclass
meta-mender-core/classes/mender-setup.bbclass

We should use `MENDER_FEATURES` because this is the final result of calculating the features, otherwise we can miss feature toggles that have special handling.
This fixes an issue where `mender-update-install` was not added correctly, leading to boot issues on RPi.
No changelog for this, because it was never in a tagged release.
Ticket: MEN-7039

fix: Don't use `MENDER_FEATURES_ENABLE` variable directly.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.5.0.bb

fix: remove `_MENDER_FLASH_TOOL_DEFAULT` from mender-binary-delta 1.5.0

---

tests/meta-mender-ci/recipes-testing/mender-artifact-coverage/mender-artifact_%.bbappend

It was changed in commit 974cba76574458a56 in poky.
Ticket: QA-587

test: Fix missing backslash in `${B}` in more recent kirkstone branch.

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc

The files `mender-systemd-machine-id.service` and `mender-set-systemd-machine-id.sh` do not exist in the repo which leads to build errors when mender 4 is enabled on kirkstone. Instead the files are name  `mender-client-systemd-machine-id.service` and `mender-client-set-systemd-machine-id.sh`. This PR fixes the path of these file.

fix: path to mender-client-systemd-machine-id service/script

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

When building from git master, it is necessary to also fetch the vendored submodules. Switching the recipe to the gitsm:// fetcher fixes this process.
Ticket: None
```
```
Thank you!

fix: use gitsm:// fetcher for mender-client_git

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc

This is important when usrmerge is enabled, which changes the systemd install location.
Ticket: None

fix: Set correct systemd installation dir.

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor.inc

If the image is built with a busybox version of `df` Mender monitor will start giving errors for the disk usage case:
Setting a runtime dependency to coreutils provides a real version of df instead of a busybox one.
Ticket: None

fix: add coreutils as a runtime dependency for Mender monitor

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc

Amends commit: 5e31f7eb2789291c6a26e6670018e5062476c8aa
Ticket: None
Changelog: Fix autogeneration of `mender-binary-delta.conf` so that the user value for `MENDER_FLASH` is respected, instead of the previously wrongly hard-coded value of `mender-flash`. Without this fix `mender-binary-delta` won't still work on UBI file systems.

fix: Fix `mender-binary-delta` configuration

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc

The script to write a persistent systemd machine id
along with the correlating systemd service unit have
been renamed. Adjust the filenames in mender-client-cpp.inc
accordingly.
Ticket: None
```
```
Thank you!

fix: persistent machine id support files renamed

---

meta-mender-qemu/docker/qemux86-64/Dockerfile

Which, apparently, fixes the issue with scarthgap images not booting in QEMU in unprivileged Docker containers.

MEN-7447: Update Docker base image to latest Alpine

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc

Commit bca6bf7 included part of the required fixed.  This contains the rest. There may be others, but this allows me to build the C++ client.
Left as an exercise for the maintainers: enabling this features somewhere in the official test matrix, so this kind of breakage gets detected sooner. :grin:

[scarthgap] chase persistent machine id renames

---

meta-mender-core/classes/mender-maybe-setup.bbclass
meta-mender-core/classes/mender-part-images.bbclass

By default, the inactive partition of a generated image is empty to allow for more efficient compression.
As squashfs (a supported ARTIFACTIMG_FSTYPE) does not support empty filesystems, it already triggers implicit logic in the mender-part-images.bbclass to populate the inactive partition with the full filesystem.
This commit adds an explicit trigger through the MENDER_FEATURES mechanism using the "mender-prepopulate-inactive-partition" key.
The primary use case is to check the bootloader integrations (A/B switching, A/B update, A/B rollback) directly on the generated images without additional modifications or processing.
The majority of our …

feat: add mender-prepopulate-inactive-partition feature

---

tests/acceptance/test_build.py

Both attempts to fix have been problematic:
* https://github.com/mendersoftware/meta-mender/pull/2181#discussion_r1803013671
* https://github.com/mendersoftware/meta-mender/pull/2190
Disabling the test for the time being.

test: Skip unstable test while we work on the workaround

---

tests/acceptance/test_mender-connect.py

By printing the journal when the test fails

QA-768: Learn more about what is happening in `mender-connect` on failures

---

tests/acceptance/test_build.py

Besides moving the test to a separate class, this commit modifies the
following:
* Use a class scoped test build dir, that unlike the default one is not
shared across all tests in the same runner.
* Disable write to shared state cache to not modify anything (note that
the test can still read the cache via the `SSTATE_MIRRORS` setup).
* Replace the aggressive `cleanall` with `clean` - we still want to
clean the recipe for further rebuilds withing the same test build dir
* And enable the test \o/
The reordering of the code affects the ordering of the tests execution
in CI, but before this commit I made sure that even with the previous
ordering the fix is "good enough" to get a green pipeline.
Finally, if you still have energy to keep reading, see all the previous
attempts that we have done …

QA-784: Use a dedicated workspace for `test_preferred_versions`

---

meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled_2.04.bb

When the meta-mender stack is included but the distro is building without Mender (such as for testing), an error is raised. This is due to a variable being used, but never defined because some of the Mender conf isn't visited.
By setting the base default to "" it lets later code use the variable without all conf being processed.
While testing, I had the Mender layer included, but I was building without Mender to hunt down a U-boot issue with the Raspberry Pi 5. This change at least let me get stuck in U-boot.
In my local.conf, I have:
```
################################################################################ …
```

Fix building with Mender disabled

---

meta-mender-qemu/recipes-support/libp11/libp11_0.4.%.bbappend

The build of `libp11` has recently started failing on `do_patch`, due to a change in upstream introducing a patch.
It is not completely known why we needed it to be pin to an specific version, tag 0.4.9, at the time of integrating it. In the commit message it says "libp11 bumped to latest source revision (align with OpenSSL 1.1.1d)", but by the time of that commit (2020-08) upstream was already using a newer version (0.4.10 as per 2019-05). See:
* https://github.com/mendersoftware/meta-mender/commit/f39dc0aeb482798ae86502d342f1e598901b265f
* https://git.openembedded.org/meta-openembedded/commit/?id=e9ffb7c6c09b9a7ca52801fb27dd1a057d15f7c1
In any case this was introduced by `dunfell` times, with OpenSSL 1.1, and we should not be requiring such an old version of this library to keep testing …

ci: Fix `libp11` build by removing the pin on an old version

---

meta-mender-core/recipes-mender/mender-connect/mender-connect.inc
meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot.inc

This is a follow-up from 0b85500.
By switching to `go.bbclass` definitions for compile and install tasks, we have also switched from static linking (golang's default) to dynamic linking (by passing `-linkshared` to the go commands - see `go.bbclass` source code).
While using shared linkage on golang binaries have benefits (and presumably is preferred in Yocto), we didn't intend to change the linkage of Mender binaries in the commit mentioned above.
(Note that `mender-connect` is actually dynamically linked for other dependencies, but at least the runtime and stdlib shall be statically linked).

MEN-7275 (follow-up): Prefer static linkage for `mender-connect` and `mender-snapshot`

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_1.4.0.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_2.0.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_4.0.0.bb
meta-mender-core/recipes-mender/mender-client/mender_5.0.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.3.0.bb

Changelog: Add recipe for `mender` 5.0.0
Changelog: Add recipe for `mender-gateway` 2.0.0
Changelog: Add recipe for `mender-connect` 2.3.0
Changelog: Add recipe for `mender-artifact` 4.0.0
Changelog: Add recipe for `mender-monitor` 1.4.0

Add recipes from Mender Client and Mender Gateway releases

---

meta-mender-core/classes/grub-mender-grubenv.bbclass
meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled.inc
meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled_2.04.bb
meta-mender-core/recipes-bsp/grub/grub-efi-mender-precompiled_2.12.bb

By adding recipe for `grub-efi-precompiled` for GRUB v2.12
Update the precompiled version for GRUB, used on ARMv7 boards like
BeableBone Black, so that they can boot (and update) correctly with the
latest filesystem features. See:
* https://github.com/mendersoftware/grub-mender-grubenv/pull/39
From Yocto `scarthgap` release on, `mke2fs` enables the feature
`metadata_csum_seed` by default, which is not understood in the
previous GRUB version. See:
* Bug report: http://savannah.gnu.org/bugs/?56897
* Fix: https://git.savannah.gnu.org/cgit/grub.git/commit/?id=7fd5feff97c4b1f446f8fcf6d37aca0c64e7c763
* mke2fs release notes: https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/tree/doc/RelNotes/v1.47.0.txt
To upgrade with Mender (or any other means, really) from `kirkstone` to
`scarthgap` the …

MEN-7854: Restore GRUB integration for ARMv7 boards (Beaglebone Black)

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_git.bb

See:
* https://github.com/mendersoftware/mender-gateway/pull/190

MEN-7886: Bump `mender-gateway` copyright license year to 2025

---

meta-mender-commercial/classes/mender-closed-source-utils.bbclass
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-core/recipes-mender/mender-flash/mender-flash_git.bb
meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot_git.bb

These went unnoticed when we updated the syntax from kirkstone to scarthgap. All of them however relate to internal testing, so no real damage has been done elsewhere.

chore: Fix syntax for test code figuring out the mender versions

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc

This was updated a while back in [1]. Odd that this has gone unnoticed for so long?
Changelog: Prevent secondary rootfs from being mounted by udev-extraconf.
[1]. https://git.openembedded.org/openembedded-core/commit/meta/recipes-core/udev/udev-extraconf_1.1.bb?id=69e486ddb3059f80ba538e1f59c2ca8a8df0faf9
```
```
Thank you!

chore: update mount.blacklist -> mount.ignorelist

---

meta-mender-core/classes/mender-setup-image.inc

when switching from kirkstone to scarthgap, `ROOTFS_POSTPROCESS_COMMAND` variable synthax changed and now uses space as separator instead of ';'. 
[ROOTFS_POSTPROCESS_COMMAND scarthgap documentation](https://docs.yoctoproject.org/5.0.7/singleindex.html#term-ROOTFS_POSTPROCESS_COMMAND)

chore: use new ROOTFS_POSTPROCESS_COMMAND syntax

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

As we are moving towards releasing `mender-artifact` out of the LTS bundled components, we won't have anymore maintenance branches and the tags (both bugfix and feature tags) will live in the main `master` branch. Reflect this already for `git` recipe
Setting no changelog as this only affects Git builds (iow master) or release candidate builds.

MEN-8269: Rework `mender-artifact` git recipe to accommodate to new release process

---

meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc

mender-inventory-geo need --tires for wget.
wget in busybox doesn't have this option therefore need a full verion of wget to work

fix: Add full version of wget for mender inventory mender-inventory-geo

---

meta-mender-commercial/recipes-extended/images/mender-gateway-image-full-cmdline.bb
meta-mender-demo/conf/layer.conf
meta-mender-demo/mender-commercial/images/mender-gateway-image-full-cmdline.bbappend

A follow-up from where we removed the use of this image in integration tests suites.

QA-945: Remove now unused testing image for `mender-gateway`
