tests/acceptance/.gitignore
tests/acceptance/README.md
tests/acceptance/common.py
tests/acceptance/conftest.py
tests/acceptance/test_update.py

- Update with a bogus image.
- Update a proper image.
- Fail to update an image because of insufficient space.
- Commit image

Add acceptance tests for basic Mender functionality.

---

tests/acceptance/common.py

Changed the 'mender-qemu' path to correct path

---

tests/acceptance/common.py

Increased wait argument to 120s for reboot() and run_after_connect()

---

recipes-mender/mender/files/mender.service

Fix some typos and add daemon option supported by client.

Make sure Mender will be started as daemon.

---

classes/mender-image-buildinfo.bbclass
classes/mender-install.bbclass
classes/sdimg.bbclass
recipes-bsp/u-boot/u-boot.inc
recipes-mender/mender/files/mender.conf
recipes-mender/mender/mender_0.1.bb

Add support for storing image metadata inside image.

Add Mender configuration to be read from file.

---

recipes-bsp/u-boot/files/0001-Enable-boot-code-specifically-for-the-U-Boot-QEMU-sc.patch
tests/acceptance/test_update.py

This way we fall back to the original partition after a failed image update.

Auto-reboot if boot command fails

---

recipes-bsp/u-boot/u-boot/0001-powerpc-cpu-u-boot-.lds-remove-_GLOBAL_OFFSET_TABLE_.patch
recipes-bsp/u-boot/u-boot/0002-image.c-Fix-non-Android-booting-with-ramdisk-and-or-.patch
recipes-bsp/u-boot/u-boot/0003-common-board_f-enable-setup_board_part1-for-MIPS.patch
recipes-bsp/u-boot/u-boot/0004-MIPS-bootm-rework-and-fix-broken-bootm-code.patch
recipes-bsp/u-boot/u-boot/0005-MIPS-bootm-use-CONFIG_IS_ENABLED-everywhere.patch
recipes-bsp/u-boot/u-boot/0006-Replace-extern-inline-with-static-inline.patch
recipes-bsp/u-boot/u-boot_2015.10.bb

Lack of one of those files is preventing form booting image
using Beaglebone Black. Next step should be to figure out which patches
are not important and remove those.

Add patch files from original Yocto u-boot meta recipe.

---

recipes-bsp/u-boot/u-boot-mender.inc

Apply cross platform GCC patch everywhere, not just QEMU.

---

recipes-mender/mender/mender_0.1.bb

Fix default server certificate location.

---

recipes-mender/mender/mender_0.1.bb

Include git revision info in PV. Make sure that agent is rebuilt each time mender repository revision is changed.
@pasinskim @kacf

PV changes

---

recipes-mender/mender/files/mender.service

Automatically create /data/mender path before starting mender service.
@kacf @pasinskim

mender: create /data/mender during startup

---

recipes-mender/mender/mender_0.1.bb

The changes should be merged only after https://github.com/mendersoftware/mender/pull/63 to mender repository has been merged.

mender: use make for building

---

tests/acceptance/common.py

Update u-boot path to reflect new path

---

conf/machine/vexpress-qemu.conf

IMAGE_FSTYPES should be configurable by the user.

---

classes/mender-sdimg.bbclass

Give boot partition a more reasonable size.

---

classes/mender-image.bbclass
recipes-mender/mender/mender_0.1.bb

mender-image: make sure that required FSTYPES are present

---

classes/mender-systemd.bbclass

Fix broken DISTRO_FEATURES variable in mender-systemd.bbclass

---

classes/mender-image-buildinfo.bbclass

Move build_mender to mender directory.

---

recipes-mender/mender/mender_0.1.bb

Make sure license check catches all licenses Mender uses.

---

classes/mender-sdimg.bbclass
classes/mender-uboot.bbclass
recipes-bsp/u-boot/files/generic-mender-boot-code.patch
recipes-bsp/u-boot/u-boot-fw-utils_2015.10.bbappend
recipes-bsp/u-boot/u-boot-mender.inc

See individual commits for details.

Various fixes from hio port

---

recipes-bsp/u-boot/files/generic-mender-boot-code.patch

Turn C++ comments into C comments.

---

recipes-bsp/u-boot/files/generic-mender-boot-code.patch

Fix corrupted patch.

---

tests/acceptance/test_update.py

Set both Mender updating tests to expected fail

---

tests/acceptance/common.py
tests/acceptance/test_update.py

@kacf this PR will make the autocommit on successful reboot work again

Create a fake authtoken before running tests

---

tests/acceptance/test_update.py

Changing test condition after error output changed.

---

recipes-devtools/go/go-cross_%.bbappend
recipes-devtools/go/go-native_%.bbappend

Remove Go workaround that has been fixed upstream.

---

classes/mender-sdimg.bbclass

do_rootfs_wicenv: Follow poky more closely in dependency definition.

---

tests/acceptance/conftest.py
tests/acceptance/prepare_bbb_testing.sh
tests/acceptance/prepare_ext3_testing.sh

Fix all hardcoded test paths to use proper workspace.

---

classes/mender-install.bbclass

Add some comments to make it easier to see what can be configured.

---

recipes-mender/mender/mender_0.1.bb

Fix swapped MENDER_SERVER_URL and HOMEPAGE variables.

---

classes/mender-install.bbclass

Remove need to set two storage device variables when one will do.

---

recipes-bsp/u-boot/files/0001-BBB-Use-Mender-boot-code-for-selecting-boot-device-a.patch

Update Beaglebone patch after boot command was refactored upstream.

---

recipes-bsp/u-boot/files/0001-BBB-Use-Mender-boot-code-for-selecting-boot-device-a.patch
recipes-bsp/u-boot/files/0001-Generic-boot-code-for-Mender.patch
recipes-bsp/u-boot/u-boot-mender.inc

Further adaptations after BeagleBone boot code was refactored.

---

Documentation/artifact-format.md

Signed-off-by: Kristian Amlie <kristian@amlie.name>

Update format of files

---

Documentation/artifact-format.md

Make sure that latest implementation changes are reflected in the format of the artifact.

Update format of atrifact archive.

---

recipes-mender/mender/mender_0.1.bb

The checksum for license file seems to be incorrect.

Fix broken Yocto build.

---

recipes-mender/mender/files/mender.service

@bboozzoo @pasinskim 
As discussed, this is a temp solution to our problem: MEN-609.
The solution is not great, but it works.
We will revisit this in the future.

Load mender after network and nss

---

recipes-mender/mender/mender_0.1.bb

mender: ship example inventory tools

---

recipes-mender/mender/files/mender.service

fixup! Load mender after network and nss

---

recipes-mender/mender/files/mender.service

This reverts commit 4dc6e5ffdd8e09fa396a1979a9c3180bc5adc2da.

Revert "fixup! Load mender after network and nss"

---

recipes-mender/mender/files/mender.service

I've been able to run the entire test suite without seeing DNS failure with this change

Attempt to make the mender service run last

---

classes/mender-sdimg.bbclass

sdimg can be properly built for me using recent poky master (49a7839)

sdimg build fixes

---

classes/mender-sdimg.bbclass

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>

mender-sdimg: further adjustments for IMGDEPLOYDIR

---

classes/mender-artifactimg.bbclass
classes/mender-image.bbclass
recipes-mender/artifacts/artifacts.bb
recipes-mender/mender/mender_0.1.bb

`artifacts` recipe will need an update once we merge  https://github.com/mendersoftware/artifacts/pull/26 due license changes

artifact image

---

classes/mender-artifactimg.bbclass

Change "mender-artifactimg: adjustments for IMGDEPLOYDIR"

---

classes/mender-sdimg.bbclass

mender-sdimg: provide a weak default for UBOOT_SUFFIX

---

classes/mender-sdimg.bbclass

mender-sdimg: rename SDIMG_* variables to MENDER_SDIMG_*

---

tests/acceptance/test_update.py

tests: Follow change of error string in the source code.

---

classes/mender-sdimg.bbclass

mender-sdimg: use wic for building SD card images

---

classes/mender-sdimg.bbclass
tests/acceptance/test_update.py

Krogoth merge from master

---

recipes-mender/mender/mender_0.1.bb

Update license checksum after adding LMDB.

---

classes/mender-sdimg.bbclass

Introduce MENDER_STORAGE_TOTAL_SIZE_MB that specifies the size of the
medium that will hold sdimg image. Rootfs is sized automatically by
distributing the remaining space after subtracting boot & data partition
sizes (incl. partitioning overhader) from the total size.
Generated kickstart (boot 16MB, rootfs 2 * 424, data auto sized):
```
part /boot   --source bootimg-partition --ondisk mmcblk0 --fstype=vfat --label boot --align 8192 --active --size 16
part /       --source rootfs --ondisk mmcblk0 --fstype=ext4 --label primary --align 8192 --reserved-size 424
part         --source rootfs --ondisk mmcblk0 --fstype=ext4 --label secondary --align 8192 --reserved-size 424
part /data   --source fsimage --sourceparams=file="/home/mborzecki/yocto/heads/mender-bbb/tmp/work/vexpress_qemu-poky-linux-g …
```

mender-sdimg: introduce MENDER_STORAGE_TOTAL_SIZE_MB, calculate rootfs size

---

tests/acceptance/common.py

Fix typo after review amendment.

---

recipes-mender/mender/mender_0.1.bb

Warn when building with default server.crt file

---

meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-beaglebone.inc
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-qemu/recipes-bsp/u-boot/u-boot-vexpress-qemu.inc

Move leftover board specific definitions to bsp layers.

---

meta-mender-core/recipes-mender/mender/files/mender.conf

Add separate pool intervals for inventory and updates.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.bb

Add missing exit command on error.

---

meta-mender-beaglebone/recipes-bsp/u-boot/patches/0001-BBB-Use-Mender-boot-code-for-selecting-boot-device-a.patch
meta-mender-core/recipes-bsp/u-boot/patches/0001-Generic-boot-code-for-Mender.patch
meta-mender-core/recipes-bsp/u-boot/patches/0002-Add-missing-header-which-fails-on-recent-GCC.patch
meta-mender-core/recipes-bsp/u-boot/patches/0002-Integration-of-Mender-boot-code-into-U-Boot.patch
meta-mender-qemu/recipes-bsp/u-boot/patches/0001-Enable-U-Boot-on-QEMU-to-use-Mender-boot-code.patch

Update U-Boot patches after move to U-Boot v2016.11.

---

meta-mender-beaglebone/recipes-bsp/u-boot/patches/0001-BBB-Use-Mender-boot-code-for-selecting-boot-device-a.patch
meta-mender-core/classes/mender-install.bbclass
meta-mender-core/classes/mender-sdimg.bbclass
meta-mender-core/classes/mender-uboot.bbclass
meta-mender-core/recipes-bsp/u-boot/patches/0001-Generic-boot-code-for-Mender.patch
meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender.inc
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-core/recipes-bsp/u-boot/u-boot-mender.inc
meta-mender-qemu/recipes-bsp/u-boot/patches/0001-Enable-U-Boot-on-QEMU-to-use-Mender-boot-code.patch
tests/acceptance/common.py
tests/acceptance/test_sdimg.py
tests/acceptance/test_update.py

This is best reviewed commit by commit.

MEN-480, MEN-749: Redundant U-Boot environment

---

tests/acceptance/test_update.py

This will never happen in practice, and the test breaks if you had a
preceding test which left a corrupted environment in the oldest of the
two (which the test itself would do, hence it will not pass twice in a
row). While that could be fixed, remove the test instead, since it's
not a relevant real life scenario.

Remove test which corrupts the oldest of the two redundant U-Boot envs.

---

meta-mender-core/classes/mender-sdimg.bbclass

Remove leftover debug code that has no effect.

---

meta-mender-core/recipes-mender/mender/mender_0.1.bb

Enable Mender daemon by default.

---

meta-mender-core/classes/mender-install.bbclass
meta-mender-core/classes/mender-uboot.bbclass

Move U-Boot related variables into mender-uboot class.

---

tests/acceptance/prepare_bbb_testing.sh

Add JUnit test results for Jenkins consumption.

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch

Backport redundant U-Boot environment to morty

---

meta-mender-core/classes/mender-sdimg.bbclass
meta-mender-core/recipes-mender/mender-artifact/mender-artifact.bb

wic tools support

---

meta-mender-core/recipes-mender/mender/mender_0.1.bb

MEN-621: Enable stripping of Mender binary to reduce size.

---

meta-mender-core/classes/mender-sdimg.bbclass

Adapt to location changes in wic components.

---

meta-mender-beaglebone/recipes-bsp/u-boot/patches/0001-BBB-Use-Mender-boot-code-for-selecting-boot-device-a.patch

Update Beaglebone patch for U-Boot v2017.01.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.bb
meta-mender-core/recipes-mender/mender/mender_0.1.bb

Switch Mender client over to 1.0.x branch.

---

meta-mender-core/classes/mender-install.bbclass
meta-mender-core/recipes-mender/mender-artifact/mender-artifact.inc
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_1.0.0b1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/mender.inc
meta-mender-core/recipes-mender/mender/mender_1.0.0b1.bb
meta-mender-core/recipes-mender/mender/mender_git.bb
tests/acceptance/test_build.py

Split Mender binaries into 1.0.0b1 and git versions.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.inc

Build fixes

---

meta-mender-core/classes/mender-sdimg.bbclass

Replace fsimage wic plugin, which was removed upstream, with rawcopy.

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-qemu/scripts/mender-qemu
tests/acceptance/test_build.py

Add MENDER_ARTIFACT_SIGNING_KEY variable to automatically sign artifact.

---

tests/acceptance/test_update.py

Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

increase broken image from 8mb to 32mb of zeros

---

tests/acceptance/test_update.py

Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

create actual file when testing broken image

---

tests/acceptance/test_update.py

Restore test case behavior after MEN-1198 is solved.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.0.0b1.bb
meta-mender-core/recipes-mender/mender/mender_1.1.0b1.bb

Add mender 1.1.0b1 and mender-artifact 2.0.0b1 to layer.

---

meta-mender-core/recipes-mender/mender/mender_git.bb

Update checksum for Mender client to match UBI changes.

---

meta-mender-qemu/Dockerfile
meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py

Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

add option to specify ArtifactVerifyKey in mender config script

---

meta-mender-core/classes/mender-sdimg.bbclass

Signed-off-by: Mirza Krak <mirza.krak@endian.se>

mender-sdimg: merge duplicate IMAGE_DEPENDS_sdimg

---

meta-mender-core/classes/mender-sdimg.bbclass

Signed-off-by: Drew Moseley <drew.moseley@mender.io>

Don't emit warning on multiple fs candidates if they are identical.

---

tests/acceptance/test_mender-artifact.py

Now manifest file contains the checksum of the version file
and tests need to be updated.

Update tests to check for version file checksum.

---

meta-mender-core/recipes-mender/mender/mender_git.bb

Update 1.1.x branch license for Git builds.

---

meta-mender-core/classes/mender-state-scripts.bbclass
tests/acceptance/test_build.py

Changelog: Install /etc/mender/scripts/version file
Modified-by: Kristian Amlie <kristian.amlie@northern.tech>
* Added test case and removed unneeded comment.
Also fixes MEN-1306.

state-scripts: Install /etc/mender/scripts/version file

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Take 2.0.x branch into account in Git recipe.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

(cherry picked from commit f5db10cf7374f8272dbd28bf4706c61ddf5ff978)

[pyro] Take 2.0.x branch into account in Git recipe.

---

meta-mender-core/classes/mender-install-ubi.bbclass

@estenberg @kacf @GregorioDiStefano

meta-mender-core: do not warn about ubifs being unsupported

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/mender_git.bb

Fix parse error when PREFERRED_VERSION is unset

---

meta-mender-demo/recipes-mender/example-state-scripts/files/example-script

(cherry picked from commit afd226aaf0c288593b2983d4836edbec1929de6b)

Add additional logging to example state scripts

---

tests/acceptance/common.py

tests: Fix incorrect reference to bitbake variable in version detection.

---

meta-mender-qemu/conf/machine/vexpress-qemu-flash.conf

vexpress-qemu-flash: Use conditional assignments to allow overrides

---

meta-mender-qemu/scripts/mender-qemu
tests/acceptance/common.py
tests/acceptance/test_build.py

@kacf @drewmoseley @GregorioDiStefano

use temporary directory for extracting images in mender-qemu 

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.0.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.1.0.bb
meta-mender-core/recipes-mender/mender/mender_1.1.1.bb
meta-mender-core/recipes-mender/mender/mender_1.2.0.bb

Add all new Mender 1.1.1 and 1.2.0 components to recipes.

---

tests/acceptance/test_update.py

Add an acceptance test for checking that the update is failing
if header checksum is invalid.

MEN-1412 Fix broken header checksum verification.

---

tests/acceptance/test_update.py

Just to make sure the resulting error is not from failing to parse the
JSON file.

tests: Be paranoid, do checksum verification with valid JSON.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.0.2.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.1.1.bb
meta-mender-core/recipes-mender/mender/mender_1.1.2.bb
meta-mender-core/recipes-mender/mender/mender_1.2.1.bb

Add recipes for Mender release 1.1.3 and 1.2.2.

---

meta-mender-qemu/Dockerfile
meta-mender-qemu/scripts/docker/entrypoint.sh
meta-mender-qemu/scripts/docker/setup-mender-configuration.py

Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

pre-generate ssh keys before booting mender-qemu

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-raspberrypi/README.md

Setup image dependencies for SDIMG on Raspberry Pi platforms

---

meta-mender-core/recipes-mender/mender/mender.inc

cherry picked from commit 276a7cc299c396573c5005310dab6606814bb4c3

Support building without a server.crt client certificate.

---

meta-mender-core/recipes-mender/mender/README-releasing.md

Document how to make new recipes for new releases.

---

meta-mender-core/recipes-mender/mender-artifact/README-releasing.md

Add recipe instructions to mender-artifact by linking to mender. 

---

meta-mender-raspberrypi/README.md

Update the documentation for the required options in local.conf. There have been some changes in meta-raspberrypi which we need to adjust to.
I have boot and update tested this on a RPi3.
This is only applicable on master branch and in upcoming rocko.

Update rpi setup

---

meta-mender-core/recipes-mender/mender/mender_1.3.0b1.bb

Add Mender 1.3.0b1 recipe.

---

meta-mender-demo/recipes-mender/example-state-scripts/files/example-script
meta-mender-demo/recipes-sato/packagegroups/packagegroup-core-x11-sato.bbappend

This is the pyro equivalent of https://github.com/mendersoftware/meta-mender/pull/413

A couple of minor cleanups for pyro

---

tests/acceptance/test_sdimg.py

Fix test fixture, before it would fail if host was missing fdisk.

---

meta-mender-toradex-nxp/recipes-bsp/u-boot/files/mx7/0003-colibri-imx7-mender-integration-override-ubiboot-and.patch
tests/meta-mender-toradex-nxp-ci/recipes-bsp/u-boot/files/colibri-imx7/0001-colibri-imx7-Mender-QA-extend-env-to-support-integra.patch
tests/meta-mender-toradex-nxp-ci/recipes-bsp/u-boot/u-boot-mender-toradex-nxp-ci.inc

This is the first set of patches for getting the Toradex bits working on the master branch with the current rocko-next branch from Toradex.

Toradex wip master

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch
meta-mender-toradex-nxp/recipes-bsp/u-boot/files/mx7/0003-colibri-imx7-mender-integration-override-ubiboot-and.patch
tests/meta-mender-toradex-nxp-ci/recipes-bsp/u-boot/files/colibri-imx7/0001-colibri-imx7-Mender-QA-extend-env-to-support-integra.patch
tests/meta-mender-toradex-nxp-ci/recipes-bsp/u-boot/u-boot-mender-toradex-nxp-ci.inc

This is the first set of patches for getting the Toradex bits working on the pyro branch with the current morty branch from Toradex.

Toradex wip pyro

---

tests/acceptance/test_update.py

Fix incorrect test cleanup causing boot failure on physical boards.

---

meta-mender-core/recipes-mender/mender/mender_1.3.0.bb

Add Mender 1.3.0 build recipe.

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch

mender: Quote bootargs for expansion with embedded variables. 

---

meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-toradex-nxp/conf/machine/colibri-imx7-mender.conf

Fixes for issues discussed in #446.

Auto patch bugs

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch

rpi_0_w: Setup Mender required defconfigs

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-setup-image.inc
meta-mender-raspberrypi/README.md
meta-mender-toradex-nxp/conf/layer.conf

A couple of (hopefully) simpler changes than those in #469 to get merged easier.

More misc changes for master branch

---

meta-mender-demo/recipes-mender/mender/mender_%.bbappend

MEN-1006: Increased the standard mender-retry-polling interval

---

meta-mender-raspberrypi/README.md

Document raspberrypi0-wifi and raspberrypi-cm support.

---

tests/acceptance/test_uboot_automation.py

test_uboot_compile: Update SHAs to latest to skip.

---

meta-mender-core/recipes-mender/mender/mender_git.bb

Also remove some old and outdated ones.

Update to latest license checksum for master.

---

meta-mender-core/recipes-mender/mender/mender_git.bb

Update mender license checksums for 1.3.x and 1.4.x.

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-ubimg.bbclass

This is a few matches from the dragonboard work that seem to be giving issues in testing.

PR #3 from Dragonboard

---

meta-mender-qemu/scripts/docker/entrypoint.sh

Add extra init steps to client container for SaaS platform.

---

tests/acceptance/test_uboot_automation.py

See the code comments for details on how it works.

Make test_uboot_compile auto-skip itself after some time of stability.

---

meta-mender-raspberrypi/conf/layer.conf

added layer dependency on mender layer

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Update to new license checksum for mender-artifact.

---

README.md
meta-mender-raspberrypi-demo/README.md
meta-mender-raspberrypi-demo/classes/rpi-demo-wifi.bbclass
meta-mender-raspberrypi-demo/conf/layer.conf
meta-mender-raspberrypi-demo/recipes-connectivity/wpa-supplicant/files/wpa_supplicant-wlan0.conf
meta-mender-raspberrypi-demo/recipes-connectivity/wpa-supplicant/wpa-supplicant_%.bbappend
meta-mender-raspberrypi-demo/recipes-core/systemd/files/wireless.network
meta-mender-raspberrypi-demo/recipes-core/systemd/systemd_%.bbappend

MEN-1804: Enable wifi in the raspberry-pi demo image by default.

---

meta-mender-core/recipes-mender/mender/mender_1.5.0b1.bb

Add Mender 1.5.0 Beta recipe.

---

meta-mender-core/recipes-mender/mender/mender_1.4.1.bb

Add Mender 1.4.1 recipe.

---

meta-mender-core/recipes-mender/mender/mender_1.5.0.bb

Add Mender 1.5.0 recipe.

---

meta-mender-core/classes/mender-setup-ubi.inc

Fix missed variable rename.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Licence checksum updated

---

meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh

Add informative message when hitting "fw_printenv -l" bug.

---

tests/acceptance/test_update.py

tests: Simplify logic to terminate temporary HTTP server.

---

meta-mender-demo/recipes-core/images/core-image-full-cmdline.bbappend

Should go together with https://github.com/mendersoftware/mender-docs/pull/450.
And should be cherry-picked to pyro branch once merged.

meta-mender-demo: remove append from MENDER_DATA_PART_DIR

---

meta-mender-core/classes/mender-full.bbclass
meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in

This follows https://github.com/mendersoftware/meta-mender/pull/561 .
Commits are signed and I added the changelogs

Meta mender aarch 64 support

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.1.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.1.2.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.2.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.3.0b1.bb
meta-mender-core/recipes-mender/mender/mender_1.6.0b1.bb

(cherry picked from commit 72c43fe6744ce7f676e143ab3681eb15c93c6922)

[sumo] Add mender 1.6.0b1 and mender-artifact 2.3.0b1 recipes.

---

meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
meta-mender-core/recipes-bsp/u-boot/u-boot-mender.inc

Enable EXTERNALSRC to be used with u-boot-fw-utils-mender-auto-provided.

---

meta-mender-core/classes/mender-helpers.bbclass
meta-mender-core/classes/mender-setup.bbclass

@drewmoseley: These are pretty important, so I cherry-picked them right away. Agree?

Rocko cherry-picks

---

meta-mender-demo/recipes-core/images/core-image-full-cmdline.bbappend
meta-mender-demo/recipes-core/packagegroups/packagegroup-core-boot.bbappend
meta-mender-demo/recipes-mender/boot-script/boot-script.bb
meta-mender-demo/recipes-mender/boot-script/files/LICENSE
meta-mender-demo/recipes-mender/boot-script/files/boot-script.service
meta-mender-demo/recipes-mender/boot-script/files/boot-script.sh

can be used to blink lights, show picture, video, etc.

boot-script recipe for easily demoing OTA updates

---

meta-mender-qemu/scripts/mender-qemu
tests/acceptance/common.py
tests/acceptance/fixtures.py
tests/acceptance/test_inventory.py

Based #589. Only the OS test is new.

MEN-2060: Add acceptance test for OS inventory script.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.3.0.bb
meta-mender-core/recipes-mender/mender/mender_1.5.1.bb
meta-mender-core/recipes-mender/mender/mender_1.6.0.bb

Changelog: Add mender 1.5.1 recipe.
Changelog: Add mender 1.6.0 recipe.
Changelog: Add mender-artifact 2.3.0 recipe.
(cherry picked from commit 67e7eeb0029a8456d7f3981d11e046cac52728d0)

Add components for Mender 1.5.1 and 1.6.0 releases.

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_1.1.0.bb
meta-mender-qemu/recipes-bsp/grub-mender-grubenv/files/02_qemu_console_arm_grub.cfg
meta-mender-qemu/recipes-bsp/grub-mender-grubenv/files/02_qemu_console_x86_grub.cfg
meta-mender-qemu/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_%.bbappend

Console logging fixes

---

tests/acceptance/test_build.py

Issues: MEN-2100
Signed-off-by: Adam Podogrocki <a.podogrocki@gmail.com>

Move test_boot_partition_population test to test_build.py file

---

meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb

u-boot-fw-utils: Add bison-native to DEPENDS.

---

meta-mender-core/recipes-bsp/grub/grub_%.bbappend

Signed-off-by: Michael Davis <michael.davis@essvote.com>

grub: Remove restriction that the core.img be at sector 1

---

meta-mender-qemu/scripts/mender-qemu

QEMU: Always try to run with KVM enabled, only fall back to emulation.

---

meta-mender-toradex-nxp/recipes-bsp/u-boot/files/colibri-imx7-emmc/0001-colibri-imx7-emmc-mender-integration-patch.patch
meta-mender-toradex-nxp/recipes-bsp/u-boot/files/colibri-imx7-emmc/fw_env.config
meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-mender-toradex-nxp.inc

meta-mender-toradex-nxp: add support for colibri-imx7-emmc

---

tests/acceptance/fixtures.py

(cherry picked from commit 6ff3e6782f844a8c06e5071b2d4720396ee2f898)

Fix deprecated pytest call that was removed in the latest version.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.4.0b1.bb
meta-mender-core/recipes-mender/mender/mender_1.7.0b1.bb

Changelog: Add mender 1.7.0 recipe.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>

Add components for Mender 1.7.0b1 release.

---

meta-mender-core/classes/mender-setup-image.inc
meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.4.0b1.bb
meta-mender-core/recipes-mender/mender/mender_1.7.0b1.bb
tests/acceptance/fixtures.py

This brings rocko inline with tag v2018.11.2 in sumo

Rocko backports

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.3.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.4.0.bb
meta-mender-core/recipes-mender/mender/mender_1.6.1.bb
meta-mender-core/recipes-mender/mender/mender_1.7.0.bb

Add mender-artifact 2.3.1 and 1.4.0 recipes.

---

meta-mender-core/recipes-mender/mender/mender_git.bb

MEN-2224: Updated the license checksum in mender-artifact

---

meta-mender-core/recipes-mender/mender/mender_git.bb

Update mender checksum for 2019 license.

---

meta-mender-core/recipes-mender/mender/mender_git.bb

MEN-2235: Update md5sum for the mender Licenses File

---

meta-mender-core/recipes-mender/mender/mender_git.bb

MEN-2335: Update License File md5sum for mender v1.7 release

---

meta-mender-core/recipes-bsp/grub/grub-mender.inc
meta-mender-core/recipes-mender/mender/mender_git.bb

Thud update

---

meta-mender-core/classes/mender-ubimg.bbclass

bugfix to prevent yocto error when rebuilding image

---

meta-mender-core/classes/mender-part-images.bbclass

This is a partial back-port of:
33225086db3 ("MEN-1845: Implement x86 BIOS support together with GRUB")
Which removed the limitation that the IMAGE_BOOTLOADER_BOOTSECTOR_OFFSET must
be 1kB aligned. It is useful to get rid of this limitation as there are some
boards/SoCs that require the bootloader to be at the first block (512 bytes / block)

allow IMAGE_BOOTLOADER_BOOTSECTOR_OFFSET to be aligend to 512 bytes

---

meta-mender-core/classes/mender-artifactimg.bbclass
meta-mender-core/classes/mender-helpers.bbclass
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.0.0b1.bb
meta-mender-core/recipes-mender/mender/mender_2.0.0b1.bb
meta-mender-qemu/recipes-mender/mender/mender-test-files.inc
meta-mender-qemu/recipes-mender/mender/mender_2.%.bbappend
tests/acceptance/common.py
tests/acceptance/fixtures.py
tests/acceptance/test_build.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_update.py

Commits that should go into master to support update module release, but before the main branch is merged.

Update modules support

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Update license checksum after vendor update in mender-artifact

---

tests/acceptance/test_update.py

(cherry picked from commit 4a65d70a3f298b270316959b2449bd6e0e0580a3)

MEN-2465: Add test for standalone upgrade of mender 1.x -> 2.x.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.0.0.bb
meta-mender-core/recipes-mender/mender/mender_2.0.0.bb

(cherry picked from commit 649253ed62021f7e6e6f43e72502061e0b872e1a)

Add recipe for mender-2.0.0 and mender-artifact-3.0.0.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_2.4.1.bb
meta-mender-core/recipes-mender/mender/mender_1.7.1.bb

Add recipes for mender-1.7.1 and mender-artifact-2.4.1.

---

tests/acceptance/fixtures.py

The problem is that the version detection mistakes the custom branch
for a Yocto branch, so be explicit that only the listed branches are
candidates for Yocto branches.

Fix failure when submitting a PR with a branch in the main repo.

---

meta-mender-core/recipes-mender/mender/mender-old-makefile.inc
meta-mender-core/recipes-mender/mender/mender.inc

mender: Setup rootfs partitions in automount blacklist.

---

meta-mender-core/classes/mender-setup-ubi.inc

Do not hard code the ubi name.

---

meta-mender-core/recipes-mender/mender/mender_git.inc

Update mender license checksum after dependencies updates

---

meta-mender-core/recipes-mender/mender/mender_git.inc

Update mender license checksum after more dependencies updates

---

meta-mender-core/recipes-mender/mender/mender_git.inc

(cherry picked from commit 16f3e60de50e6dbf4300f9e65550c48cbee664f2)

mender_git.bb: Add checksum for 2.0.x branch specifically.

---

meta-mender-qemu/scripts/docker/entrypoint.sh

Open port 85 in the qemu containers 

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.0.1.bb
meta-mender-core/recipes-mender/mender/mender_2.0.1.bb

Add recipes for mender 2.0.1 and mender-artifact 3.0.1

---

tests/acceptance/test_inventory.py

Mark inventory test as 2.0.0 and later since we made some changes.

---

meta-mender-core/recipes-mender/mender/mender_git.inc

Update license checksum for client.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.1.0b1.bb
meta-mender-core/recipes-mender/mender/mender_2.1.0b1.bb

Part of Mender 2.1.0 Beta release.

Add mender 2.1.0b1 and mender-artifact 3.1.0b1 recipes.

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/files/06_mender_debug_force_grub_prompt_grub.cfg
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc

grub-mender-grubenv: Setup debug option to drop to grub prompt.

---

meta-mender-qemu/docker/qemux86-64/Dockerfile
meta-mender-qemu/docker/vexpress-qemu/Dockerfile
meta-mender-qemu/scripts/docker/ext4_manipulator.py
meta-mender-qemu/scripts/docker/setup-mender-configuration.py

Refactor and small code extension required for ongoing work on [MEN-2599](https://tracker.mender.io/browse/MEN-2599).
The change should be completely transparent to other components.

Refactor setup script

---

meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-core/initrdscripts/files/init-install-efi-mender.sh

Also added a warning to ensure users know that MENDER_STORAGE_DEVICE is not relevant when using mender-partuuid.

Live installer device scan

---

meta-mender-commercial/README.md

Add README for meta-mender-commercial layer.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.1.0.bb
meta-mender-core/recipes-mender/mender/mender_2.1.0.bb

Add mender-2.1.0 and mender-artifact-3.1.0.

---

meta-mender-core/classes/mender-full.bbclass
meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-mender/mender/mender.inc

Men 2337 enable dynamic resizing of the data partition

---

meta-mender-raspberrypi/recipes-bsp/u-boot/patches/0001-CONFIGS-rpi-enable-mender-requirements.patch

add support for Raspberry Pi 4

---

meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-core/initrdscripts/files/init-install-efi-mender.sh

A few more that I missed previously.

Thud backports

---

meta-mender-commercial/README.md

Update README in commercial layer for Mender 2.2.

---

tests/acceptance/test_uboot_automation.py

Needs to be merged at the same time that poky/warrior is updated and #842 is merged.

Warrior update

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.2.0b1.bb

Add mender-artifact 3.2.0 and remove beta.

---

meta-mender-core/recipes-mender/mender/mender_git.inc
tests/acceptance/test_update.py

New checksum also covers the updated cli package.
changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

Updated md5 checksum for mender/LIC_FILES_CHKSUM.sha256

---

meta-mender-core/recipes-mender/mender/mender_git.inc

changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

Update checksum for `2.1.[1x].*` tags

---

meta-mender-core/recipes-mender/mender/mender_git.inc
tests/acceptance/test_update.py

Follow-up from PRs #844, #850 and #851

Update mender git lic checksums warrior

---

tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/common.py
tests/acceptance/conftest.py
tests/acceptance/fixtures.py
tests/acceptance/pytest.ini
tests/acceptance/requirements.txt
tests/acceptance/requirements_py3.txt
tests/acceptance/test_bootimg.py
tests/acceptance/test_build.py
tests/acceptance/test_commits.py
tests/acceptance/test_dataimg.py
tests/acceptance/test_inventory.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_ubimg.py
tests/acceptance/test_uboot_automation.py
tests/acceptance/test_update.py

Updating our client acceptance tests to Python3. This is still WIP.

Python3 upgrade of acceptance tests

---

tests/acceptance/common.py
tests/acceptance/fixtures.py

Missing fixes from PR #849. See individual commits.

QA-120: Acceptance tests python3 for mender-convert 

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-setup.bbclass

Just a few things I've been tracking locally.

A few random updates

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.0.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.1.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.2.1.bb
meta-mender-core/recipes-mender/mender/mender_2.1.2.bb

Add recipes for Mender releases 2.1.1 and 2.2.1
Changelog: Add mender 2.1.2 recipe
Changelog: Add mender-artifact 3.1.1 recipe
Changelog: Add mender-artifact 3.2.1 recipe

Add recipes for Mender releases 2.1.1 and 2.2.1

---

tests/acceptance/test_build.py

Created in relation to: https://github.com/mendersoftware/mender-artifact/pull/245

Update the acceptance tests to handle default rootfs-image-checksum provides

---

tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/common.py
tests/acceptance/conftest.py
tests/acceptance/fixtures.py
tests/acceptance/test_bootimg.py
tests/acceptance/test_build.py
tests/acceptance/test_commits.py
tests/acceptance/test_mender-artifact.py
tests/acceptance/test_ubimg.py
tests/acceptance/test_uboot_automation.py
tests/acceptance/test_update.py

Format all Python files in acceptance tests with Black

---

meta-mender-core/README.md
meta-mender-core/classes/mender-helpers.bbclass
meta-mender-core/classes/mender-setup-grub.inc
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc
meta-mender-core/recipes-bsp/grub/grub-efi_%.bbappend
meta-mender-core/recipes-bsp/systemd/systemd-boot_%.bbappend
meta-mender-demo/recipes-core/systemd-conf/files/en.network
meta-mender-demo/recipes-core/systemd-conf/systemd-conf_%.bbappend
tests/acceptance/test_build.py
tests/meta-mender-ci/recipes-testing/test-boot-files/files/dummy-with-different-content
tests/meta-mender-ci/recipes-testing/test-boot-files/test-boot-files_1.0.bb

Resubmission of #885, with test fixes.

Drew fixes

---

tests/acceptance/test_snapshot.py

MEN-2981: Add acceptance test for `mender snapshot` feature.

---

meta-mender-core/recipes-mender/mender/mender_git.inc

Update mender checksum after update to year 2020.

---

.gitlab-ci.yml
pyproject.toml
tests/acceptance/test_dataimg.py
tests/acceptance/test_inventory.py

This adds the new formatting check, and formats the files which are out of sync.

Enable the new formatting check for Python files

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.inc

Resubmission of #895

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/mender_git.inc

Update 2020 license checksum for mender.

---

meta-mender-core/classes/mender-setup.bbclass

bitbake.conf already contains a '-' in IMAGE_VERSION_SUFFIX.

remove stray '-' in IMAGE_NAME

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.3.0b1.bb
meta-mender-core/recipes-mender/mender/mender_2.2.0b1.bb

* Add mender 2.2.0b1 recipe
* Add mender-artifact 3.3.0b1 recipe

Add recipes for Mender beta release 2.3.0b1

---

meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-2019.01/0001-Disable-addition-of-simple-framebuffer-by-U-boot.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot_2019.01.bbappend

rpi: Add workaround for display corruption in Warrior branch.

---

meta-mender-core/recipes-mender/mender/mender_git.inc

Together with https://github.com/mendersoftware/mender/pull/499

Adjust licenses file checksum after vendor update in mender

---

meta-mender-core/classes/mender-helpers.bbclass
meta-mender-core/classes/mender-setup-image.inc
tests/acceptance/test_build.py

Make sure partitions are marked for fsck'ing by default.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

vendor mender-artifact: update md5sum

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
tests/acceptance/test_update.py

MEN-3251: Updates the md5(LIC_FILES_CHECKSUM) for the Mender client

---

meta-mender-core/recipes-bsp/u-boot/files/add_kconfig_option_with_depends.py

This would lead to the configure step getting stuck in a config screen
which would repeatedly ask for input over and over, consuming all
memory.
Changelog: Fix infinite loop which would eat all available memory
on the build host, when using U-Boot v2020.01 or later together with
the auto-patcher.
MEN-3265

u-boot: Make sure auto-patcher handles multiline Kconfig entries.

---

tests/meta-mender-ci/conf/layer.conf
tests/meta-mender-ci/recipes-extended/lsb/lsb-test_1.0.bb

MEN-3264: Restore lsb_release tool for testing purposes.

---

meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-raspberrypi.inc

Missed that you renamed the file in #959

raspberrypi: update Mender integration patch path

---

meta-mender-core/classes/mender-setup.bbclass

These features are incompatible

mender: Add sanity check for partuuid and uboot.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

This upgrade is done in accordance with:
https://github.com/mendersoftware/mender-artifact/pull/263
Which added a new dependency.

Updated the LIC_FILES_CHKSUM file

---

tests/acceptance/common.py
tests/acceptance/fixtures.py
tests/meta-mender-ci/recipes-testing/mender-coverage-client/gobinarycoverage.bb
tests/meta-mender-ci/recipes-testing/mender-coverage-client/mender-client_%.bbappend

This PR adds the ability to collect coverage through running the mender client like usual.
This PR is now ready for final review.
:slightly_smiling_face:

[Final] Add coverage instrumentation to the Mender client

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

This is the checksum required after PR:
https://github.com/mendersoftware/mender-artifact/pull/262

Bump the mender-artifact LIC_FILES_CHKSUM checksum

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc
meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_git.bb

grub: Move dynamic storage handling into grub-mender-grubenv repository. 

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

This goes along with the changes in: https://github.com/mendersoftware/mender-artifact/pull/269

Updated the LIC_FILES_CHECKSUM file

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

chore(checksum): Update the mender-client licenses checksum

---

meta-mender-raspberrypi/recipes-mender/update-firmware-state-script/files/ArtifactInstall_Leave_50.in

I found these issues on a warrior branch project.  I'll submit there as well.

Firmware install updates.

---

tests/build-conf/raspberrypi4/bblayers.conf
tests/build-conf/raspberrypi4/local.conf

Add Raspberry Pi 4 as a build-tested platform.

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Update the mender-client license checksum

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Add license for the 2.3.x branch of mender-client.

---

tests/build-conf/raspberrypi4/bblayers.conf
tests/build-conf/raspberrypi4/local.conf

(cherry picked from commit bcb700bde95650d0a6f5b94e290770cf9c1ca764)

warrior: Add Raspberry Pi 4 as a build-tested platform.

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Bump mender-client master license checksum

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.0.1.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.0b1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.0b1.bb
meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-client/mender-client_2.1.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.1.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.1.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.1.3.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.2.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.0b1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.bb

There is a lot of copying going on, so this may be easier to view locally with `-C -C -M` arguments added.

Recipes for 2.4.0b1 Mender Product release

---

tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/helpers.py

tests: Consolidate link creation in helper, instead of in test case.

---

.github/PULL_REQUEST_TEMPLATE.md

QA-191: Add a contributor PR template

---

meta-mender-core/classes/grub-mender-grubenv.bbclass

Changelog: add support for separate A/B kernel partitions

Update to new grub-mender-grubenv.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

To go together with:
* https://github.com/mendersoftware/mender/pull/563
* https://github.com/mendersoftware/mender-artifact/pull/285

QA-200: Update licenses checksums for vendor updates

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Update checksum for mender-artifact/3.4.x branch Git recipe.

---

meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh
meta-mender-core/recipes-bsp/u-boot/u-boot-mender-common.inc
tests/acceptance/test_os_integration.py

(cherry picked from commit 5f7e4233e0de13d82e619f7c542c6d589097ac69)

Increase timeout in syslog test to account for slow vexpress-qemu + test PR 1008

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

chmod 600 on mender.conf

---

meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/recipes-mender/mender-client/files/mender-client-resize-data-part.sh.in
meta-mender-raspberrypi/classes/rpi-update-firmware.bbclass
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf

To reviewers, it is https://github.com/mendersoftware/meta-mender/commit/ce88ec9b92afb9ff6311f459e98bf189b3e6e2b1 which is the new commit here.

Adapt to name change in meta-raspberrypi + merge with master

---

meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot-2020.01/0001-dm-core-Move-ofdata_to_platdata-call-earlier.patch
meta-mender-raspberrypi/recipes-bsp/u-boot/u-boot_2020.01.bbappend

https://github.com/agherzan/meta-raspberrypi/pull/660
raspberrypi CM3 fails to boot (u-boot hangs) on 2020.01 and adding this
path fix an issue.
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
Thank you!

Fix RPI CM3 u-boot hang

---

README.md

README: fix link to docs

---

tests/meta-mender-beaglebone-yocto-ci/conf/machine/beaglebone-mender.conf
tests/meta-mender-raspberrypi3-ci/conf/machine/raspberrypi3-mender.conf

These seem to only change the MACHINE name. Should not have any effect
on the build.

Remove CI beaglebone/raspberrypi3 conf files

---

meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc
meta-mender-qemu/recipes-support/gnutls/gnutls_%.bbappend
meta-mender-qemu/recipes-support/libp11/libp11_0.4.%.bbappend
tests/build-conf/qemux86-64-bios-grub-gpt/bblayers.conf
tests/build-conf/qemux86-64-bios-grub/bblayers.conf
tests/build-conf/qemux86-64-uefi-grub/bblayers.conf
tests/build-conf/vexpress-qemu-flash/bblayers.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/bblayers.conf
tests/build-conf/vexpress-qemu/bblayers.conf

MEN-3905 SoftHSM added

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

This is to go with:
https://github.com/mendersoftware/mender-artifact/pull/281

chore: Update the mender-artifact LIC_FILES_CHKSUM.sha256 shasum

---

meta-mender-core/recipes-mender/mender-client/mender-client_2.4.0.bb

Changelog: Add mender-client 2.4.0 recipe.

[dunfell] Add recipe for 2.5.0 release

---

meta-mender-core/recipes-mender/mender-client/mender-client_2.4.0.bb

Changelog: Add mender-client 2.4.0 recipe.

[master] Add recipe for 2.5.0 release

---

tests/acceptance/test_build.py

MEN-3076: update test_build to the latest mender-artifact

---

tests/acceptance/test_build.py

MEN-3482: update test_build to the latest mender-artifact

---

meta-mender-core/classes/mender-setup.bbclass

Signed-off-by: Michael Davis <michael.davis@essvote.com>
Thank you!

mender: Add additonal x86 arch to partuuid sanity check

---

meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh

MEN-3961 Fixing link that no longer exists.

---

meta-mender-core/classes/mender-bootimg.bbclass
meta-mender-qemu/recipes-connectivity/openssl/openssl_%.bbappend

Commits from #1083 that can go to current master.

Drew fixes to current master

---

meta-mender-core/recipes-kernel/linux/boot-partition-devicetree.bb
meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc
meta-mender-qemu/recipes-support/gnutls/gnutls_%.bbappend
meta-mender-qemu/recipes-support/libp11/libp11_0.4.%.bbappend

device tree naming + yocto layer check fixes

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch

mender: Fix broken patch for mender-systemd-machine-id.

---

tests/acceptance/requirements_py3.txt

Cherry-picking #1124, #1125, #1126, #1127 and #1128 at once.

Dependabot: accpetance tests pip updates

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch

[zeus] mender: Fix broken patch for mender-systemd-machine-id.

---

meta-mender-core/recipes-bsp/u-boot/patches/0002-Generic-boot-code-for-Mender.patch

[warrior] mender: Fix broken patch for mender-systemd-machine-id.

---

meta-mender-qemu/recipes-extended/sudo/sudo_%.bbappend
tests/acceptance/test_snapshot.py

MEN-3987 mender-artifact tests: sudo usage on/off if present/absent.

---

.gitmodules
tests/acceptance/conftest.py

dunfell: [tests/acceptance] Remove --no-pull and update image-tests

---

.gitmodules
tests/acceptance/conftest.py

zeus: [tests/acceptance] Remove --no-pull and update image-tests

---

tests/acceptance/test_update.py

The client has had an issue with rollback while still on the active partition,
where it would flip to the inactive partition, instead of actually rolling back.
This adds a test which verifies that the client now does indeed roll back to the
currently running active partition.

MEN-3980: Add a test for rollback regression in the client

---

meta-mender-core/classes/mender-part-images.bbclass

Add labels to the rootfs partitions

mender: Reestablish labels on the root filesystems.

---

meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bb

If this is green and good to go, this should be cherry picked at least to:
* `Dunfell`
* `Warrior`
* `Zeus`
Any more?

2.3.1 and 2.4.1 client recipes

---

meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bb

Em release dunfell (cherry)

---

meta-mender-core/recipes-mender/mender/mender_2.3.1.bb
meta-mender-core/recipes-mender/mender/mender_2.4.1.bb

[warrior] 2.3.1 and 2.4.1 client recipes

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Bump mender-client master LIC_FILES_CHKSUM md5 sum

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Bump: the mender-artifact LIC_FILES_CHKSUM checksum

---

tests/acceptance/requirements_py3.txt

#1163, #1179 and #1180 together.

Dependabot updates

---

tests/acceptance/test_build.py
tests/acceptance/test_uboot_automation.py

Porting https://github.com/mendersoftware/meta-mender/commit/c4bffbd80b86e20bfd9592432d3b997ae83a1b3b

Simplify get_bitbake_variables by doing env calculation inside it

---

tests/acceptance/test_dbus.py

MEN-4191: generic D-Bus JwtTokenStateChange signal 

---

meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc

Add xt_string kernel module, needed for TestFaultTolerance int. test.

---

tests/acceptance/requirements.txt
tests/acceptance/requirements_py3.txt

See https://github.com/mendersoftware/mender-test-containers/pull/30#discussion_r538145200 for motivation. This PR is the first piece required, I'll follow-up on the rest once it is merged.

Clean-up pip requirements files

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender/files/mender-client-resize-data-part.sh.in
meta-mender-core/recipes-mender/mender/mender.inc
meta-mender-core/recipes-mender/mender/mender_2.0.0.bb
meta-mender-core/recipes-mender/mender/mender_2.0.1.bb
meta-mender-core/recipes-mender/mender/mender_2.1.0.bb
meta-mender-core/recipes-mender/mender/mender_2.1.1.bb
meta-mender-core/recipes-mender/mender/mender_2.1.2.bb
meta-mender-core/recipes-mender/mender/mender_2.1.3.bb
meta-mender-core/recipes-mender/mender/mender_2.2.0.bb
meta-mender-core/recipes-mender/mender/mender_2.2.1.bb
meta-mender-core/recipes-mender/mender/mender_2.3.1.bb
meta-mender-core/recipes-mender/mender/mender_2.4.1.bb
meta-mender-core/recipes-mender/mender/mender_git.inc

Porting the update of #1172 without the test framework related changes.

[warrior] december update

---

meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc

Add yet another kernel module needed by TestFaultTolerance test.

---

meta-mender-qemu/docker/qemux86-64/Dockerfile
tests/acceptance/requirements_py3.txt

Monday duty: testing together #1222, #1223 and #1224.

Dependabot weekly updates

---

meta-mender-core/recipes-mender/mender-shell/mender-shell.bb
meta-mender-demo/conf/layer.conf
meta-mender-demo/recipes-mender/mender-shell/mender-shell.bbappend

Porting the `mender-shell` commits from #1233.

[warrior] mender-shell

---

meta-mender-core/recipes-mender/mender-connect/mender-connect.bb
meta-mender-demo/conf/layer.conf
meta-mender-demo/recipes-mender/mender-connect/mender-connect.bbappend
meta-mender-demo/recipes-mender/mender-shell/mender-shell.bbappend
tests/acceptance/test_build.py

MEN-4292: Rename mender-shell to mender-connect

---

meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bb
tests/acceptance/commercial/test_delta_update_module.py

See MEN-4246: New delta update test to reveal U-Boot integ bug

MEN-4246: New delta update test to reveal U-Boot integ bug

---

tests/acceptance/test_dbus.py

Remove the state files (store and agent key) after running the dbus tests

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Update mender's LICENSE md5 hash

---

meta-mender-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bbappend
meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi-rt_%.bbappend
meta-mender-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend

mender-raspberrypi: Make kernel settings conditional

---

tests/acceptance/test_dbus.py

Also fix one issue in the test: The bootstrap needs to happen before
the dbus monitor is started, because the bootstrap also broadcasts the
token. This will trigger the check for the broadcast too early, and we
will proceed with other DBus calls before the client is fully up and
running. By starting the monitor after the bootstrap, we know that the
client is up when we receive the signal.

MEN-4294: Re-enable all of the test_dbus_fetch_jwt_token test.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.5.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.5.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect.inc
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb

Cherry-picking new recipes from #1276

master: Mender 2.6.0 release

---

tests/build-conf/beagleboneblack/local.conf
tests/build-conf/qemux86-64-bios-grub-gpt/local.conf
tests/build-conf/qemux86-64-bios-grub/local.conf
tests/build-conf/qemux86-64-uefi-grub/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/local.conf
tests/build-conf/vexpress-qemu/local.conf

Provide a more useful `RM_WORK_EXCLUDE` default in our build files.

---

tests/build-conf/beagleboneblack/bblayers.conf

tests: Add missing meta-oe layer to Beaglebone builds.

---

meta-mender-core/recipes-mender/mender-configure/mender-configure.inc
meta-mender-raspberrypi/recipes-mender/mender-configure/mender-configure_%.bbappend

MEN-4594: Prepopulate the device config in mender-configure-demo.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.1.bb

Add mender-binary-delta-1.2.1 recipe.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.3.bb
tests/acceptance/test_build.py

* Release recipes for 2.4.3
* `min_mender_version` bump for the certificate test

2.4.3 patch versions

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.5.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.1.bb

* New binary delta version recipe
* New client version recipe
* New mender-connect version recipe

Release 2.6.3 versions

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-testing/mender-test-dependencies/mender-test-dependencies_1.0.bb
meta-mender-demo/recipes-mender/mender-client/mender-client_%.bbappend
tests/meta-mender-ci/recipes-testing/mender-coverage-client/mender-client_%.bbappend
tests/meta-mender-ci/recipes-testing/read-only-rootfs/mender-client_%.bbappend

This is an alternative approach for #1352 . See specifically discussion at https://github.com/mendersoftware/meta-mender/pull/1352#discussion_r625143882

MEN-4671: mender-client: New package mender-modules-gen and Update Module tests 

---

tests/acceptance/requirements_py3.txt

dependabot test updates

---

tests/acceptance/requirements_deb.txt

MEN-4106: add rpm to the deb requirements to run acceptance tests

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-testing/mender-test-dependencies/mender-test-dependencies_1.0.bb
tests/acceptance/test_build.py

MEN-4106: mender-client-dev package to distribute D-Bus API specs

---

meta-mender-core/recipes-mender/mender-client/mender-client.inc

Add io.mender.UpdateManager to D-Bus specification files.

---

meta-mender-demo/conf/layer.conf

Add meta-oe as dependency to mender-demo

---

meta-mender-demo/conf/layer.conf

[dunfell] Add meta-oe as dependency to mender-demo

---

meta-mender-demo/conf/layer.conf

[zeus] Add meta-oe as dependency to mender-demo

---

meta-mender-demo/conf/layer.conf

[warrior] Add meta-oe as dependency to mender-demo

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Fix mender-client compile for feature branches.

---

tests/acceptance/test_update_control.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py

Lluis' ones already reviewed in #1400.

Lots of update control test fixes.

---

tests/acceptance/test_update_control.py

MEN-3360: Test infinite test transitions for Update Control.

---

meta-mender-core/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv.inc
meta-mender-core/recipes-bsp/u-boot/u-boot-mender.inc
meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure.inc
meta-mender-demo/recipes-mender/example-state-scripts/files/example-script
tests/acceptance/commercial/test_delta_update_module.py
tests/acceptance/mock_server.py
tests/acceptance/test_dbus.py
tests/acceptance/test_update_control.py
tests/meta-mender-ci/conf/layer.conf
tests/meta-mender-ci/recipes-core/base-files/base-files_%.bbappend
tests/meta-mender-ci/recipes-testing/logger-update-module/logger-update-module.bb
tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/mender-mock-server_1.0.bb

Bringing #1398, #1327, #1403, #1407 and few other minor fixes.

Miscellaneous dunfell updates before release

---

tests/acceptance/mock_server.py
tests/acceptance/test_update_control.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py

Bringing all of https://github.com/mendersoftware/meta-mender/pull/1413 to `dunfell`.

dunfell: tests for update_control_maps feature

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.1.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.2.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.0.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.4.2.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.5.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.5.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.6.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.3.3.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.5.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.5.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_2.6.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.0.0.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_1.0.0.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_1.0.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.0.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.1.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_1.2.0.bb

Changelog: Add mender-client-3.0.0 recipe.
Changelog: Add mender-artifact-3.6.0 recipe.
Changelog: Add mender-connect-1.2.0 recipe.
Changelog: Add mender-configure-1.0.1 recipe.

Add recipes for Mender Product 3.0.0 release.

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor.inc

MEN-4710 Monitoring: ln -s /data/mender-monitor /var/lib/mender-monitor

---

meta-mender-core/recipes-mender/mender-configure/mender-configure.inc

Use ${localstatedir} in mender-configure

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor.inc

MEN-4893 install mender-monitorctl

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor.inc
meta-mender-core/recipes-dbs/lmdb/files/run-ptest
meta-mender-core/recipes-dbs/lmdb/lmdb_0.9.29.bb

This is required for use with the mender-monitor client, which has a dependency
on the mdb_{dump,load} commands.
The recipe is a simple copy-paste from the lmdb recipe in meta-openembedded
master. But since it is not present in any of the releases we rely on, this will
have to be mirrored in our repository for compatibility with the old
releases (Dunfell, and Gatesgarth amongst them).
Thank you!

Add lmdb recipe

---

tests/acceptance/commercial/test_monitor_addon.py

Rename incorrect test class name.

---

meta-mender-qemu/recipes-bsp/u-boot/u-boot-vexpress-qemu.inc

Update comment and refer to new upstreaming ticket.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.3.0.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_1.0.0.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.6.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.1.0.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_1.0.2.bb

Changelog: Add recipe for mender-client 3.1.0
Changelog: Add recipe for mender-artifact 3.6.1
Changelog: Add recipe for mender-monitor 1.0.0
Changelog: Add recipe for mender-binary-delta 1.3.0
Changelog: Add recipe for mender-configure 1.0.2

Release Mender 3.1.0

---

meta-mender-core/recipes-dbs/lmdb/lmdb_0.9.29.bb
tests/meta-mender-ci/recipes-testing/mender-coverage-client/gobinarycoverage.bb

Switch git:// links to https:// links since Github disabled them.

---

meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_git.bb

Previously, build from tarball would generate:
* `mender-monitor-master-gitae0ead3-r0` for internal builds (CI)
* `mender-monitor-master-git-r0` for external builds (users)
This commit makes it a bit nicer:
* `mender-monitor-master-git+ae0ead3-r0` for internal builds
* `mender-monitor-master-r0`for external builds
Also made the parsing more robust, so that it explicitly fails when the
filename is unknown.
Original work by Alan Martinovic <alan.martinovic@northern.tech>

mender-monitor_git: Beatifications and robustness when generating PV

---

.gitlab-ci.yml
meta-mender-core/classes/mender-image-systemd-boot.bbclass
meta-mender-core/classes/mender-maybe-setup.bbclass
meta-mender-core/classes/mender-part-images.bbclass
meta-mender-core/classes/mender-setup-grub.inc
meta-mender-core/classes/mender-setup-image.inc
meta-mender-core/classes/mender-setup-systemd-boot.inc
meta-mender-core/classes/mender-setup.bbclass
meta-mender-core/recipes-bsp/systemd-mender-config/files/ab_setup.py
meta-mender-core/recipes-bsp/systemd-mender-config/systemd-mender-config.bb
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install-efi_%.bbappend
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install.inc
meta-mender-core/recipes-core/initrdscripts/initramfs-module-install_%.bbappend
meta-mender-core/recipes-core/meta/wic-tools.bbappend
meta-mender-core/recipes-core/systemd/files/systemd-boot-slotconfig.patch
meta-mender-core/recipes-core/systemd/systemd-boot_%.bbappend

A resubmit of #1521, with a few fixes on top.

systemd-boot support

---

tests/acceptance/test_dbus.py

MEN-5217: Adapt test to new authorization messages.

---

tests/acceptance/test_update_control.py

MEN-5096: Increase the wait time for 'wait_for_state'

---

LICENSE
LIC_FILES_CHKSUM.sha256
tests/build-conf/raspberrypi3/bblayers.conf
tests/build-conf/raspberrypi4/bblayers.conf

Remove duplicate layer, meta-python, added by mistake.

---

meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Update license checksum for 2022 for Mender client (git).

---

meta-mender-demo/conf/layer.conf
meta-mender-demo/mender-commercial/mender-monitor/mender-monitor_%.bbappend

MEN-5137: Add a demo recipe for the monitor-client example monitors

---

meta-mender-demo/conf/layer.conf
meta-mender-demo/mender-commercial/mender-monitor/mender-monitor_%.bbappend

Cherry-picking #1532, needed for release testing.

dunfell: MEN-5137: Enable demo functionality for the monitor-client

---

meta-mender-core/recipes-mender/mender-client/mender-client_3.2.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.0.1.bb

1) client 3.2.1
2) mender-connect recipe 2.0.1

3.2.1 release version bumps

---

meta-mender-demo/mender-commercial/mender-monitor/mender-monitor_%.bbappend

master: meta-mender-demo: mender-monitor bbappend conditional to the version

---

tests/acceptance/test_mender-connect.py

Fix failures in long test runs because coverage fills up data part.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

Update license checksum for mender-artifact git recipe.

---

README.md

Readme: clarify layer usage and maintenance strategy

---

README.md

Readme: explain maintenenance strategy

---

README.md

Readme: explain maintenance strategy

---

.github/dependabot.yml

While removing gatesgarth and hardknott

dependabot: Add kirkstone target branch

---

tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py
tests/meta-mender-ci/recipes-testing/mender-mock-server/mender-mock-server_1.0.bb

MEN-5542: add the new control map endpoint to the mock-server

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.7.1.bb

fix: Add mender-artifact 3.7.1 recipe.

---

meta-mender-raspberrypi/README.md

Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
Thank you!

meta-mender-raspberrypi: fix outdated README

---

meta-mender-core/classes/mender-dataimg.bbclass
meta-mender-core/classes/mender-part-images.bbclass

This pull request brings a couple of improvements and bug fixes related to F2FS:
* Add a dependency to f2fs-tools-native in `mender-part-images` if using F2FS for the data partition.
* Load Mender configuration files to the data partition when using F2FS through `sload.f2fs` in class `dataimg`.

Master f2fs fix

---

meta-mender-qemu/docker/build-docker
meta-mender-qemu/docker/qemux86-64/Dockerfile
meta-mender-qemu/scripts/docker/extract_fs

goes with: https://github.com/mendersoftware/mender-qa/pull/583
ChangeLog: none
(cherry picked from commit b09623d194ce9aecb7f89787cf5566bdf66ec2e8)

QA-387 Embed a clean image

---

tests/acceptance/requirements_deb.txt

required for [this](https://gitlab.com/Northern.tech/Mender/mender-test-containers/-/jobs/2525911215#L919) to build in order for https://github.com/mendersoftware/mender-test-containers/pull/167 to be merged

chore: updated test requirements to allow base image update

---

meta-mender-core/recipes-mender/mender-configure/mender-configure_1.0.4.bb

chore: add mender-configure-module 1.0.4.bb

---

tests/build-conf/beagleboneblack/local.conf
tests/build-conf/qemux86-64-bios-grub-gpt/local.conf
tests/build-conf/qemux86-64-bios-grub/local.conf
tests/build-conf/qemux86-64-uefi-grub/local.conf
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/local.conf
tests/build-conf/vexpress-qemu/local.conf
tests/meta-mender-ci/conf/layer.conf

Just cherry-picks, which have already been reviewed in the master-next branch.

Changes to support interoperability with kirkstone.

---

tests/acceptance/test_dbus.py

test: Adapt test to cover all three GetJwtToken server addresses.

---

LIC_FILES_CHKSUM.sha256
meta-mender-demo/recipes-connectivity/qemu-connectivity-helper/files/LICENSE
meta-mender-demo/recipes-connectivity/qemu-connectivity-helper/files/qemu-connectivity-helper.service
meta-mender-demo/recipes-connectivity/qemu-connectivity-helper/qemu-connectivity-helper.bb

Simply create a unit file which runs after the mender-client and/or the
mender-gateway, and sleeps for 10 seconds during the shutdown of the system.
Ticket: MEN-5567

test: Add a systemd service to help mitigate the Qemu connection err

---

meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh
meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_patch.sh
meta-mender-core/recipes-core/initrdscripts/files/init-install-efi-mender.sh
meta-mender-core/recipes-mender/mender-client/files/mender-client-set-systemd-machine-id.sh
meta-mender-demo/recipes-mender/boot-script/files/boot-script.sh
meta-mender-qemu/scripts/docker/entrypoint.sh

chore: license fix for .sh files.

---

meta-mender-core/recipes-mender/mender-client/files/mender-client-resize-data-part.sh.in
meta-mender-core/recipes-mender/mender-client/mender-client.inc
meta-mender-qemu/scripts/mender-qemu
tests/acceptance/requirements_py3.txt
tests/acceptance/test_uboot_automation.py

Resubmission of #1720, with additional cherry-picks from master to deal with recent build host upgrades.

Resubmission of #1720

---

tests/acceptance/test_update_control.py

test: Add acceptance test for pausing before a manual reboot.

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.4.0.bb

dunfell: feat: add recipe for mender-binary-delta 1.4.0

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact.inc
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb

dunfell: feat: mender-artifact: Add OpenSSL dependency

---

tests/acceptance/test_dbus.py

test: Test that we only listen on one port, and only on 127.0.0.1.

---

tests/acceptance/requirements_py3.txt

#1739, #1744, #1754, #1769 and #1770.

Dependabot updates for upcoming release

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta.inc
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.1.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.1.2.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.0.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.2.1.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.3.0.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.4.0.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.4.1.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_1.0.1.bb
meta-mender-commercial/recipes-mender/mender-monitor/mender-monitor_1.2.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.9.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.4.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.1.0.bb

Changelog: Add recipe for mender-client 3.4.0
Changelog: Add recipe for mender-artifact 3.9.0
Changelog: Add recipe for mender-connect 2.1.0
Changelog: Add recipe for mender-binary-delta 1.4.1
Changelog: Add recipe for mender-monitor 1.2.1
Changelog: Add recipe for mender-gateway 1.0.1

dunfell: Release Mender 3.4.0

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_1.2.1.bb
meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.4.1.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_1.0.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.9.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.4.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.1.0.bb

Changelog: Add recipe for mender-client 3.4.0
Changelog: Add recipe for mender-artifact 3.9.0
Changelog: Add recipe for mender-connect 2.1.0
Changelog: Add recipe for mender-binary-delta 1.4.1 Changelog: Add recipe for mender-monitor 1.2.1
Changelog: Add recipe for mender-gateway 1.0.1

kirkstone: Release Mender 3.4.0

---

tests/acceptance/pytest.ini
tests/acceptance/requirements_py3.txt
tests/acceptance/test_dbus.py
tests/acceptance/test_update_control.py

test: Fix pytest `--capture` argument by removing Fabric.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.8.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.3.1.bb

feat: Add mender-client_3.3.1 and mender-artifact_3.8.1 recipes.

---

meta-mender-core/classes/mender-bootstrap-artifact.bbclass
meta-mender-core/recipes-mender/mender-client/mender-client_3.4.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Mostly cherry-picked and adapted from dunfell.

Fixes for bootstrap artifact

---

meta-mender-core/classes/mender-bootstrap-artifact.bbclass
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.8.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.3.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.4.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc

Building on #1822, ignore all but the last commit.

3.3.1 Mender recipes

---

tests/build-conf/beagleboneblack/local.conf
tests/build-conf/qemux86-64-bios-grub-gpt/local.conf
tests/build-conf/qemux86-64-bios-grub/local.conf
tests/build-conf/qemux86-64-uefi-grub/local.conf
tests/build-conf/raspberrypi3/local.conf
tests/build-conf/raspberrypi4/local.conf
tests/build-conf/vexpress-qemu-flash/local.conf
tests/build-conf/vexpress-qemu-uboot-uefi-grub/local.conf
tests/build-conf/vexpress-qemu/local.conf

fix: Work around `externalsrc_configure_prefunc` race condition.

---

tests/acceptance/requirements_py3.txt

#1832, #1833, #1834, #1835 and #1836.

Dependabot updates for pip ecosystem

---

tests/acceptance/test_update_control.py

test: Add some logging to aid in debugging test timing.

---

tests/acceptance/test_mender-connect.py

Ticket: [QA-483](https://tracker.mender.io/browse/QA-483)

chore: Disable test_mender_connect_auth_changes test

---

tests/acceptance/requirements_py3.txt

Dependabot test dependencies updates

---

tests/acceptance/requirements_py3.txt

#1874, #1875, #1876, #1877 and #1878.

Dependabot updates January 2023

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_git.bb

chore: update checksum for the mender-gateway LICENSE

---

meta-mender-core/classes/grub-mender-grubenv.bbclass

No changelog, because this was never released.
Ticket: None

fix(grub-mender-grubenv): Fix sh-compatibility issue.

---

tests/acceptance/requirements_py3.txt

#1896, #1897, #1898, #1899 and #1900.

Dependabot test updates Februrary

---

meta-mender-core/recipes-bsp/grub/mender-grub-efi-impl.inc

master: fix: Remove grub.efi resource files using pseudo.

---

tests/acceptance/test_build.py

kirkstone: test: Conditionally verify the bootstrap Artifact

---

meta-mender-core/recipes-mender/mender-client/mender-client_3.3.2.bb

fix: Add mender-client 3.3.2 recipe.

---

meta-mender-commercial/conf/layer.conf
meta-mender-core/recipes-extended/images/mender-image-full-cmdline-rofs.bb

chore: update bug tracker link

---

meta-mender-core/recipes-mender/mender-client/mender_3.99.0+really4.0.0-alpha1.bb

feat: Add first alpha release of Mender C++ client.

---

tests/acceptance/requirements_py3.in
tests/acceptance/requirements_py3.txt

They went missing in c25129566c4d00bc8ee20f87526969a33af937b0

test: Add missing pip dependencies

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_1.3.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.10.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.5.1.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_1.1.0.bb

Changelog: Add recipe for mender-artifact 3.10.1
Changelog: Add recipe for mender-client 3.5.1
Changelog: Add recipe for mender-configure 1.1.0
Changelog: Add recipe for mender-monitor 1.3.0

chore: Add recipes for release Mender 3.6.0

---

tests/acceptance/requirements_py3.in
tests/acceptance/requirements_py3.txt

chore: Update `filelock` and tests submodule

---

tests/acceptance/requirements_py3.in
tests/acceptance/requirements_py3.txt

chore: dependabot updates for client acceptance tests

---

tests/acceptance/requirements_py3.in
tests/acceptance/requirements_py3.txt

Test dependencies updates

---

meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot.inc
meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot_git.bb

Adds the `mender-snapshot` git recipe
Ticket: MEN-6861

Add the mender-snapshot recipe

---

meta-mender-core/recipes-mender/mender-flash/mender-flash_1.0.0.bb

This tool will be used by Mender client 4.0.0 and later to do rootfs-image updates.
Ticket: MEN-6279

feat: Add recipe for mender-flash-1.0.0.

---

meta-mender-core/recipes-mender/mender-client/mender-client-go.inc
meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files-3.x.inc
meta-mender-qemu/recipes-mender/mender-client/mender-client_%.bbappend

They do not influence production, and thus they belong in the dev package.

refac: mender-client: Move DBus xml files to dev package.

---

meta-mender-core/classes/mender-helpers.bbclass
tests/acceptance/test_build.py

Fix mount option defaults being typo'd to default.

fix: typo of mount option.

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.11.0.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.5.2.bb
meta-mender-core/recipes-mender/mender-configure/mender-configure_1.1.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.2.0.bb

Ticket: None
```
```
Thank you!

feat: add recipes for the client components in Mender 3.7.0

---

meta-mender-core/recipes-mender/mender-connect/mender-connect_2.2.0.bb

fix: missing license in mender-connect

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_1.2.0.bb

feat: add recipes for mender-gateway 1.2.0

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_git.bb

Goes with:
* https://github.com/mendersoftware/mender-gateway/pull/136

chore: Update license checksum for `mender-gateway` git recipe

---

meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.11.2.bb
meta-mender-core/recipes-mender/mender-client/mender_4.0.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.2.1.bb

feat: add recipes for the client components in Mender 3.7.2

---

tests/acceptance/test_mender-connect.py

Changed error check in test_mender-connect to check the new error message in connectiomanager.
https://github.com/mendersoftware/mender-connect/pull/118/commits/9b7def234b9bfeff046166dbc8ca11c20186fdf3
Ticket: MEN-5782

test: updated test to be compatible with backoff in mender-connect

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_git.bb

Follow-up from:
* https://github.com/mendersoftware/monitor-client/pull/137

chore: Update LICENSE checksum for `mender-monitor` git recipe

---

meta-mender-commercial/recipes-mender/mender-binary-delta/mender-binary-delta_1.5.0.bb
meta-mender-core/recipes-mender/mender-client/mender_4.0.2.bb

Changelog: Add recipe for `mender-binary-delta` 1.5.0
Changelog: Add recipe for `mender-client` 4.0.2

chore: Add recipes for Mender 3.7.3 release

---

meta-mender-core/recipes-mender/mender-client/mender_4.0.3.bb

feat: Add Mender client 4.0.3 recipe.

---

meta-mender-core/recipes-mender/mender-client/mender-client_3.5.1.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.5.2.bb
meta-mender-core/recipes-mender/mender-client/mender-client_3.5.3.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.1.1.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.1.2.bb

Porting the recipes from #2130 with a fix for the previous update.

Dunfell 3.6.5

---

meta-mender-demo/recipes-connectivity/pkcs11-provider/pkcs11-provider.bb
meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files-3.x.inc
meta-mender-qemu/recipes-mender/mender-client/mender-client-test-files.inc
meta-mender-qemu/recipes-mender/mender-client/mender_%.bbappend

Commits are cherry-picked from https://github.com/mendersoftware/meta-mender/pull/2002

feat: Add a pkcs11-provider recipe

---

meta-mender-qemu/docker/qemux86-64/Dockerfile

Cherry-picking #2157 and every other previous PR updating the `Dockerfile`.

kirkstone: Update Docker base image to latest Alpine

---

tests/acceptance/test_build.py

See:
* https://github.com/mendersoftware/mender/pull/1693

MEN-7672: Adjust test following the move of Update Modules

---

.github/dependabot.yml

Removing now EOL dunfell and adding missing scarthgap

ci: Update dependabot target branch for tests

---

meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_1.2.1.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_3.11.3.bb
meta-mender-core/recipes-mender/mender-client/mender_4.0.5.bb

Changelog: Add recipe for `mender` 4.0.5
Changelog: Add recipe for `mender-artifact` 3.11.3
Changelog: Add recipe for `mender-gateway` 1.2.1

master: Add recipes from Mender 3.7 LTS release

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_1.4.0.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_2.0.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_4.0.0.bb
meta-mender-core/recipes-mender/mender-client/mender_5.0.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.3.0.bb
tests/acceptance/requirements_deb.txt

Porting #2226 and test commits.

kirkstone: Add recipes from Mender Client and Mender Gateway releases

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_1.4.0.bb
meta-mender-commercial/recipes-mender/mender-gateway/mender-gateway_2.0.0.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_4.0.0.bb
meta-mender-core/recipes-mender/mender-client/mender_5.0.0.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.3.0.bb
tests/acceptance/requirements_deb.txt

Porting #2226 and test commits.

scarthgap: Add recipes from Mender Client and Mender Gateway releases

---

meta-mender-core/recipes-mender/mender-client/mender_4.0.6.bb

scarthgap: Add recipe for `mender` 4.0.6

---

LICENSE
LIC_FILES_CHKSUM.sha256
meta-mender-commercial/conditional/mender-monitor/mender-monitor_git.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-core/recipes-mender/mender-flash/mender-flash_git.bb
meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot_git.bb

Bump license

---

LICENSE
LIC_FILES_CHKSUM.sha256
meta-mender-commercial/conditional/mender-monitor/mender-monitor_git.bb
meta-mender-core/recipes-mender/mender-artifact/mender-artifact_git.bb
meta-mender-core/recipes-mender/mender-client/mender-client_git.inc
meta-mender-core/recipes-mender/mender-configure/mender-configure_git.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_git.bb
meta-mender-core/recipes-mender/mender-flash/mender-flash_git.bb
meta-mender-core/recipes-mender/mender-snapshot/mender-snapshot_git.bb

kirkstone: Bump license

---

tests/acceptance/test_build.py

scarthgap: QA-832: Simplify `test_preferred_versions`

---

tests/acceptance/test_build.py

Recreating #2247 for `kirkstone`

kirkstone: QA-832: Simplify `test_preferred_versions`

---

tests/meta-mender-ci/recipes-connectivity/openssh/openssh_%.bbappend

https://northerntech.atlassian.net/browse/QA-472
- increases limits on SSH connections and auth attempts in the CI image

fix: remove ssh server limits on connections for testing

---

meta-mender-commercial/conditional/mender-monitor/mender-monitor_1.4.2.bb
meta-mender-core/recipes-mender/mender-client/mender_5.0.2.bb
meta-mender-core/recipes-mender/mender-connect/mender-connect_2.3.1.bb

Changelog: Add recipe for `mender` 5.0.2
Changelog: Add recipe for `mender-connect` 2.3.1
Changelog: Add recipe for `mender-monitor` 1.4.2

chore: release Mender Client LTS 5.0

---

meta-mender-commercial/recipes-mender/mender-orchestrator/mender-orchestrator.inc
meta-mender-commercial/recipes-mender/mender-orchestrator/mender-orchestrator_0.1.bb
meta-mender-commercial/recipes-mender/mender-orchestrator/mender-orchestrator_git.bb
tests/acceptance/commercial/files/topology.yaml
tests/acceptance/commercial/test_mender-orchestrator.py

feat: add commercial recipe for mender-orchestrator
There is no `0.1` tag; this is just an arbitrary version since we don't
have any tags yet.
Add build test
Ticket: MEN-7015

feat: add commercial recipe for mender-orchestrator
